Repository microsoft/iot-cardboard-js, pull requests merged in 2022-08, with the labels that each got.

#658 import fixes into staging
  src/Components/OATGraphViewer/OATGraphViewer.tsx
  src/Components/OATHeader/OATHeader.tsx
  src/Components/OATPropertyEditor/JSONEditor.tsx
  src/Models/Services/Utils.ts
  src/Resources/Locales/cs.json
  src/Resources/Locales/de.json
  src/Resources/Locales/en.json
  src/Resources/Locales/es.json
  src/Resources/Locales/fr.json
  src/Resources/Locales/hu.json
  src/Resources/Locales/it.json
  src/Resources/Locales/ja.json
  src/Resources/Locales/ko.json
  src/Resources/Locales/nl.json
  src/Resources/Locales/pl.json
  src/Resources/Locales/pt-pt.json
  src/Resources/Locales/pt.json
  src/Resources/Locales/ru.json
  src/Resources/Locales/sv.json
  src/Resources/Locales/tr.json
  src/Resources/Locales/zh-Hans.json
Labels: zarmada internal PR

#597 Element form should prompt anytime you navigate away and there are changes pending
  package-lock.json
  package.json
  src/Components/ADT3DSceneBuilder/ADT3DSceneBuilder.types.ts
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/BehaviorsForm.tsx
  src/Components/ADT3DSceneBuilder/Internal/BuilderLeftPanel/BuilderLeftPanel.tsx
  src/Components/ADT3DSceneBuilder/Internal/Elements/ElementForm.tsx
  src/Components/ADT3DSceneBuilder/Internal/Elements/Internal/AliasedTwinsTab.tsx
  src/Components/ADT3DSceneBuilder/Internal/Elements/Internal/BehaviorsTab.tsx
  src/Components/ADT3DSceneBuilder/Internal/Elements/Internal/ElementTwinAliasForm.tsx
  src/Components/ADT3DViewer/ADT3DViewer.tsx
  src/Models/Classes/3DVConfig.ts
  src/Models/Classes/ViewerConfigUtility.ts
  src/Models/Constants/Interfaces.ts
  src/Models/Context/BehaviorFormContext/BehaviorFormContext.stories.tsx
  src/Models/Context/ElementsFormContext/ElementFormContext.mock.ts
  src/Models/Context/ElementsFormContext/ElementFormContext.stories.tsx
  src/Models/Context/ElementsFormContext/ElementFormContext.test.tsx
  src/Models/Context/ElementsFormContext/ElementFormContext.tsx
  src/Models/Context/ElementsFormContext/ElementFormContext.types.ts
  src/Models/Context/ElementsFormContext/ElementFormContextUtility.test.ts
  src/Models/Context/ElementsFormContext/ElementFormContextUtility.ts
  src/Models/Services/Utils.ts
Labels: enhancement :bulb:, large change :ocean:, refactor :hammer:

#623 Story demonstrating gizmo action using SceneView
  src/Components/3DV/SceneView.stories.tsx
  src/Components/3DV/SceneView.tsx
  src/Components/3DV/SceneViewWithGizmoWrapper.tsx
  src/Components/ADT3DBuilder/ADT3DBuilder.tsx
  src/Components/ADT3DBuilder/ADT3DBuilder.types.ts
  src/Components/ADT3DSceneBuilder/ADT3DSceneBuilder.state.ts
  src/Components/ADT3DSceneBuilder/ADT3DSceneBuilder.tsx
  src/Components/ADT3DSceneBuilder/ADT3DSceneBuilder.types.ts
  src/Models/Classes/SceneView.types.ts
  src/Models/Classes/__tests__/__snapshots__/ViewerConfigUtility.test.ts.snap
  src/Resources/Locales/cs.json
  src/Resources/Locales/de.json
  src/Resources/Locales/en.json
  src/Resources/Locales/es.json
  src/Resources/Locales/fr.json
  src/Resources/Locales/hu.json
  src/Resources/Locales/it.json
  src/Resources/Locales/ja.json
  src/Resources/Locales/ko.json
  src/Resources/Locales/nl.json
  src/Resources/Locales/pl.json
  src/Resources/Locales/pt-pt.json
  src/Resources/Locales/pt.json
  src/Resources/Locales/ru.json
  src/Resources/Locales/sv.json
  src/Resources/Locales/tr.json
  src/Resources/Locales/zh-Hans.json
Labels: small change :droplet:

#661 Move theme control to be with the rest of the header controls
  src/Components/3DV/SceneViewWrapper.styles.ts
  src/Components/3DV/SceneViewWrapper.tsx
  src/Components/3DV/SceneViewWrapper.types.ts
  src/Components/ADT3DBuilder/ADT3DBuilder.tsx
  src/Components/ADT3DBuilder/ADT3DBuilder.types.ts
  src/Components/ADT3DViewer/ADT3DViewer.tsx
  src/Models/Constants/Interfaces.ts
Labels: small change :droplet:, refactor :hammer:

#660 tooltip hover fix
  src/Components/TooltipCallout/TooltipCallout.styles.ts
  src/Components/TooltipCallout/TooltipCallout.tsx
  src/Components/TooltipCallout/TooltipCallout.types.ts
Labels: bugfix :bug: :white_check_mark:, small change :droplet:

#663 Advanced search boilerplate
  src/Components/AdvancedSearch/AdvancedSearch.stories.tsx
  src/Components/AdvancedSearch/AdvancedSearch.styles.ts
  src/Components/AdvancedSearch/AdvancedSearch.types.ts
  src/Components/AdvancedSearch/AdvancedSearchModal.tsx
  src/Components/AdvancedSearch/Internal/AdvancedSearchResults.tsx
  src/Components/AdvancedSearch/Internal/QueryBuilder.tsx
Labels: small change :droplet:, wip 🚧

#662 Zarmada/working/ADTS-278-
  src/Components/OATHeader/internal/FileSubMenu.tsx
  src/Components/OATHeader/internal/FormOpen.tsx
  src/Components/OATHeader/internal/FormSaveAs.tsx
  src/Components/OATHeader/internal/ModalDelete.tsx
  src/Resources/Locales/cs.json
  src/Resources/Locales/de.json
  src/Resources/Locales/en.json
  src/Resources/Locales/es.json
  src/Resources/Locales/fr.json
  src/Resources/Locales/hu.json
  src/Resources/Locales/it.json
  src/Resources/Locales/ja.json
  src/Resources/Locales/ko.json
  src/Resources/Locales/nl.json
  src/Resources/Locales/pl.json
  src/Resources/Locales/pt-pt.json
  src/Resources/Locales/pt.json
  src/Resources/Locales/ru.json
  src/Resources/Locales/sv.json
  src/Resources/Locales/tr.json
  src/Resources/Locales/zh-Hans.json
Labels: zarmada internal PR

#647 fixed error where PI could not read fields of properties that were enums
  src/Components/PropertyInspector/PropertyInspectoryModel.ts
  src/Components/PropertyInspector/PropertyTree/PropertyTree.scss
Labels: bugfix :bug: :white_check_mark:, small change :droplet:

#664 Story demonstrating transform using SceneView
  src/Components/3DV/SceneView.Utils.tsx
  src/Components/3DV/SceneView.stories.tsx
  src/Components/3DV/SceneView.tsx
  src/Models/Classes/SceneView.types.ts
Labels: small change :droplet:

#673 Fixing SceneThemeContext error
  src/Components/ADT3DBuilder/ADT3DBuilder.stories.local.tsx
  src/Components/ADT3DSceneBuilder/ADT3DSceneBuilder.state.ts
Labels: bugfix :bug: :white_check_mark:, small change :droplet:

#611 SceneViewContext phase 1
  src/Components/3DV/SceneViewWrapper.tsx
  src/Components/ADT3DBuilder/ADT3DBuilder.tsx
  src/Components/ADT3DBuilder/ADT3DBuilder.types.ts
  src/Components/ADT3DSceneBuilder/ADT3DSceneBuilder.state.ts
  src/Components/ADT3DSceneBuilder/ADT3DSceneBuilder.tsx
  src/Components/ADT3DSceneBuilder/ADT3DSceneBuilder.types.ts
  src/Components/ADT3DSceneBuilder/Internal/BuilderLeftPanel/BuilderLeftPanel.tsx
  src/Components/ADT3DSceneBuilder/Internal/Elements/Elements.tsx
  src/Components/ADT3DViewer/ADT3DViewer.stories.tsx
  src/Components/ADT3DViewer/ADT3DViewer.tsx
  src/Components/AlertModal/AlertModal.stories.tsx
  src/Components/BehaviorsModal/BehaviorsModal.stories.tsx
  src/Components/ElementsPanel/ViewerElementsPanel.stories.tsx
  src/Components/StatusPills/StatusPills.stories.tsx
  src/Models/Context/SceneViewContext/SceneViewContext.mock.ts
  src/Models/Context/SceneViewContext/SceneViewContext.test.tsx
  src/Models/Context/SceneViewContext/SceneViewContext.tsx
  src/Models/Context/SceneViewContext/SceneViewContext.types.ts
  src/Models/Context/index.ts
Labels: refactor :hammer:

#675 Clear timeouts on unmount of scene refresh control
  src/Components/DeeplinkFlyout/DeeplinkFlyout.tsx
  src/Components/SceneRefreshButton/SceneRefreshButton.tsx
Labels: bugfix :bug: :white_check_mark:, small change :droplet:

#670 Add ability to configure a dynamic refresh rate to the builder experience
  schemas/3DScenesConfiguration/v1.0.0/3DScenesConfiguration.schema.json
  src/Adapters/__mockData__/3DScenesConfiguration.json
  src/Components/ADT3DSceneBuilder/ADT3DSceneBuilder.tsx
  src/Components/ADT3DViewer/ADT3DViewer.tsx
  src/Components/HeaderControlButtonWithCallout/HeaderControlButtonWithCallout.stories.tsx
  src/Components/HeaderControlButtonWithCallout/HeaderControlButtonWithCallout.styles.ts
  src/Components/HeaderControlButtonWithCallout/HeaderControlButtonWithCallout.tsx
  src/Components/HeaderControlButtonWithCallout/HeaderControlButtonWithCallout.types.ts
  src/Components/ModelViewerModePicker/ModelViewerModePicker.styles.ts
  src/Components/ModelViewerModePicker/ModelViewerModePicker.tsx
  src/Components/ModelViewerModePicker/ModelViewerModePicker.types.ts
  src/Components/SceneRefreshButton/SceneRefreshButton.stories.tsx
  src/Components/SceneRefreshButton/SceneRefreshButton.tsx
  src/Components/SceneRefreshButton/SceneRefreshButton.types.ts
  src/Components/SceneRefreshConfigurator/SceneRefreshConfigurator.stories.tsx
  src/Components/SceneRefreshConfigurator/SceneRefreshConfigurator.styles.ts
  src/Components/SceneRefreshConfigurator/SceneRefreshConfigurator.tsx
  src/Components/SceneRefreshConfigurator/SceneRefreshConfigurator.types.ts
  src/Models/Classes/AdapterEntityCache.ts
  src/Models/Classes/ViewerConfigUtility.ts
  src/Models/Classes/__tests__/ViewerConfigUtility.test.ts
  src/Models/Constants/Constants.ts
  src/Models/Constants/Types.ts
  src/Models/Context/DeeplinkContext/DeeplinkContext.tsx
  src/Models/Hooks/useRuntimeSceneData.ts
  src/Models/Services/Utils.ts
  src/Models/Types/Generated/3DScenesConfiguration-v1.0.0.d.ts
  src/Resources/Locales/cs.json
  src/Resources/Locales/de.json
  src/Resources/Locales/en.json
  src/Resources/Locales/es.json
  src/Resources/Locales/fr.json
  src/Resources/Locales/hu.json
  src/Resources/Locales/it.json
  src/Resources/Locales/ja.json
  src/Resources/Locales/ko.json
  src/Resources/Locales/nl.json
  src/Resources/Locales/pl.json
  src/Resources/Locales/pt-pt.json
  src/Resources/Locales/pt.json
  src/Resources/Locales/ru.json
  src/Resources/Locales/sv.json
  src/Resources/Locales/tr.json
  src/Resources/Locales/zh-Hans.json
  tools/templates/component/component.js
Labels: enhancement :bulb:, large change :ocean:

#585 ResourcePicker component and changes in EnvironmentPicker
  .eslintrc.json
  .storybook/secrets.placeholder.js
  src/Adapters/ADT3DSceneAdapter.ts
  src/Adapters/ADTAdapter.ts
  src/Adapters/AzureManagementAdapter.ts
  src/Adapters/BlobAdapter.ts
  src/Adapters/MockAdapter.ts
  src/Components/ADTInstances/ADTInstances.scss
  src/Components/ADTInstances/ADTInstances.stories.local.tsx
  src/Components/ADTInstances/ADTInstances.tsx
  src/Components/EnvironmentPicker/EnvironmentPicker.scss
  src/Components/EnvironmentPicker/EnvironmentPicker.state.ts
  src/Components/EnvironmentPicker/EnvironmentPicker.stories.local.tsx
  src/Components/EnvironmentPicker/EnvironmentPicker.tsx
  src/Components/EnvironmentPicker/EnvironmentPicker.types.ts
  src/Components/EnvironmentPicker/EnvironmentPickerManager.ts
  src/Components/ResourcePicker/ResourcePicker.stories.local.tsx
  src/Components/ResourcePicker/ResourcePicker.stories.tsx
  src/Components/ResourcePicker/ResourcePicker.styles.ts
  src/Components/ResourcePicker/ResourcePicker.tsx
  src/Components/ResourcePicker/ResourcePicker.types.ts
  src/Components/index.ts
  src/Models/Classes/AdapterDataClasses/AzureManagementData.ts
  src/Models/Classes/AdapterDataClasses/StorageData.ts
  src/Models/Constants/Constants.ts
  src/Models/Constants/Enums.ts
  src/Models/Constants/Interfaces.ts
  src/Models/Constants/Types.ts
  src/Models/Context/DeeplinkContext/DeeplinkContext.mock.ts
  src/Models/Context/DeeplinkContext/DeeplinkContext.stories.tsx
  src/Models/Context/DeeplinkContext/DeeplinkContext.tsx
  src/Models/Context/DeeplinkContext/DeeplinkContext.types.ts
  src/Models/Services/Utils.ts
  src/Pages/ADT3DScenePage/ADT3DScenePage.stories.tsx
  src/Pages/ADT3DScenePage/ADT3DScenePage.tsx
  src/Resources/Locales/cs.json
  src/Resources/Locales/de.json
  src/Resources/Locales/en.json
  src/Resources/Locales/es.json
  src/Resources/Locales/fr.json
  src/Resources/Locales/hu.json
  src/Resources/Locales/it.json
  src/Resources/Locales/ja.json
  src/Resources/Locales/ko.json
  src/Resources/Locales/nl.json
  src/Resources/Locales/pl.json
  src/Resources/Locales/pt-pt.json
  src/Resources/Locales/pt.json
  src/Resources/Locales/ru.json
  src/Resources/Locales/sv.json
  src/Resources/Locales/tr.json
  src/Resources/Locales/zh-Hans.json
Labels: enhancement :bulb:, large change :ocean:, refactor :hammer:

#680 Add metrics telemetry event and rename existing types
  src/Components/SceneList/SceneList.tsx
  src/Models/Hooks/useTelemetry.ts
  src/Models/Services/TelemetryService/Telemetry.ts
  src/Models/Services/TelemetryService/TelemetryService.ts
  src/Models/Services/TelemetryService/TelemetryService.types.ts
  src/Models/Services/TelemetryService/__tests__/TelemetryService.test.ts
Labels: enhancement :bulb:, small change :droplet:

#668 Advanced Search Results, DetailsList
  src/Components/AdvancedSearch/AdvancedSearchModal.tsx
  src/Components/AdvancedSearch/Internal/AdvancedSearchResultDetailsList/AdvancedSearchResultDetailsList.stories.tsx
  src/Components/AdvancedSearch/Internal/AdvancedSearchResultDetailsList/AdvancedSearchResultDetailsList.styles.ts
  src/Components/AdvancedSearch/Internal/AdvancedSearchResultDetailsList/AdvancedSearchResultDetailsList.tsx
  src/Components/AdvancedSearch/Internal/AdvancedSearchResultDetailsList/AdvancedSearchResultDetailsList.types.ts
  src/Components/AdvancedSearch/Internal/AdvancedSearchResults.tsx
  src/Resources/Locales/cs.json
  src/Resources/Locales/de.json
  src/Resources/Locales/en.json
  src/Resources/Locales/es.json
  src/Resources/Locales/fr.json
  src/Resources/Locales/hu.json
  src/Resources/Locales/it.json
  src/Resources/Locales/ja.json
  src/Resources/Locales/ko.json
  src/Resources/Locales/nl.json
  src/Resources/Locales/pl.json
  src/Resources/Locales/pt-pt.json
  src/Resources/Locales/pt.json
  src/Resources/Locales/ru.json
  src/Resources/Locales/sv.json
  src/Resources/Locales/tr.json
  src/Resources/Locales/zh-Hans.json
Labels: wip 🚧

#684 ResourcePicker cleanup
  src/Adapters/ADT3DSceneAdapter.ts
  src/Adapters/AzureManagementAdapter.ts
  src/Adapters/BlobAdapter.ts
  src/Adapters/MockAdapter.ts
  src/Components/EnvironmentPicker/EnvironmentPicker.mock.ts
  src/Components/EnvironmentPicker/EnvironmentPicker.state.ts
  src/Components/EnvironmentPicker/EnvironmentPicker.stories.local.tsx
  src/Components/EnvironmentPicker/EnvironmentPicker.stories.tsx
  src/Components/EnvironmentPicker/EnvironmentPicker.test.tsx
  src/Components/EnvironmentPicker/EnvironmentPicker.tsx
  src/Components/EnvironmentPicker/EnvironmentPicker.types.ts
  src/Components/EnvironmentPicker/EnvironmentPickerManager.test.ts
  src/Components/EnvironmentPicker/EnvironmentPickerManager.ts
  src/Components/ResourcePicker/ResourcePicker.stories.local.tsx
  src/Components/ResourcePicker/ResourcePicker.stories.tsx
  src/Components/ResourcePicker/ResourcePicker.tsx
  src/Components/ResourcePicker/ResourcePicker.types.ts
  src/Components/ScenePageErrorHandlingWrapper/Internal/UnauthorizedAccessHandling.tsx
  src/Models/Classes/AdapterDataClasses/AzureManagementData.ts
  src/Models/Constants/Constants.ts
  src/Models/Constants/Interfaces.ts
  src/Models/Constants/Types.ts
  src/Models/Context/DeeplinkContext/DeeplinkContext.mock.ts
  src/Models/Context/DeeplinkContext/DeeplinkContext.stories.tsx
  src/Models/Context/DeeplinkContext/DeeplinkContext.tsx
  src/Models/Context/DeeplinkContext/DeeplinkContext.types.ts
  src/Models/Services/Utils.test.ts
  src/Models/Services/Utils.ts
  src/Pages/ADT3DScenePage/ADT3DScenePage.stories.local.tsx
  src/Pages/ADT3DScenePage/ADT3DScenePage.stories.tsx
  src/Pages/ADT3DScenePage/ADT3DScenePage.tsx
  src/Pages/ADT3DScenePage/ADT3DScenePage.types.ts
  src/Resources/Locales/cs.json
  src/Resources/Locales/de.json
  src/Resources/Locales/en.json
  src/Resources/Locales/es.json
  src/Resources/Locales/fr.json
  src/Resources/Locales/hu.json
  src/Resources/Locales/it.json
  src/Resources/Locales/ja.json
  src/Resources/Locales/ko.json
  src/Resources/Locales/nl.json
  src/Resources/Locales/pl.json
  src/Resources/Locales/pt-pt.json
  src/Resources/Locales/pt.json
  src/Resources/Locales/ru.json
  src/Resources/Locales/sv.json
  src/Resources/Locales/tr.json
  src/Resources/Locales/zh-Hans.json
Labels: small change :droplet:, refactor :hammer:, tests :mag:, typings :lock:
