Repository microsoft/iot-cardboard-js, pull requests merged in 2022-11, with the labels that each got.

#749 [Data history]: Content pass with PM and Design
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/Widgets/WidgetBuilders/DataHistoryWidgetBuilder/DataHistoryWidgetBuilder.tsx
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/Widgets/WidgetBuilders/DataHistoryWidgetBuilder/Internal/TimeSeriesFormCallout.tsx
  src/Components/HighChartsWrapper/HighChartsWrapper.tsx
  src/Models/Services/Utils.ts
  src/Resources/Locales/cs.json
  src/Resources/Locales/de.json
  src/Resources/Locales/en.json
  src/Resources/Locales/es.json
  src/Resources/Locales/fr.json
  src/Resources/Locales/hu.json
  src/Resources/Locales/it.json
  src/Resources/Locales/ja.json
  src/Resources/Locales/ko.json
  src/Resources/Locales/nl.json
  src/Resources/Locales/pl.json
  src/Resources/Locales/pt-pt.json
  src/Resources/Locales/pt.json
  src/Resources/Locales/ru.json
  src/Resources/Locales/sv.json
  src/Resources/Locales/tr.json
  src/Resources/Locales/zh-Hans.json
Labels: small change :droplet:, refactor :hammer:

#750 Flight data migrations for Visual rules
  src/Adapters/BlobAdapter.ts
Labels: small change :droplet:

#757 [Bugfix] Highchart module import fix for build
  src/Components/HighChartsWrapper/HighChartsWrapper.tsx
Labels: bugfix :bug: :white_check_mark:

#746 Styling: Add extended palette to the theme
  src/Models/Hooks/useExtendedTheme.ts
  src/Theming/FluentThemes.ts
  src/Theming/Palettes.ts
  src/Theming/Theme.types.ts
Labels: enhancement :bulb:, styling :art:

#758 OAT: Restyle property editor
  src/Components/OATGraphViewer/Internal/GraphViewerControls/GraphViewerControls.styles.ts
  src/Components/OATGraphViewer/OATGraphViewer.styles.tsx
  src/Components/OATGraphViewer/OATGraphViewer.tsx
  src/Components/OATGraphViewer/OATGraphViewer.types.ts
  src/Components/OATModelList/OATModelList.styles.tsx
  src/Components/OATPropertyEditor/Editor.tsx
  src/Components/OATPropertyEditor/Editor.types.ts
  src/Components/OATPropertyEditor/Internal/FormRootModelDetails.tsx
  src/Components/OATPropertyEditor/Internal/FormRootModelDetails.types.ts
  src/Components/OATPropertyEditor/Internal/PropertiesModelSummary.tsx
  src/Components/OATPropertyEditor/Internal/PropertiesModelSummary.types.ts
  src/Components/OATPropertyEditor/Internal/PropertyList.tsx
  src/Components/OATPropertyEditor/Internal/PropertyList.types.ts
  src/Components/OATPropertyEditor/OATPropertyEditor.stories.tsx
  src/Components/OATPropertyEditor/OATPropertyEditor.styles.ts
  src/Components/OATPropertyEditor/OATPropertyEditor.tsx
  src/Components/OATPropertyEditor/OATPropertyEditor.types.ts
  src/Models/Constants/OatStyleConstants.ts
  src/Models/Context/OatPageContext/OatPageContext.mock.ts
  src/Pages/OATEditorPage/Internal/Components/OATTextFieldId.tsx
  src/Pages/OATEditorPage/OATEditorPage.styles.tsx
  src/Pages/OATEditorPage/OATEditorPage.tsx
Labels: large change :ocean:

#763 [Data history]: Error handling
  src/Adapters/ADXAdapter.ts
  src/Adapters/MockAdapter.ts
  src/Cards/BaseCard/BaseCard.stories.tsx
  src/Cards/GeoSpatialCard/GeoSpatialCard.stories.tsx
  src/Cards/KeyValuePairCard/KeyValuePairCard.stories.tsx
  src/Components/ADT3DSceneBuilder/Internal/Shared/LeftPanel.styles.ts
  src/Components/BehaviorsModal/Internal/Widgets/DataHistoryWidget/DataHistoryWidget.stories.tsx
  src/Components/BehaviorsModal/Internal/Widgets/DataHistoryWidget/DataHistoryWidget.styles.ts
  src/Components/BehaviorsModal/Internal/Widgets/DataHistoryWidget/DataHistoryWidget.tsx
  src/Components/BehaviorsModal/Internal/Widgets/DataHistoryWidget/DataHistoryWidget.types.ts
  src/Components/BehaviorsModal/Internal/Widgets/DataHistoryWidget/Internal/DataHistoryWidgetErrorHandling.tsx
  src/Components/HighChartsWrapper/HighChartsWrapper.tsx
  src/Components/IllustrationMessage/IllustrationMessage.tsx
  src/Components/QuickTimesDropdown/QuickTimesDropdown.tsx
  src/Components/QuickTimesDropdown/QuickTimesDropdown.types.ts
  src/Models/Constants/Constants.ts
  src/Models/Constants/Enums.ts
  src/Models/Constants/Interfaces.ts
  src/Models/Hooks/useTimeSeriesData.ts
  src/Resources/Locales/cs.json
  src/Resources/Locales/de.json
  src/Resources/Locales/en.json
  src/Resources/Locales/es.json
  src/Resources/Locales/fr.json
  src/Resources/Locales/hu.json
  src/Resources/Locales/it.json
  src/Resources/Locales/ja.json
  src/Resources/Locales/ko.json
  src/Resources/Locales/nl.json
  src/Resources/Locales/pl.json
  src/Resources/Locales/pt-pt.json
  src/Resources/Locales/pt.json
  src/Resources/Locales/ru.json
  src/Resources/Locales/sv.json
  src/Resources/Locales/tr.json
  src/Resources/Locales/zh-Hans.json
  src/Resources/Static/connectionError.svg
Labels: enhancement :bulb:, small change :droplet:

#769 Format mock data
  src/Adapters/__mockData__/3DScenesConfiguration.json
Labels: small change :droplet:

#752 Runtime V2 to check for visual rules instead of badges/alerts
  schemas/3DScenesConfiguration/v1.0.0/3DScenesConfiguration.schema.json
  src/Components/ADT3DSceneBuilder/Internal/VisualRuleForm/Internal/ConditionsCallout/ActionItem.tsx
  src/Components/ADT3DSceneBuilder/Internal/VisualRuleForm/Internal/ConditionsCallout/ConditionCalloutUtility.ts
  src/Components/ADT3DSceneBuilder/Internal/VisualRuleForm/Internal/ConditionsCallout/ConditionsCallout.types.ts
  src/Components/ADT3DSceneBuilder/Internal/VisualRuleForm/Internal/ConditionsList.tsx
  src/Models/Classes/SceneView.types.ts
  src/Models/Classes/ViewerConfigUtility.ts
  src/Models/Hooks/useRuntimeSceneData.ts
  src/Models/Services/Utils.ts
  src/Models/Types/Generated/3DScenesConfiguration-v1.0.0.d.ts
Labels: small change :droplet:, refactor :hammer:

#771 Added string to list of allowed property schemas in timeseries builder
  schemas/3DScenesConfiguration/v1.0.0/3DScenesConfiguration.schema.json
  src/Adapters/__mockData__/3DScenesConfiguration.json
  src/Adapters/__mockData__/DemoEnvsConfig.json
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/Widgets/WidgetBuilders/DataHistoryWidgetBuilder/Internal/TimeSeriesFormCallout.tsx
  src/Models/Hooks/useTimeSeriesData.ts
  src/Models/Types/Generated/3DScenesConfiguration-v1.0.0.d.ts
  src/Resources/Locales/cs.json
  src/Resources/Locales/de.json
  src/Resources/Locales/en.json
  src/Resources/Locales/es.json
  src/Resources/Locales/fr.json
  src/Resources/Locales/hu.json
  src/Resources/Locales/it.json
  src/Resources/Locales/ja.json
  src/Resources/Locales/ko.json
  src/Resources/Locales/nl.json
  src/Resources/Locales/pl.json
  src/Resources/Locales/pt-pt.json
  src/Resources/Locales/pt.json
  src/Resources/Locales/ru.json
  src/Resources/Locales/sv.json
  src/Resources/Locales/tr.json
  src/Resources/Locales/zh-Hans.json
Labels: enhancement :bulb:

#776 [Data history widget]: Mock data fix for now required field of propertyType
  src/Adapters/__mockData__/DemoEnvsConfig.json
  src/Adapters/__mockData__/TruckAndMachinesConfig.json
  src/Components/BehaviorsModal/__mockData__/BehaviorsModalMockData.json
Labels: bugfix :bug: :white_check_mark:

#777 Resolve Conditions on save schema issue
  src/Models/Classes/3DVConfig.ts
Labels: bugfix :bug: :white_check_mark:, small change :droplet:

#775 [Azure Resource Graph]: Changes in AzureManamentAdapter and EnvironmentPicker
  src/Adapters/ADT3DSceneAdapter.ts
  src/Adapters/ADTAdapter.ts
  src/Adapters/AzureManagementAdapter.ts
  src/Adapters/BlobAdapter.ts
  src/Adapters/MockAdapter.ts
  src/Adapters/__mockData__/MockAdapterData/MockResourceGraphDataForADTInstances.json
  src/Adapters/__mockData__/MockAdapterData/MockSubscriptionData.json
  src/Components/BlobDropdown/BlobDropdown.tsx
  src/Components/EnvironmentPicker/EnvironmentPicker.mock.ts
  src/Components/EnvironmentPicker/EnvironmentPicker.tsx
  src/Components/EnvironmentPicker/EnvironmentPickerManager.ts
  src/Components/ResourcePicker/ResourcePicker.stories.local.tsx
  src/Components/ResourcePicker/ResourcePicker.tsx
  src/Components/ResourcePicker/ResourcePicker.types.ts
  src/Models/Classes/AdapterDataClasses/AzureManagementData.ts
  src/Models/Constants/Constants.ts
  src/Models/Constants/Enums.ts
  src/Models/Constants/Interfaces.ts
  src/Models/Constants/Types.ts
  src/Models/Context/DeeplinkContext/DeeplinkContext.tsx
  src/Models/Services/LocalStorageManager/LocalStorageManager.ts
  src/Models/Services/Utils.ts
  src/Models/Services/__tests__/Utils.test.ts
  src/Pages/ADT3DScenePage/ADT3DScenePage.tsx
  src/Pages/ADTTwinsPage/ADTTwinsPage.tsx
  src/Resources/Locales/cs.json
  src/Resources/Locales/de.json
  src/Resources/Locales/en.json
  src/Resources/Locales/es.json
  src/Resources/Locales/fr.json
  src/Resources/Locales/hu.json
  src/Resources/Locales/it.json
  src/Resources/Locales/ja.json
  src/Resources/Locales/ko.json
  src/Resources/Locales/nl.json
  src/Resources/Locales/pl.json
  src/Resources/Locales/pt-pt.json
  src/Resources/Locales/pt.json
  src/Resources/Locales/ru.json
  src/Resources/Locales/sv.json
  src/Resources/Locales/tr.json
  src/Resources/Locales/zh-Hans.json
Labels: large change :ocean:, refactor :hammer:

#774 Create flighted Visual rule viewer experience
  src/Components/ADT3DSceneBuilder/Internal/VisualRuleForm/Internal/ConditionsCallout/ActionItem.tsx
  src/Components/ADT3DSceneBuilder/Internal/VisualRuleForm/Internal/ConditionsCallout/ConditionSummary.styles.ts
  src/Components/ADT3DSceneBuilder/Internal/VisualRuleForm/Internal/ConditionsCallout/ConditionSummary.tsx
  src/Components/ADT3DSceneBuilder/Internal/VisualRuleForm/Internal/ConditionsCallout/ConditionSummary.types.ts
  src/Components/ADT3DSceneBuilder/Internal/VisualRuleForm/Internal/ConditionsCallout/ConditionsCallout.tsx
  src/Components/ADT3DSceneBuilder/Internal/VisualRuleForm/Internal/ConditionsList.tsx
  src/Components/ADT3DSceneBuilder/Internal/VisualRuleForm/Internal/ConditionsList.types.ts
  src/Components/ADT3DSceneBuilder/Internal/VisualRuleForm/VisualRuleFormUtility.ts
  src/Components/AlertModal/AlertModal.tsx
  src/Components/BehaviorsModal/BehaviorsModal.tsx
  src/Components/BehaviorsModal/Internal/BehaviorSection/BadgeBlock.styles.ts
  src/Components/BehaviorsModal/Internal/BehaviorSection/BadgeBlock.tsx
  src/Components/BehaviorsModal/Internal/BehaviorSection/BadgeBlock.types.ts
  src/Components/BehaviorsModal/Internal/BehaviorSection/BehaviorSection.styles.ts
  src/Components/BehaviorsModal/Internal/BehaviorSection/BehaviorSection.types.ts
  src/Components/BehaviorsModal/Internal/BehaviorSection/BehaviorVisualRuleSection.tsx
  src/Components/ColorPills/ColorPills.stories.tsx
  src/Components/ColorPills/ColorPills.styles.ts
  src/Components/ColorPills/ColorPills.tsx
  src/Components/ColorPills/ColorPills.types.ts
  src/Components/ColorPillsCalloutContent/ColorPillsCalloutContent.stories.tsx
  src/Components/ColorPillsCalloutContent/ColorPillsCalloutContent.styles.ts
  src/Components/ColorPillsCalloutContent/ColorPillsCalloutContent.tsx
  src/Components/ColorPillsCalloutContent/ColorPillsCalloutContent.types.ts
  src/Components/ElementsPanel/Internal/ElementColoring.styles.ts
  src/Components/ElementsPanel/Internal/ElementColoring.tsx
  src/Components/ElementsPanel/Internal/ElementColoring.types.ts
  src/Components/ElementsPanel/Internal/VisualRuleElementsList.tsx
  src/Components/ElementsPanel/ViewerElementsPanel.styles.ts
  src/Components/ElementsPanel/ViewerElementsPanel.tsx
  src/Components/ElementsPanel/ViewerElementsPanel.types.ts
  src/Components/StatusPills/StatusPills.styles.ts
  src/Models/Classes/ViewerConfigUtility.ts
  src/Models/Constants/VisualRuleTypes.ts
  src/Models/Hooks/useRuntimeSceneData.ts
  src/Models/Services/Utils.ts
  src/Models/SharedUtils/VisualRuleUtils.ts
  src/Resources/Locales/cs.json
  src/Resources/Locales/de.json
  src/Resources/Locales/en.json
  src/Resources/Locales/es.json
  src/Resources/Locales/fr.json
  src/Resources/Locales/hu.json
  src/Resources/Locales/it.json
  src/Resources/Locales/ja.json
  src/Resources/Locales/ko.json
  src/Resources/Locales/nl.json
  src/Resources/Locales/pl.json
  src/Resources/Locales/pt-pt.json
  src/Resources/Locales/pt.json
  src/Resources/Locales/ru.json
  src/Resources/Locales/sv.json
  src/Resources/Locales/tr.json
  src/Resources/Locales/zh-Hans.json
  src/Theming/Palettes.ts
  src/Theming/Theme.types.ts
Labels: refactor :hammer:

#782 OAT: Select untargeted relationship when node is clicked.
  src/Components/OATGraphViewer/OATGraphViewer.tsx
  src/Components/OATModelList/OATModelList.tsx
  src/Models/Context/OatPageContext/OatPageContextUtils.ts
  src/Models/Services/OatUtils.ts
  src/Pages/OATEditorPage/OATEditorPage.tsx
Labels: enhancement :bulb:, small change :droplet:

#786 Fix several Contains functions in advanced search
  src/Components/AdvancedSearch/Internal/QueryBuilder/QueryBuilderUtils.ts
Labels: bugfix :bug: :white_check_mark:, small change :droplet:

#785 Added dtid as an advanced search property
  src/Components/ModelledPropertyBuilder/ModelledPropertyBuilder.model.ts
  src/Components/TwinPropertySearchDropdown/TwinPropertySearchDropdown.styles.ts
  src/Components/TwinPropertySearchDropdown/TwinPropertySearchDropdown.tsx
  src/Components/TwinPropertySearchDropdown/TwinPropertySearchDropdown.types.ts
  src/Models/Constants/Constants.ts
  src/Models/Hooks/useFlattenedModelProperties.ts
Labels: small change :droplet:

#781 Removing flight and alert/status naming
  src/Adapters/BlobAdapter.ts
  src/Adapters/BlobAdapterUtility.ts
  src/Adapters/__mockData__/3DScenesConfiguration.json
  src/Adapters/__mockData__/DemoEnvsConfig.json
  src/Components/ADT3DSceneBuilder/ADT3DSceneBuilder.BehaviorForm.stories.tsx
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/BehaviorForm.types.ts
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/BehaviorsForm.tsx
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/Internal/AlertsTab.tsx
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/Internal/StatusTab.tsx
  src/Components/ADT3DSceneBuilder/Internal/VisualRuleForm/Internal/ConditionsList.tsx
  src/Components/ADT3DSceneBuilder/Internal/VisualRuleForm/VisualRuleForm.tsx
  src/Components/ADT3DViewer/ADT3DViewer.tsx
  src/Components/AlertModal/AlertModal.tsx
  src/Components/BehaviorsModal/BehaviorsModal.tsx
  src/Components/BehaviorsModal/Internal/BehaviorSection/BehaviorSection.tsx
  src/Components/BehaviorsModal/Internal/BehaviorSection/BehaviorVisualRuleSection.tsx
  src/Components/ElementsPanel/Internal/ElementsList.tsx
  src/Components/ElementsPanel/Internal/VisualRuleElementsList.tsx
  src/Components/ElementsPanel/ViewerElementsPanel.Utils.ts
  src/Components/ElementsPanel/ViewerElementsPanel.styles.ts
  src/Components/ElementsPanel/ViewerElementsPanel.tsx
  src/Components/ElementsPanel/ViewerElementsPanel.types.ts
  src/Components/StatusPills/StatusPills.stories.tsx
  src/Components/StatusPills/StatusPills.styles.ts
  src/Components/StatusPills/StatusPills.tsx
  src/Components/StatusPills/StatusPills.types.ts
  src/Components/VisualsModal/VisualsModal.stories.tsx
  src/Components/VisualsModal/VisualsModal.styles.ts
  src/Components/VisualsModal/VisualsModal.tsx
  src/Models/Classes/3DVConfig.ts
  src/Models/Classes/ViewerConfigUtility.ts
  src/Models/Constants/Constants.ts
  src/Models/Context/BehaviorFormContext/BehaviorFormContext.mock.ts
  src/Models/Context/BehaviorFormContext/BehaviorFormContext.test.tsx
  src/Models/Context/BehaviorFormContext/BehaviorFormContext.tsx
  src/Models/Context/BehaviorFormContext/BehaviorFormContext.types.ts
  src/Models/Hooks/useRuntimeSceneData.ts
  src/Resources/Locales/cs.json
  src/Resources/Locales/de.json
  src/Resources/Locales/en.json
  src/Resources/Locales/es.json
  src/Resources/Locales/fr.json
  src/Resources/Locales/hu.json
  src/Resources/Locales/it.json
  src/Resources/Locales/ja.json
  src/Resources/Locales/ko.json
  src/Resources/Locales/nl.json
  src/Resources/Locales/pl.json
  src/Resources/Locales/pt-pt.json
  src/Resources/Locales/pt.json
  src/Resources/Locales/ru.json
  src/Resources/Locales/sv.json
  src/Resources/Locales/tr.json
  src/Resources/Locales/zh-Hans.json
Labels: large change :ocean:, refactor :hammer:
