Repository microsoft/iot-cardboard-js, pull requests merged in 2022-05, with the labels that each got.

#479 Fixed typo in example component import in the "Getting Started" section
  README.md
Labels: documentation

#482 Value widget: support for 0 & unset twin values
  src/Components/BehaviorsModal/Internal/Widgets/ValueWidget/FormattedValue.tsx
  src/Components/BehaviorsModal/Internal/Widgets/ValueWidget/ValueWidget.styles.ts
  src/Components/BehaviorsModal/Internal/Widgets/ValueWidget/ValueWidget.tsx
Labels: bugfix :bug: :white_check_mark:

#473 Zarmada/working/ADTS-144
  src/Components/OATGraphViewer/Internal/OATGraphCustomNode.tsx
  src/Components/OATGraphViewer/OATGraphViewer.tsx
Labels: zarmada internal PR

#474 Update to layers dropdown behavior and update resource strings & sort behaviors
  src/Components/ADT3DSceneBuilder/ADT3DSceneBuilder.BehaviorForm.stories.tsx
  src/Components/ADT3DSceneBuilder/ADT3DSceneBuilder.BehaviorList.stories.tsx
  src/Components/ADT3DSceneBuilder/ADT3DSceneBuilder.WidgetsList.stories.tsx
  src/Components/ADT3DSceneBuilder/ADT3DSceneBuilder.types.ts
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/Behaviors.tsx
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/BehaviorsForm.tsx
  src/Components/ADT3DViewer/ADT3DViewer.tsx
  src/Components/LayerDropdown/LayerDropdown.styles.ts
  src/Components/LayerDropdown/LayerDropdown.tsx
  src/Components/LayerDropdown/LayerDropdown.types.ts
  src/Models/Classes/ViewerConfigUtility.ts
  src/Models/Services/Utils.ts
  src/Resources/Locales/cs.json
  src/Resources/Locales/de.json
  src/Resources/Locales/en.json
  src/Resources/Locales/es.json
  src/Resources/Locales/fr.json
  src/Resources/Locales/hu.json
  src/Resources/Locales/it.json
  src/Resources/Locales/ja.json
  src/Resources/Locales/ko.json
  src/Resources/Locales/nl.json
  src/Resources/Locales/pl.json
  src/Resources/Locales/pt-pt.json
  src/Resources/Locales/pt.json
  src/Resources/Locales/ru.json
  src/Resources/Locales/sv.json
  src/Resources/Locales/tr.json
  src/Resources/Locales/zh-Hans.json
Labels: small change :droplet:

#440 Zarmada/working/adts 96b
  package-lock.json
  package.json
  src/Components/OATGraphViewer/OATGraphViewer.tsx
  src/Components/OATModelList/OATModelList.styles.tsx
  src/Components/OATModelList/OATModelList.tsx
  src/Components/OATPropertyEditor/JSONEditor.tsx
  src/Components/OATPropertyEditor/PropertySelector.tsx
  src/Models/Constants/Interfaces.ts
  src/Models/Services/Utils.ts
Labels: zarmada internal PR

#487 Zarmada/working/ADTS-135
  src/Components/OATGraphViewer/OATGraphViewer.styles.tsx
  src/Components/OATPropertyEditor/OATPropertyEditor.styles.ts
  src/Pages/OATEditorPage/OATEditorPage.Styles.tsx
Labels: zarmada internal PR

#489 Added No container and No ADT error cases to Scene page
  src/Components/EnvironmentPicker/EnvironmentPicker.tsx
  src/Components/EnvironmentPicker/EnvironmentPicker.types.ts
  src/Components/ScenePageErrorHandlingWrapper/ScenePageErrorHandlingWrapper.tsx
  src/Models/Constants/Enums.ts
  src/Pages/ADT3DScenePage/ADT3DScenePage.tsx
  src/Resources/Locales/cs.json
  src/Resources/Locales/de.json
  src/Resources/Locales/en.json
  src/Resources/Locales/es.json
  src/Resources/Locales/fr.json
  src/Resources/Locales/hu.json
  src/Resources/Locales/it.json
  src/Resources/Locales/ja.json
  src/Resources/Locales/ko.json
  src/Resources/Locales/nl.json
  src/Resources/Locales/pl.json
  src/Resources/Locales/pt-pt.json
  src/Resources/Locales/pt.json
  src/Resources/Locales/ru.json
  src/Resources/Locales/sv.json
  src/Resources/Locales/tr.json
  src/Resources/Locales/zh-Hans.json
Labels: enhancement :bulb:

#490 ADTS-113
  src/Components/OATGraphViewer/OATGraphViewer.tsx
  src/Components/OATHeader/OATHeader.tsx
  src/Pages/OATEditorPage/Internal/OATImport.tsx
  src/Pages/OATEditorPage/OATEditorPage.tsx
Labels: zarmada internal PR

#485 Zarmada/working/ADTS-133-B
  src/Models/Constants/ActionTypes.ts
  src/Pages/OATEditorPage/Internal/OATErrorHandlingWrapper.tsx
  src/Pages/OATEditorPage/OATEditorPage.Styles.tsx
  src/Pages/OATEditorPage/OATEditorPage.state.ts
  src/Pages/OATEditorPage/OATEditorPage.tsx
  src/Pages/OATEditorPage/OATEditorPage.types.ts
  src/Resources/Locales/cs.json
  src/Resources/Locales/de.json
  src/Resources/Locales/en.json
  src/Resources/Locales/es.json
  src/Resources/Locales/fr.json
  src/Resources/Locales/hu.json
  src/Resources/Locales/it.json
  src/Resources/Locales/ja.json
  src/Resources/Locales/ko.json
  src/Resources/Locales/nl.json
  src/Resources/Locales/pl.json
  src/Resources/Locales/pt-pt.json
  src/Resources/Locales/pt.json
  src/Resources/Locales/ru.json
  src/Resources/Locales/sv.json
  src/Resources/Locales/tr.json
  src/Resources/Locales/zh-Hans.json
Labels: zarmada internal PR

#497 Zarmada/working/adts 143
  src/Components/OATGraphViewer/OATGraphViewer.styles.tsx
  src/Components/OATGraphViewer/OATGraphViewer.tsx
Labels: zarmada internal PR

#461 Zarmada/working/ADTS-145
  src/Components/OATGraphViewer/OATGraphViewer.tsx
  src/Components/OATHeader/OATHeader.styles.ts
  src/Components/OATHeader/OATHeader.tsx
  src/Components/OATHeader/internal/Enums/index.tsx
  src/Components/OATHeader/internal/FileSubMenu.tsx
  src/Components/OATHeader/internal/FormOpen.tsx
  src/Components/OATHeader/internal/FormSaveAs.tsx
  src/Components/OATHeader/internal/Modal.tsx
  src/Components/OATHeader/internal/ModalDelete.tsx
  src/Components/OATHeader/internal/ModalSaveCurrentProjectAndClear.tsx
  src/Components/OATHeader/internal/Utils.ts
  src/Components/OATPropertyEditor/Editor.tsx
  src/Components/OATPropertyEditor/FormRootModelDetails.tsx
  src/Components/OATPropertyEditor/PropertiesModelSummary.tsx
  src/Models/Constants/ActionTypes.ts
  src/Models/Constants/Constants.ts
  src/Pages/OATEditorPage/Internal/Classes/index.ts
  src/Pages/OATEditorPage/Internal/Types/index.ts
  src/Pages/OATEditorPage/OATEditorPage.state.ts
  src/Pages/OATEditorPage/OATEditorPage.tsx
  src/Pages/OATEditorPage/OATEditorPage.types.ts
  src/Resources/Locales/cs.json
  src/Resources/Locales/de.json
  src/Resources/Locales/en.json
  src/Resources/Locales/es.json
  src/Resources/Locales/fr.json
  src/Resources/Locales/hu.json
  src/Resources/Locales/it.json
  src/Resources/Locales/ja.json
  src/Resources/Locales/ko.json
  src/Resources/Locales/nl.json
  src/Resources/Locales/pl.json
  src/Resources/Locales/pt-pt.json
  src/Resources/Locales/pt.json
  src/Resources/Locales/ru.json
  src/Resources/Locales/sv.json
  src/Resources/Locales/tr.json
  src/Resources/Locales/zh-Hans.json
Labels: zarmada internal PR
