Repository microsoft/iot-cardboard-js, pull requests merged in 2022-12, with the labels that each got.

#784 [React-select for ResourcePicker]: Component refactors
  package-lock.json
  package.json
  src/Adapters/AzureManagementAdapter.ts
  src/Components/EnvironmentPicker/EnvironmentPicker.state.ts
  src/Components/EnvironmentPicker/EnvironmentPicker.test.tsx
  src/Components/EnvironmentPicker/EnvironmentPicker.tsx
  src/Components/ResourcePicker/ResourcePicker.stories.local.tsx
  src/Components/ResourcePicker/ResourcePicker.styles.ts
  src/Components/ResourcePicker/ResourcePicker.tsx
  src/Components/ResourcePicker/ResourcePicker.types.ts
  src/Models/Constants/Types.ts
  src/Models/Services/Utils.ts
  src/Resources/Locales/cs.json
  src/Resources/Locales/de.json
  src/Resources/Locales/en.json
  src/Resources/Locales/es.json
  src/Resources/Locales/fr.json
  src/Resources/Locales/hu.json
  src/Resources/Locales/it.json
  src/Resources/Locales/ja.json
  src/Resources/Locales/ko.json
  src/Resources/Locales/nl.json
  src/Resources/Locales/pl.json
  src/Resources/Locales/pt-pt.json
  src/Resources/Locales/pt.json
  src/Resources/Locales/ru.json
  src/Resources/Locales/sv.json
  src/Resources/Locales/tr.json
  src/Resources/Locales/zh-Hans.json
  src/Resources/Styles/ReactSelect.styles.ts
Labels: refactor :hammer:

#789 Create twin search component and use where needed
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/Twins/BehaviorTwinAliasForm.tsx
  src/Components/ADT3DSceneBuilder/Internal/Elements/ElementForm.tsx
  src/Components/ADT3DSceneBuilder/Internal/Elements/Internal/ElementTwinAliasForm.tsx
  src/Components/TwinSearch/TwinSearch.stories.tsx
  src/Components/TwinSearch/TwinSearch.styles.ts
  src/Components/TwinSearch/TwinSearch.tsx
  src/Components/TwinSearch/TwinSearch.types.ts
Labels: enhancement :bulb:, small change :droplet:

#791 [Environment Picker] Fixed error message disappearing and made filter case insensitive
  src/Components/EnvironmentPicker/EnvironmentPicker.tsx
  src/Components/ResourcePicker/ResourcePicker.tsx
Labels: bugfix :bug: :white_check_mark:

#793 Fix bugs in Visual rules
  src/Components/ADT3DSceneBuilder/Internal/VisualRuleForm/Internal/ConditionsCallout/ConditionsCallout.tsx
  src/Components/ADT3DSceneBuilder/Internal/VisualRuleForm/Internal/ConditionsCallout/ConditionsCallout.types.ts
  src/Components/ADT3DSceneBuilder/Internal/VisualRuleForm/VisualRuleForm.tsx
Labels: bugfix :bug: :white_check_mark:, small change :droplet:

#794 [EnvironmentPicker]: Fixed error message for catastrophic ARM calls and enabled save button
  src/Adapters/AzureManagementAdapter.ts
  src/Components/EnvironmentPicker/EnvironmentPicker.tsx
  src/Components/ResourcePicker/ResourcePicker.stories.tsx
  src/Components/ResourcePicker/ResourcePicker.styles.ts
  src/Components/ResourcePicker/ResourcePicker.tsx
  src/Components/ResourcePicker/ResourcePicker.types.ts
  src/Resources/Locales/cs.json
  src/Resources/Locales/de.json
  src/Resources/Locales/en.json
  src/Resources/Locales/es.json
  src/Resources/Locales/fr.json
  src/Resources/Locales/hu.json
  src/Resources/Locales/it.json
  src/Resources/Locales/ja.json
  src/Resources/Locales/ko.json
  src/Resources/Locales/nl.json
  src/Resources/Locales/pl.json
  src/Resources/Locales/pt-pt.json
  src/Resources/Locales/pt.json
  src/Resources/Locales/ru.json
  src/Resources/Locales/sv.json
  src/Resources/Locales/tr.json
  src/Resources/Locales/zh-Hans.json
Labels: bugfix :bug: :white_check_mark:

#773 Array support
  .storybook/test_data/mockModel.json
  src/Components/PropertyInspector/PropertyInspector.stories.local.tsx
  src/Components/PropertyInspector/PropertyInspector.stories.tsx
  src/Components/PropertyInspector/PropertyInspectoryModel.ts
  src/Components/PropertyInspector/PropertyTree/PropertyTree.tsx
  src/Components/PropertyInspector/PropertyTree/PropertyTree.types.ts
  src/Components/PropertyInspector/PropertyTree/TreeComponents/TreeNode.tsx
  src/Components/PropertyInspector/PropertyTree/TreeComponents/TreeNodeArrayItemTool.tsx
  src/Components/PropertyInspector/PropertyTree/TreeComponents/TreeNodeDateTimeValue.tsx
  src/Components/PropertyInspector/PropertyTree/TreeComponents/TreeNodeIcon.tsx
  src/Components/PropertyInspector/PropertyTree/TreeComponents/TreeNodeMapTool.tsx
  src/Components/PropertyInspector/PropertyTree/TreeComponents/TreeNodeSetUnset.tsx
  src/Components/PropertyInspector/PropertyTree/TreeComponents/TreeNodeValue.tsx
  src/Components/PropertyInspector/StandalonePropertyInspector.state.ts
  src/Components/PropertyInspector/StandalonePropertyInspector.tsx
  src/Components/PropertyInspector/__mockdata__/mockData.ts
  src/Components/PropertyInspector/__tests__/PropertyInspectorModel.test.ts
  src/Components/PropertyInspector/__tests__/testModel.json
  src/Models/Constants/dtdlInterfaces.ts
  src/Resources/Locales/cs.json
  src/Resources/Locales/de.json
  src/Resources/Locales/en.json
  src/Resources/Locales/es.json
  src/Resources/Locales/fr.json
  src/Resources/Locales/hu.json
  src/Resources/Locales/it.json
  src/Resources/Locales/ja.json
  src/Resources/Locales/ko.json
  src/Resources/Locales/nl.json
  src/Resources/Locales/pl.json
  src/Resources/Locales/pt-pt.json
  src/Resources/Locales/pt.json
  src/Resources/Locales/ru.json
  src/Resources/Locales/sv.json
  src/Resources/Locales/tr.json
  src/Resources/Locales/zh-Hans.json
Labels: enhancement :bulb:, large change :ocean:

#796 [Environment Picker]: Null check for container url and removed tenant ID from ARG query
  src/Adapters/AzureManagementAdapter.ts
  src/Components/EnvironmentPicker/EnvironmentPicker.tsx
Labels: bugfix :bug: :white_check_mark:

#799 Gauge widget should be configurable to show decimals
  src/Adapters/__mockData__/MockGaugeData.json
  src/Components/BehaviorsModal/Internal/Widgets/GaugeWidget/GaugeWidget.stories.tsx
  src/Components/BehaviorsModal/Internal/Widgets/GaugeWidget/GaugeWidget.tsx
  src/Models/Services/Utils.ts
Labels: enhancement :bulb:

#802 Ocean theme seems resolved. Dark has a regression
  src/Theming/Palettes.ts
Labels: small change :droplet:, styling :art:

#804 Add console.warn for missing user keys
  .storybook/useAuthParams.js
Labels: bugfix :bug: :white_check_mark:, small change :droplet:
