Repository microsoft/iot-cardboard-js, pull requests merged in 2022-06, with the labels that each got.

#501 Zarmada/working/adts 148
  src/Components/OATGraphViewer/Internal/OATGraphCustomEdge.tsx
  src/Components/OATGraphViewer/Internal/OATGraphCustomNode.tsx
  src/Components/OATGraphViewer/OATGraphViewer.tsx
  src/Components/OATHeader/OATHeader.tsx
  src/Components/OATModelList/OATModelList.styles.tsx
  src/Components/OATModelList/OATModelList.tsx
  src/Components/OATPropertyEditor/Editor.tsx
  src/Components/OATPropertyEditor/JSONEditor.tsx
  src/Components/OATPropertyEditor/OATPropertyEditor.styles.ts
  src/Models/Constants/ActionTypes.ts
  src/Models/Services/Utils.ts
  src/Pages/OATEditorPage/OATEditorPage.state.ts
  src/Pages/OATEditorPage/OATEditorPage.tsx
  src/Pages/OATEditorPage/OATEditorPage.types.ts
Labels: zarmada internal PR

#499 Close modal on scene change
  src/Components/ADT3DViewer/ADT3DViewer.tsx
  src/Components/SceneBreadcrumb/BaseBreadcrumb.tsx
  src/Components/SceneBreadcrumb/Internal/SceneDropdown.tsx
  src/Components/SceneBreadcrumb/Internal/SceneDropdown.types.tsx
  src/Components/SceneBreadcrumb/SceneBreadcrumb.types.ts
  src/Components/SceneBreadcrumb/SceneBreadcrumbFactory.tsx
Labels: bugfix :bug: :white_check_mark:

#502 Zarmada/working/ADTS-154
  src/Components/OATGraphViewer/OATGraphViewer.state.ts
  src/Components/OATGraphViewer/OATGraphViewer.tsx
  src/Components/OATHeader/OATHeader.tsx
  src/Components/OATHeader/internal/FileSubMenu.tsx
  src/Components/OATHeader/internal/FormOpen.tsx
  src/Components/OATHeader/internal/FormSaveAs.tsx
  src/Components/OATHeader/internal/Modal.tsx
  src/Components/OATHeader/internal/ModalDelete.tsx
  src/Components/OATHeader/internal/ModalSaveCurrentProjectAndClear.tsx
  src/Components/OATModelList/OATModelList.state.ts
  src/Components/OATPropertyEditor/OATPropertyEditor.tsx
  src/Models/Constants/ActionTypes.ts
  src/Models/Constants/Interfaces.ts
  src/Models/Services/Utils.ts
  src/Pages/OATEditorPage/Internal/Classes/index.ts
  src/Pages/OATEditorPage/OATEditorPage.state.ts
  src/Pages/OATEditorPage/OATEditorPage.tsx
  src/Pages/OATEditorPage/OATEditorPage.types.ts
  src/Resources/Locales/en.json
Labels: zarmada internal PR

#503 Zarmada/working/adts 155
  package-lock.json
  package.json
  src/Components/OATGraphViewer/Internal/OATGraphCustomEdge.tsx
  src/Components/OATGraphViewer/OATGraphViewer.tsx
  src/Components/OATModelList/OATModelList.styles.tsx
  src/Components/OATModelList/OATModelList.tsx
  src/Components/OATPropertyEditor/OATPropertyEditor.styles.ts
  src/Components/OATPropertyEditor/PropertyList.tsx
  src/Pages/OATEditorPage/OATEditorPage.Styles.tsx
Labels: zarmada internal PR

#507 Fix: Aliased Twin properties
  src/Adapters/ADTAdapter.ts
  src/Components/ModelledPropertyBuilder/ModelledPropertyBuilder.model.ts
  src/Components/ModelledPropertyBuilder/ModelledPropertyBuilder.types.ts
  src/Models/Classes/ViewerConfigUtility.ts
Labels: bugfix :bug: :white_check_mark:

#516 Zarmada/working/ADTS-166
  src/Components/OATGraphViewer/Internal/OATGraphCustomEdge.tsx
  src/Components/OATGraphViewer/Internal/OATGraphCustomNode.tsx
  src/Components/OATGraphViewer/OATGraphViewer.tsx
  src/Models/Constants/Interfaces.ts
  src/Pages/OATEditorPage/Internal/Classes/index.ts
  src/Pages/OATEditorPage/OATEditorPage.tsx
Labels: zarmada internal PR

#504 Coryboyle/environment map cleanup
  src/Components/3DV/SceneView.tsx
  src/Components/3DV/Shaders.ts
  src/Models/Constants/Constants.ts
Labels: small change :droplet:

#511 Show elements without behaviors in the elements panel
  jest.setup.ts
  src/Adapters/ADTAdapter.ts
  src/Components/ADT3DSceneBuilder/ADT3DSceneBuilder.tsx
  src/Components/ADT3DSceneBuilder/Internal/Elements/Internal/BehaviorsTab.tsx
  src/Components/ADT3DViewer/ADT3DViewer.tsx
  src/Components/BehaviorsModal/BehaviorsModal.stories.tsx
  src/Components/BehaviorsModal/BehaviorsModal.tsx
  src/Components/ModelledPropertyBuilder/ModelledPropertyBuilder.stories.tsx
  src/Models/Classes/ViewerConfigUtility.ts
  src/Models/Classes/__tests__/ViewerConfigUtility.test.ts
  src/Models/Classes/__tests__/ViewerConfigUtilityTestHelpers.ts
  src/Models/Classes/__tests__/__snapshots__/ViewerConfigUtility.test.ts.snap
  src/Models/Hooks/useRuntimeSceneData.ts
  src/i18n.ts
Labels: bugfix :bug: :white_check_mark:, small change :droplet:

#520 coryboyle/handleinstancedmeshes
  src/Components/3DV/SceneView.tsx
Labels: bugfix :bug: :white_check_mark:

#527 Bug fix: Fix deeplinks not respecting layers
  src/Components/ADT3DViewer/ADT3DViewer.tsx
Labels: bugfix :bug: :white_check_mark:, small change :droplet:

#519 Export generated 3D Scenes Studio schema types
  rollup.config.js
Labels: enhancement :bulb:

#532 Zarmada/working/ADTS-164
  src/Components/OATPropertyEditor/FormAddEnumItem.tsx
  src/Components/OATPropertyEditor/FormRootModelDetails.tsx
  src/Components/OATPropertyEditor/FormUpdateProperty.tsx
Labels: zarmada internal PR

#523 ADTS-163 Changes
  src/Components/OATGraphViewer/Internal/OATGraphCustomEdge.tsx
  src/Components/OATGraphViewer/Internal/OATGraphCustomNode.tsx
  src/Components/OATGraphViewer/OATGraphViewer.styles.tsx
  src/Components/OATGraphViewer/OATGraphViewer.tsx
  src/Components/OATHeader/OATHeader.tsx
  src/Components/OATModelList/OATModelList.styles.tsx
  src/Components/OATModelList/OATModelList.tsx
  src/Components/OATPropertyEditor/FormUpdateProperty.tsx
  src/Components/OATPropertyEditor/OATPropertyEditor.styles.ts
  src/Components/OATPropertyEditor/PropertiesModelSummary.tsx
  src/Models/Constants/Enums.ts
  src/Models/Constants/Interfaces.ts
Labels: zarmada internal PR

#510 "clear status" button
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/Internal/StatusTab.tsx
  src/Components/ModelledPropertyBuilder/ModelledPropertyBuilder.stories.tsx
  src/Components/ModelledPropertyBuilder/ModelledPropertyBuilder.styles.ts
  src/Components/ModelledPropertyBuilder/ModelledPropertyBuilder.tsx
  src/Components/ModelledPropertyBuilder/ModelledPropertyBuilder.types.ts
  src/Resources/Locales/cs.json
  src/Resources/Locales/de.json
  src/Resources/Locales/en.json
  src/Resources/Locales/es.json
  src/Resources/Locales/fr.json
  src/Resources/Locales/hu.json
  src/Resources/Locales/it.json
  src/Resources/Locales/ja.json
  src/Resources/Locales/ko.json
  src/Resources/Locales/nl.json
  src/Resources/Locales/pl.json
  src/Resources/Locales/pt-pt.json
  src/Resources/Locales/pt.json
  src/Resources/Locales/ru.json
  src/Resources/Locales/sv.json
  src/Resources/Locales/tr.json
  src/Resources/Locales/zh-Hans.json
Labels: bugfix :bug: :white_check_mark:

#531 Zarmada/working/ADTS-162
  src/Components/OATPropertyEditor/FormUpdateProperty.tsx
  src/Components/OATPropertyEditor/PropertyList.tsx
  src/Components/OATPropertyEditor/PropertyListItem.tsx
  src/Components/OATPropertyEditor/PropertyListItemNest.tsx
  src/Components/OATPropertyEditor/PropertySelector.tsx
  src/Components/OATPropertyEditor/Utils.ts
Labels: zarmada internal PR

#543 Zarmada/working/ADTS-180
  src/Components/OATGraphViewer/OATGraphViewer.styles.tsx
  src/Components/OATGraphViewer/OATGraphViewer.tsx
Labels: zarmada internal PR

#539 Zarmada/working/ADTS-164
  src/Components/OATPropertyEditor/FormRootModelDetails.tsx
  src/Components/OATPropertyEditor/FormUpdateProperty.tsx
Labels: zarmada internal PR

#536 Zarmada/working/ADTS-160
  src/Components/OATGraphViewer/Internal/OATGraphCustomNode.tsx
  src/Components/OATPropertyEditor/FormAddEnumItem.tsx
  src/Components/OATPropertyEditor/FormRootModelDetails.tsx
  src/Components/OATPropertyEditor/FormUpdateProperty.tsx
  src/Components/OATPropertyEditor/PropertiesModelSummary.tsx
  src/Components/OATPropertyEditor/Utils.ts
  src/Models/Constants/Constants.ts
  src/Resources/Locales/cs.json
  src/Resources/Locales/de.json
  src/Resources/Locales/en.json
  src/Resources/Locales/es.json
  src/Resources/Locales/fr.json
  src/Resources/Locales/hu.json
  src/Resources/Locales/it.json
  src/Resources/Locales/ja.json
  src/Resources/Locales/ko.json
  src/Resources/Locales/nl.json
  src/Resources/Locales/pl.json
  src/Resources/Locales/pt-pt.json
  src/Resources/Locales/pt.json
  src/Resources/Locales/ru.json
  src/Resources/Locales/sv.json
  src/Resources/Locales/tr.json
  src/Resources/Locales/zh-Hans.json
Labels: zarmada internal PR

#545 ADTS-177
  src/Components/OATGraphViewer/OATGraphViewer.tsx
Labels: zarmada internal PR

#549 ADTS-188
  src/Components/OATGraphViewer/Internal/OATGraphCustomEdge.tsx
Labels: zarmada internal PR

#550 Zarmada/working/ADTS-186
  src/Components/OATPropertyEditor/Constants.ts
  src/Components/OATPropertyEditor/Modal.tsx
  src/Components/OATPropertyEditor/PropertiesModelSummary.tsx
  src/Components/OATPropertyEditor/PropertyListItem.tsx
  src/Components/OATPropertyEditor/PropertyListItemNest.tsx
Labels: zarmada internal PR

#542 Zarmada/working/adts 175
  src/Components/OATGraphViewer/OATGraphViewer.tsx
  src/Components/OATHeader/OATHeader.tsx
  src/Components/OATHeader/internal/Enums/index.tsx
  src/Components/OATHeader/internal/FileSubMenu.tsx
  src/Components/OATHeader/internal/FormOpen.tsx
  src/Components/OATHeader/internal/FormSaveAs.tsx
  src/Components/OATHeader/internal/FormSettings.tsx
  src/Components/OATHeader/internal/Modal.tsx
  src/Components/OATHeader/internal/ModalDelete.tsx
  src/Components/OATHeader/internal/ModalSaveCurrentProjectAndClear.tsx
  src/Models/Constants/ActionTypes.ts
  src/Models/Constants/Constants.ts
  src/Models/Services/Utils.ts
  src/Pages/OATEditorPage/Internal/Classes/index.ts
  src/Pages/OATEditorPage/OATEditorPage.state.ts
  src/Pages/OATEditorPage/OATEditorPage.tsx
  src/Pages/OATEditorPage/OATEditorPage.types.ts
  src/Resources/Locales/cs.json
  src/Resources/Locales/de.json
  src/Resources/Locales/en.json
  src/Resources/Locales/es.json
  src/Resources/Locales/fr.json
  src/Resources/Locales/hu.json
  src/Resources/Locales/it.json
  src/Resources/Locales/ja.json
  src/Resources/Locales/ko.json
  src/Resources/Locales/nl.json
  src/Resources/Locales/pl.json
  src/Resources/Locales/pt-pt.json
  src/Resources/Locales/pt.json
  src/Resources/Locales/ru.json
  src/Resources/Locales/sv.json
  src/Resources/Locales/tr.json
  src/Resources/Locales/zh-Hans.json
Labels: zarmada internal PR

#546 Zarmada/working/ADTS-160
  src/Components/OATGraphViewer/Internal/OATGraphCustomEdge.tsx
  src/Components/OATGraphViewer/Internal/OATGraphCustomNode.tsx
  src/Components/OATPropertyEditor/FormAddEnumItem.tsx
  src/Components/OATPropertyEditor/FormRootModelDetails.tsx
  src/Components/OATPropertyEditor/FormUpdateProperty.tsx
  src/Components/OATPropertyEditor/PropertiesModelSummary.tsx
  src/Components/OATPropertyEditor/Utils.ts
  src/Models/Constants/Constants.ts
  src/Resources/Locales/cs.json
  src/Resources/Locales/de.json
  src/Resources/Locales/en.json
  src/Resources/Locales/es.json
  src/Resources/Locales/fr.json
  src/Resources/Locales/hu.json
  src/Resources/Locales/it.json
  src/Resources/Locales/ja.json
  src/Resources/Locales/ko.json
  src/Resources/Locales/nl.json
  src/Resources/Locales/pl.json
  src/Resources/Locales/pt-pt.json
  src/Resources/Locales/pt.json
  src/Resources/Locales/ru.json
  src/Resources/Locales/sv.json
  src/Resources/Locales/tr.json
  src/Resources/Locales/zh-Hans.json
Labels: zarmada internal PR

#544 Auto fill new twin alias or behavior name with searched text in callout
  src/Components/ADT3DSceneBuilder/ADT3DSceneBuilder.types.ts
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/Internal/TwinsTab.tsx
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/Twins/BehaviorTwinAliasForm.tsx
  src/Components/ADT3DSceneBuilder/Internal/BuilderLeftPanel.tsx
  src/Components/ADT3DSceneBuilder/Internal/Elements/ElementForm.tsx
  src/Components/ADT3DSceneBuilder/Internal/Elements/Elements.tsx
  src/Components/ADT3DSceneBuilder/Internal/Elements/Internal/BehaviorsTab.tsx
  src/Components/CardboardListCallout/CardboardListCallout.tsx
  src/Components/CardboardListCallout/CardboardListCallout.types.ts
  src/Resources/Locales/cs.json
  src/Resources/Locales/de.json
  src/Resources/Locales/en.json
  src/Resources/Locales/es.json
  src/Resources/Locales/fr.json
  src/Resources/Locales/hu.json
  src/Resources/Locales/it.json
  src/Resources/Locales/ja.json
  src/Resources/Locales/ko.json
  src/Resources/Locales/nl.json
  src/Resources/Locales/pl.json
  src/Resources/Locales/pt-pt.json
  src/Resources/Locales/pt.json
  src/Resources/Locales/ru.json
  src/Resources/Locales/sv.json
  src/Resources/Locales/tr.json
  src/Resources/Locales/zh-Hans.json
Labels: small change :droplet:

#541 Left panel padding, borders & overflow consistency
  src/Components/ADT3DSceneBuilder/ADT3DSceneBuilder.scss
  src/Components/ADT3DSceneBuilder/ADT3DSceneBuilder.styles.ts
  src/Components/ADT3DSceneBuilder/ADT3DSceneBuilder.tsx
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/Behaviors.tsx
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/Internal/AlertsTab.tsx
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/Internal/StatusTab.tsx
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/Internal/TwinsTab.tsx
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/Internal/WidgetsTab.tsx
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/Twins/BehaviorTwinAliasForm.tsx
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/Widgets/WidgetForm/WidgetForm.styles.ts
  src/Components/ADT3DSceneBuilder/Internal/BuilderLeftPanel/BuilderLeftPanel.styles.ts
  src/Components/ADT3DSceneBuilder/Internal/BuilderLeftPanel/BuilderLeftPanel.tsx
  src/Components/ADT3DSceneBuilder/Internal/BuilderLeftPanel/BuilderLeftPanel.types.ts
  src/Components/ADT3DSceneBuilder/Internal/Elements/Elements.tsx
  src/Components/ADT3DSceneBuilder/Internal/Elements/Internal/AliasedTwinsTab.tsx
  src/Components/ADT3DSceneBuilder/Internal/Elements/Internal/BehaviorsTab.tsx
  src/Components/ADT3DSceneBuilder/Internal/Elements/Internal/ElementTwinAliasForm.tsx
  src/Components/ADT3DSceneBuilder/Internal/Elements/Internal/MeshTab.tsx
  src/Components/ADT3DSceneBuilder/Internal/LeftPanelBuilderHeader.styles.ts
  src/Components/ADT3DSceneBuilder/Internal/Shared/LeftPanel.styles.ts
  src/Components/ADT3DSceneBuilder/Internal/Shared/PanelFooter.styles.ts
  src/Components/ADT3DSceneBuilder/Internal/Shared/PanelForms.styles.ts
  src/Components/ADT3DSceneBuilder/Internal/Shared/SearchHeader.tsx
  src/Components/ADT3DViewer/ADT3DViewer.scss
  src/Components/BaseComponent/BaseComponent.tsx
  src/Components/BaseComponent/BaseComponent.types.ts
  src/Models/Constants/StyleConstants.ts
  src/Pages/ADT3DScenePage/ADT3DScenePage.styles.ts
  src/Pages/ADT3DScenePage/ADT3DScenePage.tsx
  src/Resources/Styles/BaseStyles.scss
  src/Resources/Styles/BaseStyles.ts
Labels: enhancement :bulb:, styling :art:

#551 ADTS-173
  src/Components/OATGraphViewer/OATGraphViewer.styles.tsx
  src/Components/OATHeader/OATHeader.styles.ts
  src/Components/OATModelList/OATModelList.styles.tsx
  src/Components/OATPropertyEditor/OATPropertyEditor.styles.ts
  src/Components/OATPropertyEditor/PropertyList.tsx
  src/Components/OATPropertyEditor/PropertyListMapItemNested.tsx
  src/Components/OATPropertyEditor/PropertySelector.tsx
  src/Components/OATPropertyEditor/TemplateColumn.tsx
  src/Components/OATPropertyEditor/TemplateList.tsx
  src/Resources/Locales/en.json
Labels: zarmada internal PR

#535 Zarmada/working/ADTS-172
  src/Components/OATGraphViewer/OATGraphViewer.tsx
Labels: zarmada internal PR

#554 ADTS-183: manually calculate the source and target for edges
  src/Components/OATGraphViewer/Internal/OATGraphCustomEdge.tsx
  src/Components/OATGraphViewer/Internal/OATGraphCustomNode.tsx
  src/Components/OATGraphViewer/OATGraphViewer.styles.tsx
  src/Components/OATGraphViewer/OATGraphViewer.tsx
Labels: zarmada internal PR

#560 Zarmada/working/adts 182
  src/Components/OATGraphViewer/Internal/OATGraphCustomEdge.tsx
  src/Components/OATGraphViewer/Internal/OATGraphCustomNode.tsx
  src/Components/OATGraphViewer/OATGraphViewer.styles.tsx
  src/Components/OATModelList/OATModelList.styles.tsx
  src/Components/OATModelList/OATModelList.tsx
Labels: zarmada internal PR

#553 Zarmada/working/adts 189
  src/Components/OATGraphViewer/Internal/OATGraphCustomEdge.tsx
  src/Components/OATGraphViewer/OATGraphViewer.tsx
Labels: zarmada internal PR

#557 Zarmada/working/ADTS-185
  src/Components/OATGraphViewer/OATGraphViewer.styles.tsx
  src/Components/OATGraphViewer/OATGraphViewer.tsx
  src/Components/OATHeader/OATHeader.tsx
  src/Components/OATHeader/internal/FormSettings.tsx
Labels: zarmada internal PR

#458 Edit Dialog Refactor
  src/Components/SceneList/Internal/SceneDialog.state.ts
  src/Components/SceneList/Internal/SceneDialog.tsx
  src/Components/SceneList/SceneList.types.ts
Labels: small change :droplet:, refactor :hammer:

#548 Encapsulate theme object colors inside the context instead of forcing consumers to deal with it
  src/Components/3DV/SceneView.tsx
  src/Components/3DV/SceneViewWrapper.tsx
  src/Components/ModelViewerModePicker/SceneThemePicker.stories.tsx
  src/Components/ModelViewerModePicker/SceneThemePicker.tsx
  src/Models/Classes/SceneView.types.ts
  src/Models/Constants/Interfaces.ts
  src/Models/Context/SceneThemeContext/SceneThemeContext.stories.tsx
  src/Models/Context/SceneThemeContext/SceneThemeContext.tsx
  src/Models/Context/SceneThemeContext/SceneThemeContext.types.ts
Labels: small change :droplet:, refactor :hammer:

#563 Zarmada/working/ADTS-195
  src/Components/OATGraphViewer/Internal/OATGraphCustomEdge.tsx
  src/Components/OATGraphViewer/Internal/OATGraphCustomNode.tsx
  src/Components/OATGraphViewer/OATGraphViewer.styles.tsx
  src/Components/OATGraphViewer/OATGraphViewer.tsx
  src/Components/OATModelList/OATModelList.tsx
  src/Components/OATPropertyEditor/JSONEditor.tsx
  src/Components/OATPropertyEditor/OATPropertyEditor.styles.ts
  src/Components/OATPropertyEditor/PropertiesModelSummary.tsx
  src/Pages/OATEditorPage/Internal/Components/OATTextFieldDisplayName.tsx
  src/Pages/OATEditorPage/Internal/Components/OATTextFieldId.tsx
  src/Pages/OATEditorPage/Internal/Components/OATTextFieldName.tsx
  src/Pages/OATEditorPage/OATEditorPage.state.ts
  src/Pages/OATEditorPage/OATEditorPage.tsx
  src/Pages/OATEditorPage/OATEditorPage.types.ts
  src/Resources/Locales/cs.json
  src/Resources/Locales/de.json
  src/Resources/Locales/en.json
  src/Resources/Locales/es.json
  src/Resources/Locales/fr.json
  src/Resources/Locales/hu.json
  src/Resources/Locales/it.json
  src/Resources/Locales/ja.json
  src/Resources/Locales/ko.json
  src/Resources/Locales/nl.json
  src/Resources/Locales/pl.json
  src/Resources/Locales/pt-pt.json
  src/Resources/Locales/pt.json
  src/Resources/Locales/ru.json
  src/Resources/Locales/sv.json
  src/Resources/Locales/tr.json
  src/Resources/Locales/zh-Hans.json
Labels: zarmada internal PR

#562 Test for cardboard list callout
  jest.setup.ts
  src/Components/CardboardListCallout/CardboardListCallout.test.tsx
  src/Components/CardboardListCallout/CardboardListCallout.tsx
  src/Components/CardboardListCallout/CardboardListCallout.types.ts
  src/Components/CardboardListCallout/__snapshots__/CardboardListCallout.test.tsx.snap
Labels: enhancement :bulb:

#565 Zarmada/working/adts-195
  src/Components/OATGraphViewer/Internal/OATGraphCustomEdge.tsx
  src/Components/OATGraphViewer/Internal/OATGraphCustomNode.tsx
  src/Components/OATModelList/OATModelList.tsx
  src/Pages/OATEditorPage/Internal/Components/OATTextFieldId.tsx
  src/Pages/OATEditorPage/Internal/Components/OATTextFieldName.tsx
Labels: zarmada internal PR

#566 Zarmada/working/ADTS-205
  src/Components/OATGraphViewer/Internal/OATGraphCustomEdge.tsx
  src/Components/OATGraphViewer/OATGraphViewer.styles.tsx
  src/Components/OATHeader/internal/FormSettings.tsx
  src/Components/OATModelList/OATModelList.styles.tsx
  src/Components/OATModelList/OATModelList.tsx
  src/Components/OATPropertyEditor/PropertiesModelSummary.tsx
  src/Pages/OATEditorPage/Internal/Components/OATTextFieldDisplayName.tsx
  src/Pages/OATEditorPage/Internal/Components/OATTextFieldId.tsx
  src/Resources/Locales/cs.json
  src/Resources/Locales/de.json
  src/Resources/Locales/en.json
  src/Resources/Locales/es.json
  src/Resources/Locales/fr.json
  src/Resources/Locales/hu.json
  src/Resources/Locales/it.json
  src/Resources/Locales/ja.json
  src/Resources/Locales/ko.json
  src/Resources/Locales/nl.json
  src/Resources/Locales/pl.json
  src/Resources/Locales/pt-pt.json
  src/Resources/Locales/pt.json
  src/Resources/Locales/ru.json
  src/Resources/Locales/sv.json
  src/Resources/Locales/tr.json
  src/Resources/Locales/zh-Hans.json
Labels: zarmada internal PR

#521 Scene View better handling for not loading 3D file (including CORS)
  package-lock.json
  package.json
  src/Components/3DV/Internal/LoadingErrorMessage.tsx
  src/Components/3DV/SceneView.styles.ts
  src/Components/3DV/SceneView.tsx
  src/Resources/Locales/cs.json
  src/Resources/Locales/de.json
  src/Resources/Locales/en.json
  src/Resources/Locales/es.json
  src/Resources/Locales/fr.json
  src/Resources/Locales/hu.json
  src/Resources/Locales/it.json
  src/Resources/Locales/ja.json
  src/Resources/Locales/ko.json
  src/Resources/Locales/nl.json
  src/Resources/Locales/pl.json
  src/Resources/Locales/pt-pt.json
  src/Resources/Locales/pt.json
  src/Resources/Locales/ru.json
  src/Resources/Locales/sv.json
  src/Resources/Locales/tr.json
  src/Resources/Locales/zh-Hans.json
Labels: bugfix :bug: :white_check_mark:, refactor :hammer:

#567 Fix: Avoid camera issue when scene changes while loading
  src/Components/3DV/SceneView.tsx
Labels: bugfix :bug: :white_check_mark:, small change :droplet:

#564 ADTS-201 ADTS-202
  src/Components/OATGraphViewer/Internal/OATGraphCustomEdge.tsx
  src/Components/OATGraphViewer/Internal/OATGraphCustomNode.tsx
  src/Components/OATModelList/OATModelList.tsx
  src/Components/OATPropertyEditor/PropertyList.tsx
  src/Components/OATPropertyEditor/TemplateList.tsx
  src/Models/Constants/ActionTypes.ts
  src/Models/Constants/Interfaces.ts
  src/Pages/OATEditorPage/Internal/OATConfirmDeleteWrapper.tsx
  src/Pages/OATEditorPage/OATEditorPage.Styles.tsx
  src/Pages/OATEditorPage/OATEditorPage.state.ts
  src/Pages/OATEditorPage/OATEditorPage.tsx
  src/Pages/OATEditorPage/OATEditorPage.types.ts
Labels: zarmada internal PR

#570 Zarmada/working/ADTS-211
  src/Components/OATGraphViewer/Internal/OATGraphCustomNode.tsx
  src/Components/OATGraphViewer/OATGraphViewer.styles.tsx
  src/Resources/Static/relationshipComponent.svg
  src/Resources/Static/relationshipInheritance.svg
  src/Resources/Static/relationshipTargeted.svg
  src/Resources/Static/relationshipUntargeted.svg
Labels: zarmada internal PR

#569 Zarmada/working/ADTS-209
  src/Components/OATPropertyEditor/JSONEditor.tsx
Labels: zarmada internal PR

#568 Zarmada/working/ADTS-205
  src/Components/OATGraphViewer/Internal/OATGraphCustomEdge.tsx
  src/Components/OATHeader/internal/FormSettings.tsx
  src/Components/OATPropertyEditor/Editor.tsx
  src/Components/OATPropertyEditor/PropertiesModelSummary.tsx
Labels: zarmada internal PR

#575 Zarmada/working/ADTS-214
  src/Components/OATModelList/OATModelList.tsx
Labels: zarmada internal PR

#577 Zarmada/working/ADTS-206
  src/Components/OATGraphViewer/Internal/OATGraphCustomEdge.tsx
  src/Components/OATHeader/internal/FormSettings.tsx
Labels: zarmada internal PR

#578 Zarmada/working/ADTS-213
  src/Components/OATModelList/OATModelList.styles.tsx
Labels: zarmada internal PR

#579 Zarmada/working/ADTS-211
  src/Components/OATGraphViewer/OATGraphViewer.styles.tsx
Labels: zarmada internal PR

#580 Zarmada/working/ADTS-212
  src/Components/CardboardList/CardboardList.types.ts
  src/Components/CardboardList/CardboardListItem.tsx
  src/Components/OATPropertyEditor/PropertyList.tsx
  src/Components/OATPropertyEditor/PropertyListItemSubMenu.tsx
  src/Components/OATPropertyEditor/TemplateList.tsx
  src/Components/OATPropertyEditor/TemplateListItem.tsx
  src/Resources/Locales/cs.json
  src/Resources/Locales/de.json
  src/Resources/Locales/en.json
  src/Resources/Locales/es.json
  src/Resources/Locales/fr.json
  src/Resources/Locales/hu.json
  src/Resources/Locales/it.json
  src/Resources/Locales/ja.json
  src/Resources/Locales/ko.json
  src/Resources/Locales/nl.json
  src/Resources/Locales/pl.json
  src/Resources/Locales/pt-pt.json
  src/Resources/Locales/pt.json
  src/Resources/Locales/ru.json
  src/Resources/Locales/sv.json
  src/Resources/Locales/tr.json
  src/Resources/Locales/zh-Hans.json
Labels: zarmada internal PR

#581 Zarmada/working/ADTS-215
  src/Components/OATGraphViewer/Internal/OATGraphCustomEdge.tsx
Labels: zarmada internal PR

#583 Logging and Telemetry Framework
  .storybook/preview.js
  src/Components/TestStories/Logging.stories.tsx
  src/Models/Context/LoggingContextProvider.tsx
  src/Models/Hooks/useLogger.ts
  src/Models/Hooks/useTelemetry.ts
  src/Models/Services/LoggingService/LoggingService.ts
  src/Models/Services/LoggingService/LoggingService.types.ts
  src/Models/Services/TelemetryService/Telemetry.ts
  src/Models/Services/TelemetryService/TelemetryService.ts
  src/Models/Services/TelemetryService/TelemetryService.types.ts
  src/Models/Services/TelemetryService/__tests__/TelemetryService.test.ts
  src/Models/Services/index.ts
Labels: enhancement :bulb:, tests :mag:

#537 fix: Behavior form should prompt anytime you navigate away and there are changes pending
  jest.setup.ts
  package.json
  schemas/3DScenesConfiguration/v1.0.0/3DScenesConfiguration.schema.json
  src/Components/ADT3DSceneBuilder/ADT3DSceneBuilder.state.ts
  src/Components/ADT3DSceneBuilder/ADT3DSceneBuilder.tsx
  src/Components/ADT3DSceneBuilder/ADT3DSceneBuilder.types.ts
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/BehaviorsForm.tsx
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/Internal/AlertsTab.tsx
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/Internal/BehaviorFormContext/BehaviorFormContext.mock.ts
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/Internal/BehaviorFormContext/BehaviorFormContext.stories.tsx
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/Internal/BehaviorFormContext/BehaviorFormContext.test.tsx
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/Internal/BehaviorFormContext/BehaviorFormContext.tsx
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/Internal/BehaviorFormContext/BehaviorFormContext.types.ts
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/Internal/BehaviorFormContext/BehaviorFormContextUtility.test.ts
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/Internal/BehaviorFormContext/BehaviorFormContextUtility.ts
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/Internal/StatusTab.tsx
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/Internal/TwinsTab.tsx
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/Internal/WidgetsTab.tsx
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/Twins/BehaviorTwinAliasForm.tsx
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/Widgets/WidgetBuilders/GaugeWidgetBuilder.tsx
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/Widgets/WidgetBuilders/LinkWidgetBuilder.tsx
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/Widgets/WidgetBuilders/ValueWidgetBuilder.tsx
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/Widgets/WidgetForm/WidgetForm.tsx
  src/Components/ADT3DSceneBuilder/Internal/BuilderLeftPanel/BuilderLeftPanel.tsx
  src/Components/ADT3DSceneBuilder/Internal/Elements/Internal/BehaviorsTab.tsx
  src/Components/ADT3DSceneBuilder/Internal/SceneLayerMultiSelectBuilder/SceneLayerMultiSelectBuilder.tsx
  src/Components/ADT3DViewer/ADT3DViewer.tsx
  src/Components/BehaviorsModal/BehaviorsModal.tsx
  src/Components/CardboardListCallout/CardboardListCallout.test.tsx
  src/Components/CardboardListCallout/__snapshots__/CardboardListCallout.test.tsx.snap
  src/Components/SceneBreadcrumb/BaseBreadcrumb.tsx
  src/Components/SceneBreadcrumb/SceneBreadcrumb.stories.tsx
  src/Components/SceneBreadcrumb/SceneBreadcrumb.types.ts
  src/Components/SceneBreadcrumb/SceneBreadcrumbFactory.tsx
  src/Models/Classes/3DVConfig.ts
  src/Models/Constants/Types.ts
  src/Models/Services/Utils.ts
  src/Models/Types/Generated/3DScenesConfiguration-v1.0.0.d.ts
Labels: bugfix :bug: :white_check_mark:, large change :ocean:, refactor :hammer:

#588 Zarmada/working/ADTS-223
  src/Components/OATGraphViewer/OATGraphViewer.styles.tsx
  src/Components/OATGraphViewer/OATGraphViewer.tsx
  src/Components/OATPropertyEditor/Editor.tsx
  src/Components/OATPropertyEditor/OATPropertyEditor.styles.ts
  src/Components/OATPropertyEditor/PropertyList.tsx
  src/Components/OATPropertyEditor/PropertySelector.tsx
Labels: zarmada internal PR

#599 Zarmada/working/ADTS-223
  src/Components/OATPropertyEditor/PropertySelector.tsx
Labels: zarmada internal PR

#591 Zarmada/working/ADTS-226
  src/Components/CardboardList/CardboardList.types.ts
  src/Components/CardboardList/CardboardListItem.tsx
  src/Components/OATPropertyEditor/PropertyList.tsx
  src/Components/OATPropertyEditor/PropertyListEnumItemNested.tsx
  src/Components/OATPropertyEditor/PropertyListItem.tsx
  src/Components/OATPropertyEditor/PropertyListItemNest.tsx
  src/Components/OATPropertyEditor/PropertyListItemNested.tsx
  src/Components/OATPropertyEditor/TemplateList.tsx
Labels: zarmada internal PR

#592 ADTS-218
  src/Components/OATGraphViewer/Internal/OATGraphCustomEdge.tsx
  src/Pages/OATEditorPage/Internal/Components/OATTextFieldName.tsx
Labels: zarmada internal PR

#584 Zarmada/working/adts 201
  src/Components/OATGraphViewer/Internal/Classes/ConnectionParams.ts
  src/Components/OATGraphViewer/Internal/OATGraphCustomEdge.tsx
  src/Components/OATGraphViewer/OATGraphViewer.tsx
  src/Components/OATHeader/OATHeader.tsx
  src/Components/OATHeader/internal/FileSubMenu.tsx
  src/Components/OATHeader/internal/FormOpen.tsx
  src/Components/OATHeader/internal/FormSaveAs.tsx
  src/Components/OATHeader/internal/FormSettings.tsx
  src/Components/OATHeader/internal/ModalDelete.tsx
  src/Components/OATHeader/internal/ModalSaveCurrentProjectAndClear.tsx
  src/Components/OATModelList/OATModelList.tsx
  src/Components/OATPropertyEditor/FormAddEnumItem.tsx
  src/Components/OATPropertyEditor/FormRootModelDetails.tsx
  src/Components/OATPropertyEditor/FormUpdateProperty.tsx
  src/Components/OATPropertyEditor/JSONEditor.tsx
  src/Components/OATPropertyEditor/PropertyListEnumItemNested.tsx
  src/Components/OATPropertyEditor/PropertyListItemNest.tsx
  src/Components/OATPropertyEditor/PropertyListMapItemNested.tsx
  src/Components/OATPropertyEditor/PropertySelector.tsx
  src/Components/OATPropertyEditor/TemplateList.tsx
  src/Pages/OATEditorPage/Internal/Components/OATTextFieldDisplayName.tsx
  src/Pages/OATEditorPage/Internal/Components/OATTextFieldId.tsx
  src/Pages/OATEditorPage/Internal/Components/OATTextFieldName.tsx
Labels: zarmada internal PR

#604 Zarmada/working/adts 234
  src/Components/OATGraphViewer/Internal/OATGraphCustomNode.tsx
  src/Components/OATModelList/OATModelList.tsx
  src/Components/OATPropertyEditor/FormRootModelDetails.tsx
  src/Components/OATPropertyEditor/OATPropertyEditor.styles.ts
  src/Pages/OATEditorPage/Internal/Components/OATTextFieldId.tsx
  src/Resources/Static/Double.svg
  src/Resources/Static/Float.svg
  src/Resources/Static/Integer.svg
Labels: zarmada internal PR

#607 Zarmada/working/ADTS-241
  src/Components/OATGraphViewer/OATGraphViewer.tsx
  src/Components/OATPropertyEditor/OATPropertyEditor.styles.ts
  src/Components/OATPropertyEditor/PropertyList.tsx
  src/Components/OATPropertyEditor/Utils.ts
Labels: zarmada internal PR

#602 ADTS-224
  src/Components/OATGraphViewer/Internal/OATGraphCustomEdge.tsx
  src/Components/OATGraphViewer/OATGraphViewer.tsx
  src/Components/OATPropertyEditor/FormAddEnumItem.tsx
  src/Components/OATPropertyEditor/FormRootModelDetails.tsx
  src/Components/OATPropertyEditor/FormUpdateProperty.tsx
  src/Components/OATPropertyEditor/PropertySelector.tsx
  src/Components/OATPropertyEditor/Utils.ts
  src/Resources/Locales/cs.json
  src/Resources/Locales/de.json
  src/Resources/Locales/en.json
  src/Resources/Locales/es.json
  src/Resources/Locales/fr.json
  src/Resources/Locales/hu.json
  src/Resources/Locales/it.json
  src/Resources/Locales/ja.json
  src/Resources/Locales/ko.json
  src/Resources/Locales/nl.json
  src/Resources/Locales/pl.json
  src/Resources/Locales/pt-pt.json
  src/Resources/Locales/pt.json
  src/Resources/Locales/ru.json
  src/Resources/Locales/sv.json
  src/Resources/Locales/tr.json
  src/Resources/Locales/zh-Hans.json
Labels: zarmada internal PR
