Repository microsoft/iot-cardboard-js, pull requests merged in 2022-07, with the labels that each got.

#610 ADTS-245 Fixing and Testing
  src/Components/OATGraphViewer/Internal/OATGraphCustomEdge.tsx
  src/Components/OATGraphViewer/Internal/OATGraphCustomNode.tsx
  src/Components/OATGraphViewer/OATGraphViewer.styles.tsx
  src/Components/OATGraphViewer/OATGraphViewer.tsx
Labels: zarmada internal PR

#608 ADTS-230 ADTS-225 Implementations
  src/Components/OATPropertyEditor/FormAddEnumItem.tsx
  src/Components/OATPropertyEditor/FormRootModelDetails.tsx
  src/Components/OATPropertyEditor/FormUpdateProperty.tsx
  src/Components/OATPropertyEditor/OATPropertyEditor.styles.ts
  src/Components/OATPropertyEditor/PropertiesModelSummary.tsx
  src/Components/OATPropertyEditor/PropertyListItem.tsx
  src/Components/OATPropertyEditor/PropertyListItemNest.tsx
  src/Components/OATPropertyEditor/PropertyListItemNested.tsx
Labels: zarmada internal PR

#612 ADTS-220 Changes For BezierPath
  src/Components/OATGraphViewer/Internal/OATGraphCustomEdge.tsx
Labels: zarmada internal PR

#614 Zarmada/working/ADTS-252
  src/Components/OATPropertyEditor/FormUpdateProperty.tsx
  src/Components/OATPropertyEditor/OATPropertyEditor.styles.ts
  src/Components/OATPropertyEditor/PropertyListItem.tsx
  src/Components/OATPropertyEditor/PropertyListItemNest.tsx
  src/Components/OATPropertyEditor/PropertyListItemNested.tsx
  src/Components/OATPropertyEditor/PropertySelector.tsx
  src/Models/Constants/Constants.ts
Labels: zarmada internal PR

#615 Zarmada/working/ADTS-254
  src/Components/OATModelList/OATModelList.styles.tsx
  src/Components/OATModelList/OATModelList.tsx
  src/Components/OATPropertyEditor/OATPropertyEditor.styles.ts
  src/Components/OATPropertyEditor/PropertiesModelSummary.tsx
Labels: zarmada internal PR

#616 Zarmada/working/ADTS-248
  src/Components/OATGraphViewer/Internal/OATGraphCustomEdge.tsx
Labels: zarmada internal PR

#617 Zarmada/working/ADTS-256
  src/Components/OATHeader/OATHeader.styles.ts
  src/Components/OATHeader/OATHeader.tsx
  src/Components/OATModelList/OATModelList.tsx
Labels: zarmada internal PR

#621 ADTS-261 Fixing Overflow and adding Run layout button
  src/Components/OATGraphViewer/OATGraphViewer.styles.tsx
  src/Components/OATGraphViewer/OATGraphViewer.tsx
  src/Components/OATPropertyEditor/OATPropertyEditor.styles.ts
  src/Resources/Locales/cs.json
  src/Resources/Locales/de.json
  src/Resources/Locales/en.json
  src/Resources/Locales/es.json
  src/Resources/Locales/fr.json
  src/Resources/Locales/hu.json
  src/Resources/Locales/it.json
  src/Resources/Locales/ja.json
  src/Resources/Locales/ko.json
  src/Resources/Locales/nl.json
  src/Resources/Locales/pl.json
  src/Resources/Locales/pt-pt.json
  src/Resources/Locales/pt.json
  src/Resources/Locales/ru.json
  src/Resources/Locales/sv.json
  src/Resources/Locales/tr.json
  src/Resources/Locales/zh-Hans.json
Labels: zarmada internal PR

#618 zarmada/working/ADTS-237
  src/Components/OATGraphViewer/Internal/OATGraphCustomEdge.tsx
  src/Components/OATGraphViewer/Internal/OATGraphCustomNode.tsx
  src/Components/OATModelList/OATModelList.tsx
  src/Components/OATPropertyEditor/FormRootModelDetails.tsx
  src/Components/OATPropertyEditor/PropertiesModelSummary.tsx
  src/Pages/OATEditorPage/Internal/Components/OATTextFieldDisplayName.tsx
  src/Pages/OATEditorPage/Internal/Components/OATTextFieldId.tsx
  src/Pages/OATEditorPage/Internal/Components/OATTextFieldName.tsx
Labels: zarmada internal PR

#620 zarmada/working/ADTS-257
  src/Components/OATGraphViewer/OATGraphViewer.tsx
Labels: zarmada internal PR

#613 Zarmada/working/ADTS-244
  src/Components/OATGraphViewer/OATGraphViewer.tsx
  src/Resources/Locales/cs.json
  src/Resources/Locales/de.json
  src/Resources/Locales/en.json
  src/Resources/Locales/es.json
  src/Resources/Locales/fr.json
  src/Resources/Locales/hu.json
  src/Resources/Locales/it.json
  src/Resources/Locales/ja.json
  src/Resources/Locales/ko.json
  src/Resources/Locales/nl.json
  src/Resources/Locales/pl.json
  src/Resources/Locales/pt-pt.json
  src/Resources/Locales/pt.json
  src/Resources/Locales/ru.json
  src/Resources/Locales/sv.json
  src/Resources/Locales/tr.json
  src/Resources/Locales/zh-Hans.json
Labels: zarmada internal PR

#622 Zarmada/working/ADTS-259
  src/Components/OATGraphViewer/Internal/OATGraphCustomEdge.tsx
  src/Components/OATGraphViewer/Internal/OATGraphCustomNode.tsx
  src/Components/OATGraphViewer/OATGraphViewer.tsx
  src/Components/OATPropertyEditor/PropertyList.tsx
  src/Components/OATPropertyEditor/PropertyListItem.tsx
  src/Components/OATPropertyEditor/PropertySelector.tsx
Labels: zarmada internal PR

#606 Zarmada/working/ADTS-235
  src/Components/OATGraphViewer/OATGraphViewer.styles.tsx
  src/Components/OATGraphViewer/OATGraphViewer.tsx
  src/Components/OATHeader/OATHeader.styles.ts
  src/Components/OATHeader/OATHeader.tsx
  src/Components/OATHeader/internal/FileSubMenu.tsx
  src/Components/OATHeader/internal/FormOpen.tsx
  src/Components/OATHeader/internal/FormSaveAs.tsx
  src/Components/OATHeader/internal/ImportSubMenu.tsx
  src/Components/OATHeader/internal/ModalSaveCurrentProjectAndClear.tsx
  src/Components/OATPropertyEditor/FormRootModelDetails.tsx
  src/Models/Constants/ActionTypes.ts
  src/Models/Services/Utils.ts
  src/Pages/OATEditorPage/Internal/Classes/index.ts
  src/Pages/OATEditorPage/OATEditorPage.state.ts
  src/Pages/OATEditorPage/OATEditorPage.tsx
  src/Pages/OATEditorPage/OATEditorPage.types.ts
  src/Resources/Locales/cs.json
  src/Resources/Locales/de.json
  src/Resources/Locales/en.json
  src/Resources/Locales/es.json
  src/Resources/Locales/fr.json
  src/Resources/Locales/hu.json
  src/Resources/Locales/it.json
  src/Resources/Locales/ja.json
  src/Resources/Locales/ko.json
  src/Resources/Locales/nl.json
  src/Resources/Locales/pl.json
  src/Resources/Locales/pt-pt.json
  src/Resources/Locales/pt.json
  src/Resources/Locales/ru.json
  src/Resources/Locales/sv.json
  src/Resources/Locales/tr.json
  src/Resources/Locales/zh-Hans.json
Labels: zarmada internal PR

#624 Zarmada/working/ADTS-262
  src/Components/OATGraphViewer/OATGraphViewer.tsx
  src/Components/OATModelList/OATModelList.styles.tsx
  src/Components/OATPropertyEditor/OATPropertyEditor.styles.ts
Labels: zarmada internal PR

#625 Zarmada/working/ADTS-263
  src/Components/OATGraphViewer/Internal/OATGraphCustomNode.tsx
  src/Components/OATGraphViewer/OATGraphViewer.tsx
  src/Components/OATHeader/OATHeader.tsx
  src/Components/OATPropertyEditor/OATPropertyEditor.styles.ts
Labels: zarmada internal PR

#598 Zarmada/working/ADTS-178
  src/Components/OATGraphViewer/Internal/OATGraphCustomEdge.tsx
  src/Components/OATGraphViewer/OATGraphViewer.tsx
  src/Components/OATHeader/OATHeader.styles.ts
  src/Components/OATHeader/OATHeader.tsx
  src/Components/OATModelList/OATModelList.tsx
  src/Components/OATPropertyEditor/FormAddEnumItem.tsx
  src/Components/OATPropertyEditor/FormRootModelDetails.tsx
  src/Components/OATPropertyEditor/FormUpdateProperty.tsx
  src/Components/OATPropertyEditor/JSONEditor.tsx
  src/Components/OATPropertyEditor/PropertiesModelSummary.tsx
  src/Components/OATPropertyEditor/PropertyList.tsx
  src/Components/OATPropertyEditor/PropertyListItem.tsx
  src/Components/OATPropertyEditor/PropertyListItemNest.tsx
  src/Components/OATPropertyEditor/PropertyListItemNested.tsx
  src/Components/OATPropertyEditor/PropertyListItemSubMenu.tsx
  src/Components/OATPropertyEditor/PropertySelector.tsx
  src/Components/OATPropertyEditor/TemplateList.tsx
  src/Pages/OATEditorPage/Internal/Components/OATTextFieldDisplayName.tsx
  src/Pages/OATEditorPage/Internal/Components/OATTextFieldId.tsx
  src/Pages/OATEditorPage/Internal/Components/OATTextFieldName.tsx
  src/Pages/OATEditorPage/Internal/Context/CommandHistoryContext.tsx
  src/Pages/OATEditorPage/Internal/Hooks/useCommandHistory.tsx
  src/Pages/OATEditorPage/OATEditorPage.tsx
  src/Resources/Locales/cs.json
  src/Resources/Locales/de.json
  src/Resources/Locales/en.json
  src/Resources/Locales/es.json
  src/Resources/Locales/fr.json
  src/Resources/Locales/hu.json
  src/Resources/Locales/it.json
  src/Resources/Locales/ja.json
  src/Resources/Locales/ko.json
  src/Resources/Locales/nl.json
  src/Resources/Locales/pl.json
  src/Resources/Locales/pt-pt.json
  src/Resources/Locales/pt.json
  src/Resources/Locales/ru.json
  src/Resources/Locales/sv.json
  src/Resources/Locales/tr.json
  src/Resources/Locales/zh-Hans.json
Labels: zarmada internal PR

#631 Unused prop and ref cleanup
  src/Components/ADT3DGlobe/ADT3DGlobe.tsx
  src/Pages/ADT3DScenePage/ADT3DScenePage.tsx
  src/Pages/ADT3DScenePage/ADT3DScenePage.types.ts
  src/Pages/ADT3DScenePage/Internal/ADT3DSceneBuilderContainer.tsx
Labels: small change :droplet:

#629 Zarmada/working/ADTS-268
  src/Components/OATGraphViewer/Internal/OATGraphCustomNode.tsx
  src/Components/OATGraphViewer/OATGraphViewer.styles.tsx
  src/Components/OATGraphViewer/OATGraphViewer.tsx
  src/Components/OATHeader/OATHeader.tsx
  src/Components/OATModelList/OATModelList.styles.tsx
  src/Components/OATModelList/OATModelList.tsx
  src/Components/OATPropertyEditor/Editor.tsx
  src/Components/OATPropertyEditor/OATPropertyEditor.styles.ts
  src/Components/OATPropertyEditor/PropertiesModelSummary.tsx
  src/Components/OATPropertyEditor/PropertyList.tsx
  src/Components/OATPropertyEditor/PropertySelector.tsx
  src/Components/OATPropertyEditor/Utils.ts
  src/Pages/OATEditorPage/OATEditorPage.state.ts
Labels: zarmada internal PR

#637 Zarmada/working/ADTS-271
  src/Components/OATGraphViewer/OATGraphViewer.tsx
  src/Components/OATModelList/OATModelList.styles.tsx
  src/Components/OATModelList/OATModelList.tsx
  src/Pages/OATEditorPage/Internal/Components/OATTextFieldId.tsx
Labels: zarmada internal PR

#633 Make meshes tab appear required
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/BehaviorsForm.styles.ts
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/BehaviorsForm.tsx
  src/Components/ADT3DSceneBuilder/Internal/Elements/ElementForm.tsx
  src/Resources/Locales/cs.json
  src/Resources/Locales/de.json
  src/Resources/Locales/en.json
  src/Resources/Locales/es.json
  src/Resources/Locales/fr.json
  src/Resources/Locales/hu.json
  src/Resources/Locales/it.json
  src/Resources/Locales/ja.json
  src/Resources/Locales/ko.json
  src/Resources/Locales/nl.json
  src/Resources/Locales/pl.json
  src/Resources/Locales/pt-pt.json
  src/Resources/Locales/pt.json
  src/Resources/Locales/ru.json
  src/Resources/Locales/sv.json
  src/Resources/Locales/tr.json
  src/Resources/Locales/zh-Hans.json
  src/Theming/FluentComponentStyles/Pivot.styles.ts
  src/Theming/FluentComponentStyles/Pivot.styles.tsx
Labels: small change :droplet:

#630 Logical State Icons for Alerts
  src/Theming/Palettes.ts
Labels: small change :droplet:

#639 Zarmada/working/ADTS-271
  src/Components/OATModelList/OATModelList.tsx
Labels: zarmada internal PR

#641 Fix: Model file upload correctly creates new scene
  src/Components/SceneList/Internal/SceneDialog.tsx
Labels: bugfix :bug: :white_check_mark:

#646 Zarmada/working/staging fixes
  src/Components/OATGraphViewer/Internal/Classes/ElementData.ts
  src/Components/OATGraphViewer/Internal/Classes/ElementEdge.ts
  src/Components/OATGraphViewer/Internal/Classes/ElementEdgeData.ts
  src/Components/OATGraphViewer/Internal/Classes/ElementNode.ts
  src/Components/OATGraphViewer/Internal/Classes/ElementPosition.ts
  src/Components/OATGraphViewer/Internal/Interfaces/index.ts
  src/Components/OATGraphViewer/Internal/OATContext.tsx
  src/Components/OATGraphViewer/Internal/OATGraphCustomEdge.tsx
  src/Components/OATGraphViewer/Internal/OATGraphCustomNode.tsx
  src/Components/OATGraphViewer/Internal/Utils.tsx
  src/Components/OATGraphViewer/OATGraphViewer.state.ts
  src/Components/OATGraphViewer/OATGraphViewer.stories.tsx
  src/Components/OATGraphViewer/OATGraphViewer.tsx
  src/Components/OATModelList/OATModelList.state.ts
  src/Components/OATModelList/OATModelList.stories.tsx
  src/Components/OATModelList/OATModelList.tsx
  src/Components/OATPropertyEditor/Editor.tsx
  src/Components/OATPropertyEditor/Editor.types.ts
  src/Components/OATPropertyEditor/FormAddEnumItem.tsx
  src/Components/OATPropertyEditor/FormAddEnumItem.types.ts
  src/Components/OATPropertyEditor/FormRootModelDetails.tsx
  src/Components/OATPropertyEditor/FormUpdateProperty.tsx
  src/Components/OATPropertyEditor/FormUpdateProperty.types.ts
  src/Components/OATPropertyEditor/JSONEditor.tsx
  src/Components/OATPropertyEditor/OATPropertyEditor.tsx
  src/Components/OATPropertyEditor/PropertiesModelSummary.tsx
  src/Components/OATPropertyEditor/PropertiesModelSummary.types.ts
  src/Components/OATPropertyEditor/PropertyList.tsx
  src/Components/OATPropertyEditor/PropertyList.types.ts
  src/Components/OATPropertyEditor/PropertyListEnumItemNested.tsx
  src/Components/OATPropertyEditor/PropertyListItem.tsx
  src/Components/OATPropertyEditor/PropertyListItem.types.ts
  src/Components/OATPropertyEditor/PropertyListItemNest.tsx
  src/Components/OATPropertyEditor/PropertyListItemNest.types.ts
  src/Components/OATPropertyEditor/PropertyListItemNested.tsx
  src/Components/OATPropertyEditor/PropertyListItemNested.types.ts
  src/Components/OATPropertyEditor/PropertyListMapItemNested.tsx
  src/Components/OATPropertyEditor/PropertySelector.tsx
  src/Components/OATPropertyEditor/TemplateColumn.tsx
  src/Components/OATPropertyEditor/TemplateColumn.types.ts
  src/Components/OATPropertyEditor/TemplateList.tsx
  src/Components/OATPropertyEditor/TemplateList.types.ts
  src/Components/OATPropertyEditor/TeplateListItem.tsx
  src/Components/OATPropertyEditor/Utils.ts
  src/Models/Constants/Interfaces.ts
  src/Models/Services/Utils.ts
  src/Pages/OATEditorPage/Internal/Classes/index.ts
  src/Pages/OATEditorPage/Internal/Components/OATTextFieldDisplayName.types.ts
  src/Pages/OATEditorPage/Internal/Components/OATTextFieldId.types.ts
  src/Pages/OATEditorPage/Internal/Components/OATTextFieldName.tsx
  src/Pages/OATEditorPage/Internal/Components/OATTextFieldName.types.ts
  src/Pages/OATEditorPage/Internal/OATConfirmDeleteModal.tsx
  src/Pages/OATEditorPage/Internal/OATErrorHandlingModal.tsx
  src/Pages/OATEditorPage/Internal/OATErrorPage.tsx
  src/Pages/OATEditorPage/Internal/Types/index.ts
  src/Pages/OATEditorPage/OATEditorPage.state.ts
  src/Pages/OATEditorPage/OATEditorPage.styles.tsx
  src/Pages/OATEditorPage/OATEditorPage.tsx
  src/Pages/OATEditorPage/OATEditorPage.types.ts
Labels: zarmada internal PR

#648 zarmada/working/ADTS-276
  src/Components/OATHeader/OATHeader.tsx
  src/Components/OATPropertyEditor/Editor.tsx
  src/Components/OATPropertyEditor/FormAddEnumItem.tsx
  src/Components/OATPropertyEditor/FormUpdateProperty.tsx
  src/Components/OATPropertyEditor/Modal.tsx
  src/Components/OATPropertyEditor/OATPropertyEditor.styles.ts
  src/Components/OATPropertyEditor/PropertyListEnumItemNested.tsx
  src/Components/OATPropertyEditor/Utils.ts
  src/Resources/Locales/cs.json
  src/Resources/Locales/de.json
  src/Resources/Locales/en.json
  src/Resources/Locales/es.json
  src/Resources/Locales/fr.json
  src/Resources/Locales/hu.json
  src/Resources/Locales/it.json
  src/Resources/Locales/ja.json
  src/Resources/Locales/ko.json
  src/Resources/Locales/nl.json
  src/Resources/Locales/pl.json
  src/Resources/Locales/pt-pt.json
  src/Resources/Locales/pt.json
  src/Resources/Locales/ru.json
  src/Resources/Locales/sv.json
  src/Resources/Locales/tr.json
  src/Resources/Locales/zh-Hans.json
Labels: zarmada internal PR

#640 Update storybook version to latest
  package-lock.json
  package.json
Labels: Package upgrade

#652 Ignore Card stories when building Storybook
  .storybook/main.js
Labels: small change :droplet:, build system 🏗️

#651 Zarmada/working/ADTS-275
  src/Components/OATGraphViewer/OATGraphViewer.tsx
  src/Components/OATHeader/OATHeader.tsx
  src/Components/OATPropertyEditor/JSONEditor.tsx
  src/Models/Services/Utils.ts
  src/Resources/Locales/cs.json
  src/Resources/Locales/de.json
  src/Resources/Locales/en.json
  src/Resources/Locales/es.json
  src/Resources/Locales/fr.json
  src/Resources/Locales/hu.json
  src/Resources/Locales/it.json
  src/Resources/Locales/ja.json
  src/Resources/Locales/ko.json
  src/Resources/Locales/nl.json
  src/Resources/Locales/pl.json
  src/Resources/Locales/pt-pt.json
  src/Resources/Locales/pt.json
  src/Resources/Locales/ru.json
  src/Resources/Locales/sv.json
  src/Resources/Locales/tr.json
  src/Resources/Locales/zh-Hans.json
Labels: zarmada internal PR
