Repository microsoft/iot-cardboard-js, pull requests merged in 2022-09, with the labels that each got.

#683 Query builder UI + field validation
  src/Components/AdvancedSearch/AdvancedSearch.stories.tsx
  src/Components/AdvancedSearch/AdvancedSearch.styles.ts
  src/Components/AdvancedSearch/AdvancedSearch.tsx
  src/Components/AdvancedSearch/AdvancedSearch.types.ts
  src/Components/AdvancedSearch/AdvancedSearchModal.tsx
  src/Components/AdvancedSearch/Internal/QueryBuilder.tsx
  src/Components/AdvancedSearch/Internal/QueryBuilder/QueryBuilder.styles.ts
  src/Components/AdvancedSearch/Internal/QueryBuilder/QueryBuilder.tsx
  src/Components/AdvancedSearch/Internal/QueryBuilder/QueryBuilder.types.ts
  src/Components/AdvancedSearch/Internal/QueryBuilder/QueryBuilderRow.tsx
  src/Components/AdvancedSearch/Internal/QueryBuilder/QueryBuilderUtils.ts
  src/Components/ModelledPropertyBuilder/ModelledPropertyBuilder.model.ts
  src/Models/Hooks/__tests__/useFlattenedModelProperties.test.ts
  src/Models/Hooks/useFlattenedModelProperties.ts
  src/Models/Services/StoryUtilities.tsx
  src/Resources/Locales/cs.json
  src/Resources/Locales/de.json
  src/Resources/Locales/en.json
  src/Resources/Locales/es.json
  src/Resources/Locales/fr.json
  src/Resources/Locales/hu.json
  src/Resources/Locales/it.json
  src/Resources/Locales/ja.json
  src/Resources/Locales/ko.json
  src/Resources/Locales/nl.json
  src/Resources/Locales/pl.json
  src/Resources/Locales/pt-pt.json
  src/Resources/Locales/pt.json
  src/Resources/Locales/ru.json
  src/Resources/Locales/sv.json
  src/Resources/Locales/tr.json
  src/Resources/Locales/zh-Hans.json
Labels: enhancement :bulb:

#689 [Telemetry] Wire up telemetry events for KPI metrics & initial user actions
  package-lock.json
  package.json
  src/Adapters/ADTAdapter.ts
  src/Adapters/BlobAdapter.ts
  src/Adapters/BlobAdapterUtility.ts
  src/Components/SceneList/SceneList.tsx
  src/Models/Constants/Constants.ts
  src/Models/Constants/TelemetryConstants.ts
  src/Models/Context/DeeplinkContext/DeeplinkContext.tsx
  src/Models/Hooks/useTelemetry.ts
  src/Models/Services/TelemetryService/Telemetry.ts
  src/Models/Services/TelemetryService/TelemetryService.ts
  src/Models/Services/TelemetryService/TelemetryService.types.ts
  src/Models/Services/TelemetryService/__tests__/TelemetryService.test.ts
  src/Models/Services/Utils.test.ts
  src/Models/Services/Utils.ts
Labels: enhancement :bulb:, large change :ocean:

#686 Enable sorting Advanced Search Results List
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/Behaviors.tsx
  src/Components/ADT3DSceneBuilder/Internal/Elements/Internal/BehaviorsTab.tsx
  src/Components/AdvancedSearch/Internal/AdvancedSearchResultDetailsList/AdvancedSearchResultDetailsList.tsx
  src/Models/Services/Utils.ts
Labels: enhancement :bulb:

#688 Querying adapter method (and some UI updates)
  src/Adapters/ADTAdapter.ts
  src/Adapters/MockAdapter.ts
  src/Components/AdvancedSearch/AdvancedSearch.stories.local.tsx
  src/Components/AdvancedSearch/AdvancedSearch.stories.tsx
  src/Components/AdvancedSearch/AdvancedSearch.tsx
  src/Components/AdvancedSearch/AdvancedSearch.types.ts
  src/Components/AdvancedSearch/Internal/AdvancedSearchResultDetailsList/AdvancedSearchResultDetailsList.styles.ts
  src/Components/AdvancedSearch/Internal/AdvancedSearchResultDetailsList/AdvancedSearchResultDetailsList.tsx
  src/Components/AdvancedSearch/Internal/AdvancedSearchResultDetailsList/AdvancedSearchResultDetailsList.types.ts
  src/Components/AdvancedSearch/Internal/QueryBuilder/QueryBuilder.styles.ts
  src/Components/AdvancedSearch/Internal/QueryBuilder/QueryBuilder.tsx
  src/Components/AdvancedSearch/Internal/QueryBuilder/QueryBuilder.types.ts
  src/Components/AdvancedSearch/Internal/QueryBuilder/QueryBuilderRow.tsx
  src/Components/AdvancedSearch/Internal/QueryBuilder/QueryBuilderUtils.ts
  src/Components/ModelledPropertyBuilder/ModelledPropertyBuilder.model.ts
  src/Components/ModelledPropertyBuilder/ModelledPropertyBuilder.types.ts
  src/Components/ModelledPropertyBuilder/useModelledProperties.ts
  src/Models/Classes/AdapterDataClasses/ADTAdapterData.ts
  src/Models/Classes/AdapterResult.ts
  src/Models/Constants/Constants.ts
  src/Models/Constants/Enums.ts
  src/Models/Constants/Interfaces.ts
  src/Models/Constants/Types.ts
  src/Models/Hooks/__tests__/useFlattenedModelProperties.test.ts
  src/Models/Hooks/useFlattenedModelProperties.ts
  src/Resources/Locales/cs.json
  src/Resources/Locales/de.json
  src/Resources/Locales/en.json
  src/Resources/Locales/es.json
  src/Resources/Locales/fr.json
  src/Resources/Locales/hu.json
  src/Resources/Locales/it.json
  src/Resources/Locales/ja.json
  src/Resources/Locales/ko.json
  src/Resources/Locales/nl.json
  src/Resources/Locales/pl.json
  src/Resources/Locales/pt-pt.json
  src/Resources/Locales/pt.json
  src/Resources/Locales/ru.json
  src/Resources/Locales/sv.json
  src/Resources/Locales/tr.json
  src/Resources/Locales/zh-Hans.json
Labels: enhancement :bulb:

#697 Fix null reference in environment picker
  src/Components/EnvironmentPicker/EnvironmentPicker.tsx
Labels: bugfix :bug: :white_check_mark:

#696 Integrating Advanced search to Element form
  src/Components/ADT3DSceneBuilder/Internal/Elements/ElementForm.tsx
  src/Components/AdvancedSearch/AdvancedSearch.stories.local.tsx
  src/Components/AdvancedSearch/AdvancedSearch.stories.tsx
  src/Components/AdvancedSearch/AdvancedSearch.styles.ts
  src/Components/AdvancedSearch/AdvancedSearch.tsx
  src/Components/AdvancedSearch/AdvancedSearch.types.ts
  src/Components/AdvancedSearch/Internal/AdvancedSearchResultDetailsList/AdvancedSearchResultDetailsList.stories.tsx
  src/Components/AdvancedSearch/Internal/AdvancedSearchResultDetailsList/AdvancedSearchResultDetailsList.tsx
  src/Components/AdvancedSearch/Internal/AdvancedSearchResultDetailsList/AdvancedSearchResultDetailsList.types.ts
  src/Components/AdvancedSearch/Internal/QueryBuilder/QueryBuilder.styles.ts
  src/Components/AdvancedSearch/Internal/QueryBuilder/QueryBuilderRow.tsx
  src/Components/PropertyInspector/PropertyInspectorCallout/PropertyInspectorCallout.tsx
  src/Components/PropertyInspector/PropertyInspectorCallout/PropertyInspectorCallout.types.ts
  src/Components/TwinPropertySearchDropdown/TwinPropertySearchDropdown.tsx
  src/Components/TwinPropertySearchDropdown/TwinPropertySearchDropdown.types.ts
  src/Models/Services/StoryUtilities.tsx
  src/Resources/Locales/cs.json
  src/Resources/Locales/de.json
  src/Resources/Locales/en.json
  src/Resources/Locales/es.json
  src/Resources/Locales/fr.json
  src/Resources/Locales/hu.json
  src/Resources/Locales/it.json
  src/Resources/Locales/ja.json
  src/Resources/Locales/ko.json
  src/Resources/Locales/nl.json
  src/Resources/Locales/pl.json
  src/Resources/Locales/pt-pt.json
  src/Resources/Locales/pt.json
  src/Resources/Locales/ru.json
  src/Resources/Locales/sv.json
  src/Resources/Locales/tr.json
  src/Resources/Locales/zh-Hans.json
Labels: enhancement :bulb:

#704 Bug Fix: Overflow tabs cause react error
  .eslintrc.json
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/BehaviorsForm.tsx
  src/Components/ADT3DSceneBuilder/Internal/Elements/ElementForm.tsx
  src/Components/OATHeader/internal/FormOpen.tsx
  src/Theming/FluentComponentStyles/Pivot.styles.tsx
Labels: bugfix :bug: :white_check_mark:

#703 Advanced search feedback fixes [1/2]
  src/Components/ADT3DSceneBuilder/Internal/Elements/ElementForm.tsx
  src/Resources/Locales/cs.json
  src/Resources/Locales/de.json
  src/Resources/Locales/en.json
  src/Resources/Locales/es.json
  src/Resources/Locales/fr.json
  src/Resources/Locales/hu.json
  src/Resources/Locales/it.json
  src/Resources/Locales/ja.json
  src/Resources/Locales/ko.json
  src/Resources/Locales/nl.json
  src/Resources/Locales/pl.json
  src/Resources/Locales/pt-pt.json
  src/Resources/Locales/pt.json
  src/Resources/Locales/ru.json
  src/Resources/Locales/sv.json
  src/Resources/Locales/tr.json
  src/Resources/Locales/zh-Hans.json
Labels: small change :droplet:

#702 Visual rules flighting
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/BehaviorsForm.tsx
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/Internal/VisualRulesTab.tsx
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/VisualRules/VisualRuleList.tsx
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/VisualRules/VisualRules.types.ts
  src/Models/Constants/Constants.ts
  src/Resources/Locales/cs.json
  src/Resources/Locales/de.json
  src/Resources/Locales/en.json
  src/Resources/Locales/es.json
  src/Resources/Locales/fr.json
  src/Resources/Locales/hu.json
  src/Resources/Locales/it.json
  src/Resources/Locales/ja.json
  src/Resources/Locales/ko.json
  src/Resources/Locales/nl.json
  src/Resources/Locales/pl.json
  src/Resources/Locales/pt-pt.json
  src/Resources/Locales/pt.json
  src/Resources/Locales/ru.json
  src/Resources/Locales/sv.json
  src/Resources/Locales/tr.json
  src/Resources/Locales/zh-Hans.json
Labels: small change :droplet:, wip 🚧

#707 Creating a generic modal component
  src/Components/AdvancedSearch/AdvancedSearch.styles.ts
  src/Components/AdvancedSearch/AdvancedSearch.tsx
  src/Components/AdvancedSearch/AdvancedSearch.types.ts
  src/Components/CardboardModal/CardboardModal.stories.tsx
  src/Components/CardboardModal/CardboardModal.styles.ts
  src/Components/CardboardModal/CardboardModal.tsx
  src/Components/CardboardModal/CardboardModal.types.ts
  src/Models/Constants/Types.ts
Labels: small change :droplet:
