Repository microsoft/iot-cardboard-js, pull requests merged in 2022-10, with the labels that each got.

#706 Data History Spike - migrate local storage to new keys for environment data
  src/Components/BlobDropdown/BlobDropdown.tsx
  src/Components/EnvironmentPicker/EnvironmentPicker.mock.ts
  src/Components/EnvironmentPicker/EnvironmentPicker.state.ts
  src/Components/EnvironmentPicker/EnvironmentPicker.test.tsx
  src/Components/EnvironmentPicker/EnvironmentPicker.tsx
  src/Components/EnvironmentPicker/EnvironmentPicker.types.ts
  src/Components/EnvironmentPicker/EnvironmentPickerManager.test.ts
  src/Components/EnvironmentPicker/EnvironmentPickerManager.ts
  src/Components/ResourcePicker/ResourcePicker.tsx
  src/Models/Classes/AdapterDataClasses/ADTInstanceConnectionData.ts
  src/Models/Constants/Constants.ts
  src/Models/Constants/Interfaces.ts
  src/Models/Context/DeeplinkContext/DeeplinkContext.tsx
  src/Models/Context/DeeplinkContext/DeeplinkContext.types.ts
  src/Models/Services/LocalStorageManager/LocalStorageManager.ts
  src/Models/Services/LocalStorageManager/LocalStorageManager.types.ts
  src/Models/Services/Utils.ts
  src/Models/Services/__tests__/Utils.test.ts
  src/Pages/ADT3DScenePage/ADT3DScenePage.stories.local.tsx
  src/Pages/ADT3DScenePage/ADT3DScenePage.tsx
  src/Pages/ADT3DScenePage/ADT3DScenePage.types.ts
  src/Pages/ADTTwinsPage/ADTTwinsPage.tsx
  src/Resources/Locales/cs.json
  src/Resources/Locales/de.json
  src/Resources/Locales/en.json
  src/Resources/Locales/es.json
  src/Resources/Locales/fr.json
  src/Resources/Locales/hu.json
  src/Resources/Locales/it.json
  src/Resources/Locales/ja.json
  src/Resources/Locales/ko.json
  src/Resources/Locales/nl.json
  src/Resources/Locales/pl.json
  src/Resources/Locales/pt-pt.json
  src/Resources/Locales/pt.json
  src/Resources/Locales/ru.json
  src/Resources/Locales/sv.json
  src/Resources/Locales/tr.json
  src/Resources/Locales/zh-Hans.json
Labels: enhancement :bulb:

#698 Column Picker
  src/Components/AdvancedSearch/Internal/AdvancedSearchResultDetailsList/AdvancedSearchResultDetailsList.styles.ts
  src/Components/AdvancedSearch/Internal/AdvancedSearchResultDetailsList/AdvancedSearchResultDetailsList.tsx
  src/Components/AdvancedSearch/Internal/AdvancedSearchResultDetailsList/AdvancedSearchResultDetailsList.types.ts
  src/Components/AdvancedSearch/Internal/ColumnPicker/ColumnPicker.styles.ts
  src/Components/AdvancedSearch/Internal/ColumnPicker/ColumnPicker.tsx
  src/Components/AdvancedSearch/Internal/ColumnPicker/ColumnPicker.types.ts
  src/Components/CardboardModal/CardboardModal.tsx
  src/Resources/Locales/cs.json
  src/Resources/Locales/de.json
  src/Resources/Locales/en.json
  src/Resources/Locales/es.json
  src/Resources/Locales/fr.json
  src/Resources/Locales/hu.json
  src/Resources/Locales/it.json
  src/Resources/Locales/ja.json
  src/Resources/Locales/ko.json
  src/Resources/Locales/nl.json
  src/Resources/Locales/pl.json
  src/Resources/Locales/pt-pt.json
  src/Resources/Locales/pt.json
  src/Resources/Locales/ru.json
  src/Resources/Locales/sv.json
  src/Resources/Locales/tr.json
  src/Resources/Locales/zh-Hans.json
Labels: enhancement :bulb:

#708 Visual rules form panel - UI only
  src/Components/ADT3DSceneBuilder/ADT3DSceneBuilder.state.ts
  src/Components/ADT3DSceneBuilder/ADT3DSceneBuilder.tsx
  src/Components/ADT3DSceneBuilder/ADT3DSceneBuilder.types.ts
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/BehaviorsForm.tsx
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/Widgets/WidgetBuilders/ValueWidgetBuilder.tsx
  src/Components/ADT3DSceneBuilder/Internal/Elements/ElementForm.tsx
  src/Components/ADT3DSceneBuilder/Internal/LeftPanelBuilderHeader.tsx
  src/Components/ADT3DSceneBuilder/Internal/Shared/PanelForms.styles.ts
  src/Components/ADT3DSceneBuilder/Internal/Shared/SharedFormUtils.tsx
  src/Components/ADT3DSceneBuilder/Internal/VisualRuleForm/Internal/ConditionsList.styles.ts
  src/Components/ADT3DSceneBuilder/Internal/VisualRuleForm/Internal/ConditionsList.tsx
  src/Components/ADT3DSceneBuilder/Internal/VisualRuleForm/Internal/ConditionsList.types.ts
  src/Components/ADT3DSceneBuilder/Internal/VisualRuleForm/Internal/ConditionsMock.ts
  src/Components/ADT3DSceneBuilder/Internal/VisualRuleForm/VisualRuleForm.styles.ts
  src/Components/ADT3DSceneBuilder/Internal/VisualRuleForm/VisualRuleForm.tsx
  src/Components/ADT3DSceneBuilder/Internal/VisualRuleForm/VisualRuleForm.types.ts
  src/Components/SceneBreadcrumb/SceneBreadcrumbFactory.tsx
  src/Models/Constants/Constants.ts
  src/Models/Constants/Enums.ts
  src/Resources/Locales/cs.json
  src/Resources/Locales/de.json
  src/Resources/Locales/en.json
  src/Resources/Locales/es.json
  src/Resources/Locales/fr.json
  src/Resources/Locales/hu.json
  src/Resources/Locales/it.json
  src/Resources/Locales/ja.json
  src/Resources/Locales/ko.json
  src/Resources/Locales/nl.json
  src/Resources/Locales/pl.json
  src/Resources/Locales/pt-pt.json
  src/Resources/Locales/pt.json
  src/Resources/Locales/ru.json
  src/Resources/Locales/sv.json
  src/Resources/Locales/tr.json
  src/Resources/Locales/zh-Hans.json
Labels: enhancement :bulb:, wip 🚧

#714 Added visual rule management in behavior form context and schema updates
  schemas/3DScenesConfiguration/v1.0.0/3DScenesConfiguration.schema.json
  src/Adapters/BlobAdapter.ts
  src/Adapters/BlobAdapterUtility.ts
  src/Adapters/MockAdapter.ts
  src/Models/Classes/ViewerConfigUtility.ts
  src/Models/Context/BehaviorFormContext/BehaviorFormContext.tsx
  src/Models/Context/BehaviorFormContext/BehaviorFormContext.types.ts
  src/Models/Types/Generated/3DScenesConfiguration-v1.0.0.d.ts
Labels: enhancement :bulb:, small change :droplet:

#711 Fixed wrong cached adx connection value returning for the selected adt instance
  src/Adapters/AzureManagementAdapter.ts
  src/Models/Constants/Constants.ts
Labels: bugfix :bug: :white_check_mark:

#719 column picker infinite loop
  src/Components/AdvancedSearch/Internal/AdvancedSearchResultDetailsList/AdvancedSearchResultDetailsList.tsx
Labels: bugfix :bug: :white_check_mark:

#716 Data history widget builder (only authoring experience, not including the view model)
  .storybook/middleware.js
  schemas/3DScenesConfiguration/v1.0.0/3DScenesConfiguration.schema.json
  src/Adapters/__mockData__/TruckAndMachinesConfig.json
  src/Components/ADT3DSceneBuilder/ADT3DSceneBuilder.WidgetsForm.stories.tsx
  src/Components/ADT3DSceneBuilder/ADT3DSceneBuilder.scss
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/Internal/WidgetsTab.tsx
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/Widgets/WidgetBuilders/DataHistoryWidgetBuilder/DataHistoryWidgetBuilder.stories.tsx
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/Widgets/WidgetBuilders/DataHistoryWidgetBuilder/DataHistoryWidgetBuilder.styles.tsx
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/Widgets/WidgetBuilders/DataHistoryWidgetBuilder/DataHistoryWidgetBuilder.tsx
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/Widgets/WidgetBuilders/DataHistoryWidgetBuilder/DataHistoryWidgetBuilder.types.ts
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/Widgets/WidgetBuilders/DataHistoryWidgetBuilder/Internal/TimeSeriesFormCallout.tsx
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/Widgets/WidgetBuilders/DataHistoryWidgetBuilder/Internal/TimeSeriesList.tsx
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/Widgets/WidgetForm/WidgetForm.styles.ts
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/Widgets/WidgetForm/WidgetForm.tsx
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/Widgets/WidgetLibraryDialog/WidgetLibraryDialog.tsx
  src/Components/BehaviorsModal/Internal/Widgets/DataHistoryWidget/DataHistoryWidget.tsx
  src/Components/BehaviorsModal/Internal/Widgets/WidgetsContainer.tsx
  src/Components/CardboardListCallout/CardboardListCallout.styles.ts
  src/Components/CardboardListCallout/CardboardListCallout.tsx
  src/Components/CardboardListCallout/__snapshots__/CardboardListCallout.test.tsx.snap
  src/Models/Classes/3DVConfig.ts
  src/Models/Constants/Constants.ts
  src/Models/Constants/Types.ts
  src/Models/Context/DeeplinkContext/DeeplinkContext.tsx
  src/Models/Services/LocalStorageManager/LocalStorageManager.ts
  src/Models/Types/Generated/3DScenesConfiguration-v1.0.0.d.ts
  src/Pages/ADT3DScenePage/ADT3DScenePage.tsx
  src/Resources/Locales/cs.json
  src/Resources/Locales/de.json
  src/Resources/Locales/en.json
  src/Resources/Locales/es.json
  src/Resources/Locales/fr.json
  src/Resources/Locales/hu.json
  src/Resources/Locales/it.json
  src/Resources/Locales/ja.json
  src/Resources/Locales/ko.json
  src/Resources/Locales/nl.json
  src/Resources/Locales/pl.json
  src/Resources/Locales/pt-pt.json
  src/Resources/Locales/pt.json
  src/Resources/Locales/ru.json
  src/Resources/Locales/sv.json
  src/Resources/Locales/tr.json
  src/Resources/Locales/zh-Hans.json
Labels: enhancement :bulb:, large change :ocean:

#717 Wiring data for Visual rule form
  schemas/3DScenesConfiguration/v1.0.0/3DScenesConfiguration.schema.json
  src/Adapters/BlobAdapterUtility.ts
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/BehaviorsForm.tsx
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/Internal/VisualRulesTab.tsx
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/VisualRules/VisualRules.types.ts
  src/Components/ADT3DSceneBuilder/Internal/Shared/SharedFormUtils.tsx
  src/Components/ADT3DSceneBuilder/Internal/VisualRuleForm/Internal/ConditionsList.tsx
  src/Components/ADT3DSceneBuilder/Internal/VisualRuleForm/Internal/ConditionsList.types.ts
  src/Components/ADT3DSceneBuilder/Internal/VisualRuleForm/Internal/ConditionsMock.ts
  src/Components/ADT3DSceneBuilder/Internal/VisualRuleForm/VisualRuleForm.state.ts
  src/Components/ADT3DSceneBuilder/Internal/VisualRuleForm/VisualRuleForm.styles.ts
  src/Components/ADT3DSceneBuilder/Internal/VisualRuleForm/VisualRuleForm.tsx
  src/Components/ADT3DSceneBuilder/Internal/VisualRuleForm/VisualRuleForm.types.ts
  src/Components/ADT3DSceneBuilder/Internal/VisualRuleForm/VisualRuleFormUtility.ts
  src/Components/ModelledPropertyBuilder/ModelledPropertyBuilder.tsx
  src/Components/ModelledPropertyBuilder/ModelledPropertyBuilder.types.ts
  src/Models/Classes/3DVConfig.ts
  src/Models/Context/BehaviorFormContext/BehaviorFormContext.types.ts
  src/Models/Types/Generated/3DScenesConfiguration-v1.0.0.d.ts
  src/Resources/Locales/cs.json
  src/Resources/Locales/de.json
  src/Resources/Locales/en.json
  src/Resources/Locales/es.json
  src/Resources/Locales/fr.json
  src/Resources/Locales/hu.json
  src/Resources/Locales/it.json
  src/Resources/Locales/ja.json
  src/Resources/Locales/ko.json
  src/Resources/Locales/nl.json
  src/Resources/Locales/pl.json
  src/Resources/Locales/pt-pt.json
  src/Resources/Locales/pt.json
  src/Resources/Locales/ru.json
  src/Resources/Locales/sv.json
  src/Resources/Locales/tr.json
  src/Resources/Locales/zh-Hans.json
Labels: enhancement :bulb:, wip 🚧

#724 [Visual Rules] Adding visual rule list tab
  src/Adapters/__mockData__/TruckAndMachinesConfig.json
  src/Components/ADT3DSceneBuilder/ADT3DSceneBuilder.VisualRuleList.stories.tsx
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/BehaviorsForm.tsx
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/Internal/VisualRulesTab.tsx
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/VisualRules/VisualRuleList.tsx
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/VisualRules/VisualRules.types.ts
  src/Resources/Locales/cs.json
  src/Resources/Locales/de.json
  src/Resources/Locales/en.json
  src/Resources/Locales/es.json
  src/Resources/Locales/fr.json
  src/Resources/Locales/hu.json
  src/Resources/Locales/it.json
  src/Resources/Locales/ja.json
  src/Resources/Locales/ko.json
  src/Resources/Locales/nl.json
  src/Resources/Locales/pl.json
  src/Resources/Locales/pt-pt.json
  src/Resources/Locales/pt.json
  src/Resources/Locales/ru.json
  src/Resources/Locales/sv.json
  src/Resources/Locales/tr.json
  src/Resources/Locales/zh-Hans.json
Labels: enhancement :bulb:

#723 [Data history] Data history widget viewer
  package-lock.json
  package.json
  schemas/3DScenesConfiguration/v1.0.0/3DScenesConfiguration.schema.json
  src/Adapters/ADXAdapter.ts
  src/Adapters/AzureManagementAdapter.ts
  src/Adapters/MockAdapter.ts
  src/Adapters/__mockData__/TruckAndMachinesConfig.json
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/Widgets/WidgetBuilders/DataHistoryWidgetBuilder/DataHistoryWidgetBuilder.tsx
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/Widgets/WidgetBuilders/DataHistoryWidgetBuilder/DataHistoryWidgetBuilder.types.ts
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/Widgets/WidgetBuilders/DataHistoryWidgetBuilder/Internal/TimeSeriesFormCallout.tsx
  src/Components/ADT3DViewer/ADT3DViewer.tsx
  src/Components/BehaviorsModal/BehaviorsModal.tsx
  src/Components/BehaviorsModal/Internal/Widgets/DataHistoryWidget/DataHistoryWidget.stories.tsx
  src/Components/BehaviorsModal/Internal/Widgets/DataHistoryWidget/DataHistoryWidget.styles.ts
  src/Components/BehaviorsModal/Internal/Widgets/DataHistoryWidget/DataHistoryWidget.tsx
  src/Components/BehaviorsModal/Internal/Widgets/DataHistoryWidget/DataHistoryWidget.types.ts
  src/Components/BehaviorsModal/Internal/Widgets/WidgetsContainer.styles.ts
  src/Components/BehaviorsModal/Internal/Widgets/WidgetsContainer.tsx
  src/Components/BehaviorsModal/__mockData__/BehaviorsModalMockData.json
  src/Components/HighChartsWrapper/HighChartsWrapper.stories.tsx
  src/Components/HighChartsWrapper/HighChartsWrapper.styles.ts
  src/Components/HighChartsWrapper/HighChartsWrapper.tsx
  src/Components/HighChartsWrapper/HighChartsWrapper.types.ts
  src/Models/Classes/3DVConfig.ts
  src/Models/Classes/AdapterDataClasses/ADXTimeSeriesData.ts
  src/Models/Constants/Constants.ts
  src/Models/Constants/Enums.ts
  src/Models/Constants/Interfaces.ts
  src/Models/Constants/Types.ts
  src/Models/Hooks/useTimeSeriesData.ts
  src/Models/Services/Utils.ts
  src/Models/Types/Generated/3DScenesConfiguration-v1.0.0.d.ts
  src/Pages/ADTTwinsPage/ADTTwinsPage.tsx
  src/Resources/Locales/cs.json
  src/Resources/Locales/de.json
  src/Resources/Locales/en.json
  src/Resources/Locales/es.json
  src/Resources/Locales/fr.json
  src/Resources/Locales/hu.json
  src/Resources/Locales/it.json
  src/Resources/Locales/ja.json
  src/Resources/Locales/ko.json
  src/Resources/Locales/nl.json
  src/Resources/Locales/pl.json
  src/Resources/Locales/pt-pt.json
  src/Resources/Locales/pt.json
  src/Resources/Locales/ru.json
  src/Resources/Locales/sv.json
  src/Resources/Locales/tr.json
  src/Resources/Locales/zh-Hans.json
Labels: enhancement :bulb:, large change :ocean:

#738 CardboardList: Add styling for selected list items
  src/Components/CardboardList/CardboardList.stories.tsx
  src/Components/CardboardList/CardboardList.types.ts
  src/Components/CardboardList/CardboardListItem.stories.tsx
  src/Components/CardboardList/CardboardListItem.styles.ts
  src/Components/CardboardList/CardboardListItem.tsx
Labels: small change :droplet:, styling :art:

#732 [Data History]: Title changes in widget and quick time dropdown
  src/Adapters/ADXAdapter.ts
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/Widgets/WidgetBuilders/DataHistoryWidgetBuilder/DataHistoryWidgetBuilder.tsx
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/Widgets/WidgetBuilders/DataHistoryWidgetBuilder/DataHistoryWidgetBuilder.types.ts
  src/Components/BehaviorsModal/Internal/Widgets/DataHistoryWidget/DataHistoryWidget.styles.ts
  src/Components/BehaviorsModal/Internal/Widgets/DataHistoryWidget/DataHistoryWidget.tsx
  src/Components/BehaviorsModal/Internal/Widgets/DataHistoryWidget/DataHistoryWidget.types.ts
  src/Components/HighChartsWrapper/HighChartsWrapper.stories.tsx
  src/Components/HighChartsWrapper/HighChartsWrapper.styles.ts
  src/Components/HighChartsWrapper/HighChartsWrapper.tsx
  src/Components/HighChartsWrapper/HighChartsWrapper.types.ts
  src/Components/QuickTimesDropdown/QuickTimesDropdown.stories.tsx
  src/Components/QuickTimesDropdown/QuickTimesDropdown.styles.ts
  src/Components/QuickTimesDropdown/QuickTimesDropdown.tsx
  src/Components/QuickTimesDropdown/QuickTimesDropdown.types.ts
  src/Models/Hooks/useTimeSeriesData.ts
  src/Models/Services/Utils.ts
  src/Resources/Locales/cs.json
  src/Resources/Locales/de.json
  src/Resources/Locales/en.json
  src/Resources/Locales/es.json
  src/Resources/Locales/fr.json
  src/Resources/Locales/hu.json
  src/Resources/Locales/it.json
  src/Resources/Locales/ja.json
  src/Resources/Locales/ko.json
  src/Resources/Locales/nl.json
  src/Resources/Locales/pl.json
  src/Resources/Locales/pt-pt.json
  src/Resources/Locales/pt.json
  src/Resources/Locales/ru.json
  src/Resources/Locales/sv.json
  src/Resources/Locales/tr.json
  src/Resources/Locales/zh-Hans.json
Labels: enhancement :bulb:, small change :droplet:, refactor :hammer:

#742 [Data history]: Fixed data grouping for large data set
  src/Components/HighChartsWrapper/HighChartsWrapper.mock.ts
  src/Components/HighChartsWrapper/HighChartsWrapper.stories.tsx
  src/Components/HighChartsWrapper/HighChartsWrapper.tsx
  src/Components/HighChartsWrapper/HighChartsWrapper.types.ts
Labels: bugfix :bug: :white_check_mark:

#727 Conditions flyout form
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/BehaviorsForm.tsx
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/VisualRules/VisualRuleList.tsx
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/VisualRules/VisualRules.types.ts
  src/Components/ADT3DSceneBuilder/Internal/VisualRuleForm/Internal/ConditionsCallout/ActionItem.styles.ts
  src/Components/ADT3DSceneBuilder/Internal/VisualRuleForm/Internal/ConditionsCallout/ActionItem.tsx
  src/Components/ADT3DSceneBuilder/Internal/VisualRuleForm/Internal/ConditionsCallout/ActionItem.types.ts
  src/Components/ADT3DSceneBuilder/Internal/VisualRuleForm/Internal/ConditionsCallout/BoundaryInput.styles.ts
  src/Components/ADT3DSceneBuilder/Internal/VisualRuleForm/Internal/ConditionsCallout/BoundaryInput.tsx
  src/Components/ADT3DSceneBuilder/Internal/VisualRuleForm/Internal/ConditionsCallout/BoundaryInput.types.ts
  src/Components/ADT3DSceneBuilder/Internal/VisualRuleForm/Internal/ConditionsCallout/ConditionCalloutUtility.ts
  src/Components/ADT3DSceneBuilder/Internal/VisualRuleForm/Internal/ConditionsCallout/ConditionSummary.styles.ts
  src/Components/ADT3DSceneBuilder/Internal/VisualRuleForm/Internal/ConditionsCallout/ConditionSummary.tsx
  src/Components/ADT3DSceneBuilder/Internal/VisualRuleForm/Internal/ConditionsCallout/ConditionSummary.types.ts
  src/Components/ADT3DSceneBuilder/Internal/VisualRuleForm/Internal/ConditionsCallout/ConditionsCallout.state.ts
  src/Components/ADT3DSceneBuilder/Internal/VisualRuleForm/Internal/ConditionsCallout/ConditionsCallout.stories.tsx
  src/Components/ADT3DSceneBuilder/Internal/VisualRuleForm/Internal/ConditionsCallout/ConditionsCallout.styles.ts
  src/Components/ADT3DSceneBuilder/Internal/VisualRuleForm/Internal/ConditionsCallout/ConditionsCallout.tsx
  src/Components/ADT3DSceneBuilder/Internal/VisualRuleForm/Internal/ConditionsCallout/ConditionsCallout.types.ts
  src/Components/ADT3DSceneBuilder/Internal/VisualRuleForm/Internal/ConditionsList.styles.ts
  src/Components/ADT3DSceneBuilder/Internal/VisualRuleForm/Internal/ConditionsList.tsx
  src/Components/ADT3DSceneBuilder/Internal/VisualRuleForm/Internal/ConditionsList.types.ts
  src/Components/ADT3DSceneBuilder/Internal/VisualRuleForm/VisualRuleForm.state.ts
  src/Components/ADT3DSceneBuilder/Internal/VisualRuleForm/VisualRuleForm.tsx
  src/Components/ADT3DSceneBuilder/Internal/VisualRuleForm/VisualRuleFormUtility.ts
  src/Components/BehaviorsModal/Internal/BehaviorSection/BehaviorSection.tsx
  src/Components/CardboardMultiSelect/CardboardMultiSelect.stories.tsx
  src/Components/CardboardMultiSelect/CardboardMultiSelect.styles.ts
  src/Components/CardboardMultiSelect/CardboardMultiSelect.tsx
  src/Components/CardboardMultiSelect/CardboardMultiSelect.types.ts
  src/Components/SceneBreadcrumb/SceneBreadcrumbFactory.tsx
  src/Models/Classes/3DVConfig.ts
  src/Resources/Locales/cs.json
  src/Resources/Locales/de.json
  src/Resources/Locales/en.json
  src/Resources/Locales/es.json
  src/Resources/Locales/fr.json
  src/Resources/Locales/hu.json
  src/Resources/Locales/it.json
  src/Resources/Locales/ja.json
  src/Resources/Locales/ko.json
  src/Resources/Locales/nl.json
  src/Resources/Locales/pl.json
  src/Resources/Locales/pt-pt.json
  src/Resources/Locales/pt.json
  src/Resources/Locales/ru.json
  src/Resources/Locales/sv.json
  src/Resources/Locales/tr.json
  src/Resources/Locales/zh-Hans.json
  src/Resources/Styles/ReactSelect.styles.ts
Labels: enhancement :bulb:

#740 CardboardList: Add id for list item
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/Internal/TwinsTab.tsx
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/Widgets/WidgetBuilders/DataHistoryWidgetBuilder/Internal/TimeSeriesList.tsx
  src/Components/CardboardList/CardboardList.types.ts
  src/Components/CardboardList/CardboardListItem.tsx
Labels: small change :droplet:, refactor :hammer:

#743 Added translations back for quick time dropdown component
  src/Resources/Locales/cs.json
  src/Resources/Locales/de.json
  src/Resources/Locales/en.json
  src/Resources/Locales/es.json
  src/Resources/Locales/fr.json
  src/Resources/Locales/hu.json
  src/Resources/Locales/it.json
  src/Resources/Locales/ja.json
  src/Resources/Locales/ko.json
  src/Resources/Locales/nl.json
  src/Resources/Locales/pl.json
  src/Resources/Locales/pt-pt.json
  src/Resources/Locales/pt.json
  src/Resources/Locales/ru.json
  src/Resources/Locales/sv.json
  src/Resources/Locales/tr.json
  src/Resources/Locales/zh-Hans.json
Labels: bugfix :bug: :white_check_mark:

#739 OAT: Restyling Models list
  src/Components/HeaderControlButton/HeaderControlButton.styles.ts
  src/Components/HeaderControlButton/HeaderControlButton.tsx
  src/Components/OATGraphViewer/Internal/GraphLegend/GraphLegend.tsx
  src/Components/OATGraphViewer/Internal/GraphViewerControls/GraphViewerControls.stories.tsx
  src/Components/OATGraphViewer/Internal/GraphViewerControls/GraphViewerControls.styles.ts
  src/Components/OATGraphViewer/Internal/GraphViewerControls/GraphViewerControls.tsx
  src/Components/OATGraphViewer/Internal/GraphViewerControls/GraphViewerControls.types.ts
  src/Components/OATGraphViewer/Internal/OATGraphCustomNode.tsx
  src/Components/OATGraphViewer/OATGraphViewer.styles.tsx
  src/Components/OATGraphViewer/OATGraphViewer.tsx
  src/Components/OATGraphViewer/OATGraphViewer.types.ts
  src/Components/OATHeader/OATHeader.styles.ts
  src/Components/OATHeader/OATHeader.tsx
  src/Components/OATHeader/internal/ManageOntologyModal/ManageOntologyModal.tsx
  src/Components/OATModelList/OATModelList.stories.tsx
  src/Components/OATModelList/OATModelList.styles.tsx
  src/Components/OATModelList/OATModelList.tsx
  src/Components/OATModelList/OATModelList.types.ts
  src/Components/OATPropertyEditor/OATPropertyEditor.tsx
  src/Models/Constants/OatStyleConstants.ts
  src/Models/Context/OatGraphContext/OatGraphContext.tsx
  src/Models/Context/OatGraphContext/OatGraphContext.types.ts
  src/Models/Context/OatPageContext/OatPageContext.mock.ts
  src/Models/Context/OatPageContext/OatPageContext.stories.tsx
  src/Models/Context/OatPageContext/OatPageContext.tsx
  src/Models/Context/OatPageContext/OatPageContext.types.ts
  src/Models/Context/OatPageContext/OatPageContextUtils.ts
  src/Models/Services/OatUtils.ts
  src/Pages/OATEditorPage/OATEditorPage.interactions.stories.tsx
  src/Pages/OATEditorPage/OATEditorPage.styles.tsx
  src/Pages/OATEditorPage/OATEditorPage.tsx
  src/Resources/Locales/cs.json
  src/Resources/Locales/de.json
  src/Resources/Locales/en.json
  src/Resources/Locales/es.json
  src/Resources/Locales/fr.json
  src/Resources/Locales/hu.json
  src/Resources/Locales/it.json
  src/Resources/Locales/ja.json
  src/Resources/Locales/ko.json
  src/Resources/Locales/nl.json
  src/Resources/Locales/pl.json
  src/Resources/Locales/pt-pt.json
  src/Resources/Locales/pt.json
  src/Resources/Locales/ru.json
  src/Resources/Locales/sv.json
  src/Resources/Locales/tr.json
  src/Resources/Locales/zh-Hans.json
Labels: large change :ocean:, refactor :hammer:

#744 More translation fix and mock data changes
  src/Adapters/MockAdapter.ts
  src/Adapters/__mockData__/3DScenesConfiguration.json
  src/Adapters/__mockData__/DemoEnvsConfig.json
  src/Components/HighChartsWrapper/HighChartsWrapper.tsx
  src/Pages/ADT3DScenePage/ADT3DScenePage.stories.tsx
  src/Resources/Locales/cs.json
  src/Resources/Locales/de.json
  src/Resources/Locales/en.json
  src/Resources/Locales/es.json
  src/Resources/Locales/fr.json
  src/Resources/Locales/hu.json
  src/Resources/Locales/it.json
  src/Resources/Locales/ja.json
  src/Resources/Locales/ko.json
  src/Resources/Locales/nl.json
  src/Resources/Locales/pl.json
  src/Resources/Locales/pt-pt.json
  src/Resources/Locales/pt.json
  src/Resources/Locales/ru.json
  src/Resources/Locales/sv.json
  src/Resources/Locales/tr.json
  src/Resources/Locales/zh-Hans.json
Labels: bugfix :bug: :white_check_mark:

#748 Design review fixes - visual rules
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/Internal/VisualRulesTab.tsx
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/VisualRules/VisualRuleList.tsx
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/VisualRules/VisualRules.types.ts
  src/Components/ADT3DSceneBuilder/Internal/VisualRuleForm/Internal/ConditionsCallout/ActionItem.tsx
  src/Components/ADT3DSceneBuilder/Internal/VisualRuleForm/Internal/ConditionsCallout/ConditionSummary.styles.ts
  src/Components/ADT3DSceneBuilder/Internal/VisualRuleForm/Internal/ConditionsCallout/ConditionSummary.tsx
  src/Components/ADT3DSceneBuilder/Internal/VisualRuleForm/Internal/ConditionsCallout/ConditionsCallout.styles.ts
  src/Components/ADT3DSceneBuilder/Internal/VisualRuleForm/Internal/ConditionsList.styles.ts
  src/Components/ADT3DSceneBuilder/Internal/VisualRuleForm/Internal/ConditionsList.tsx
  src/Components/ADT3DSceneBuilder/Internal/VisualRuleForm/Internal/ConditionsList.types.ts
  src/Components/ADT3DSceneBuilder/Internal/VisualRuleForm/VisualRuleForm.tsx
  src/Components/ADT3DSceneBuilder/Internal/VisualRuleForm/VisualRuleFormUtility.ts
  src/Components/CardboardList/CardboardListItem.styles.ts
  src/Resources/Locales/cs.json
  src/Resources/Locales/de.json
  src/Resources/Locales/en.json
  src/Resources/Locales/es.json
  src/Resources/Locales/fr.json
  src/Resources/Locales/hu.json
  src/Resources/Locales/it.json
  src/Resources/Locales/ja.json
  src/Resources/Locales/ko.json
  src/Resources/Locales/nl.json
  src/Resources/Locales/pl.json
  src/Resources/Locales/pt-pt.json
  src/Resources/Locales/pt.json
  src/Resources/Locales/ru.json
  src/Resources/Locales/sv.json
  src/Resources/Locales/tr.json
  src/Resources/Locales/zh-Hans.json
Labels: small change :droplet:, styling :art:
