Repository microsoft/iot-cardboard-js, pull requests merged in 2023-02, with the labels that each got.

#842 [Data History Explorer]: Error Handling
  src/Adapters/AzureManagementAdapter.ts
  src/Components/BehaviorsModal/Internal/Widgets/DataHistoryWidget/DataHistoryWidget.stories.tsx
  src/Components/BehaviorsModal/Internal/Widgets/DataHistoryWidget/DataHistoryWidget.styles.ts
  src/Components/BehaviorsModal/Internal/Widgets/DataHistoryWidget/DataHistoryWidget.tsx
  src/Components/BehaviorsModal/Internal/Widgets/DataHistoryWidget/DataHistoryWidget.types.ts
  src/Components/CardboardList/CardboardList.types.ts
  src/Components/CardboardList/CardboardListItem.styles.ts
  src/Components/CardboardList/CardboardListItem.tsx
  src/Components/CardboardListCallout/__snapshots__/CardboardListCallout.test.tsx.snap
  src/Components/DataHistoryErrorHandlingWrapper/DataHistoryErrorHandlingWrapper.stories.tsx
  src/Components/DataHistoryErrorHandlingWrapper/DataHistoryErrorHandlingWrapper.styles.ts
  src/Components/DataHistoryErrorHandlingWrapper/DataHistoryErrorHandlingWrapper.tsx
  src/Components/DataHistoryErrorHandlingWrapper/DataHistoryErrorHandlingWrapper.types.ts
  src/Components/DataHistoryExplorer/DataHistoryExplorer.styles.ts
  src/Components/DataHistoryExplorer/DataHistoryExplorer.tsx
  src/Components/DataHistoryExplorer/DataHistoryExplorer.types.ts
  src/Components/DataHistoryExplorer/Internal/TimeSeriesBuilder/TimeSeriesBuilder.tsx
  src/Components/DataHistoryExplorer/Internal/TimeSeriesBuilder/TimeSeriesBuilder.types.ts
  src/Components/DataHistoryExplorer/Internal/TimeSeriesViewer/Internal/TimeSeriesChart/TimeSeriesChart.tsx
  src/Components/DataHistoryExplorer/Internal/TimeSeriesViewer/Internal/TimeSeriesTable/TimeSeriesTable.tsx
  src/Components/DataHistoryExplorer/Internal/TimeSeriesViewer/TimeSeriesViewer.tsx
  src/Components/DataHistoryExplorer/Internal/TimeSeriesViewer/TimeSeriesViewer.types.ts
  src/Components/DataHistoryExplorer/Internal/TimeSeriesViewer/TimeSeriesViewerError.stories.tsx
  src/Components/DataHistoryExplorerModal/DataHistoryExplorerModal.stories.tsx
  src/Components/HighChartsWrapper/HighChartsWrapper.tsx
  src/Components/HighChartsWrapper/HighChartsWrapper.types.ts
  src/Components/IllustrationMessage/IllustrationMessage.types.tsx
  src/Models/Classes/Errors.ts
  src/Models/Constants/Enums.ts
  src/Models/Hooks/useTimeSeriesData.ts
  src/Resources/Locales/cs.json
  src/Resources/Locales/de.json
  src/Resources/Locales/en.json
  src/Resources/Locales/es.json
  src/Resources/Locales/fr.json
  src/Resources/Locales/hu.json
  src/Resources/Locales/it.json
  src/Resources/Locales/ja.json
  src/Resources/Locales/ko.json
  src/Resources/Locales/nl.json
  src/Resources/Locales/pl.json
  src/Resources/Locales/pt-pt.json
  src/Resources/Locales/pt.json
  src/Resources/Locales/ru.json
  src/Resources/Locales/sv.json
  src/Resources/Locales/tr.json
  src/Resources/Locales/zh-Hans.json
  src/Resources/Static/searchError.svg
Labels: enhancement :bulb:

#853 OAT: Refactor import/export logic to public utils file
  src/Components/OATHeader/OATHeader.tsx
  src/Components/OATPropertyEditor/Internal/JSONEditor.tsx
  src/Models/Context/OatPageContext/OatPageContext.mock.ts
  src/Models/Services/OatPublicUtils.ts
  src/Models/Services/OatUtils.ts
  src/Models/Services/Utils.ts
  src/Models/Services/__tests__/OatPublicUtils.test.ts
  src/Models/Services/index.ts
  src/Resources/Locales/cs.json
  src/Resources/Locales/de.json
  src/Resources/Locales/en.json
  src/Resources/Locales/es.json
  src/Resources/Locales/fr.json
  src/Resources/Locales/hu.json
  src/Resources/Locales/it.json
  src/Resources/Locales/ja.json
  src/Resources/Locales/ko.json
  src/Resources/Locales/nl.json
  src/Resources/Locales/pl.json
  src/Resources/Locales/pt-pt.json
  src/Resources/Locales/pt.json
  src/Resources/Locales/ru.json
  src/Resources/Locales/sv.json
  src/Resources/Locales/tr.json
  src/Resources/Locales/zh-Hans.json
Labels: small change :droplet:, refactor :hammer:

#859 OAT: Allow uploads of non-json files & fixing co-type handling of relationships
  src/Components/OATGraphViewer/OATGraphViewer.tsx
  src/Components/OATHeader/OATHeader.styles.ts
  src/Components/OATHeader/OATHeader.tsx
  src/Components/OATHeader/OATHeader.types.ts
  src/Models/Classes/DTDL.ts
  src/Models/Context/OatPageContext/OatPageContext.mock.ts
  src/Models/Context/OatPageContext/OatPageContextUtils.ts
  src/Models/Services/DtdlUtils.ts
  src/Models/Services/OatPublicUtils.ts
  src/Models/Services/Utils.ts
  src/Models/Services/__tests__/OatPublicUtils.test.ts
  src/Resources/Locales/cs.json
  src/Resources/Locales/de.json
  src/Resources/Locales/en.json
  src/Resources/Locales/es.json
  src/Resources/Locales/fr.json
  src/Resources/Locales/hu.json
  src/Resources/Locales/it.json
  src/Resources/Locales/ja.json
  src/Resources/Locales/ko.json
  src/Resources/Locales/nl.json
  src/Resources/Locales/pl.json
  src/Resources/Locales/pt-pt.json
  src/Resources/Locales/pt.json
  src/Resources/Locales/ru.json
  src/Resources/Locales/sv.json
  src/Resources/Locales/tr.json
  src/Resources/Locales/zh-Hans.json
Labels: bugfix :bug: :white_check_mark:, small change :droplet:

#861 OAT: Add preview badge for V3 models
  src/Components/OATPropertyEditor/Editor.styles.ts
  src/Components/OATPropertyEditor/Editor.tsx
  src/Components/OATPropertyEditor/Editor.types.ts
  src/Components/OATPropertyEditor/Internal/PreviewLabel/PreviewLabel.stories.tsx
  src/Components/OATPropertyEditor/Internal/PreviewLabel/PreviewLabel.styles.ts
  src/Components/OATPropertyEditor/Internal/PreviewLabel/PreviewLabel.tsx
  src/Components/OATPropertyEditor/Internal/PreviewLabel/PreviewLabel.types.ts
  src/Components/OATPropertyEditor/OATPropertyEditor.stories.tsx
  src/Models/Services/DtdlUtils.ts
  src/Resources/Locales/cs.json
  src/Resources/Locales/de.json
  src/Resources/Locales/en.json
  src/Resources/Locales/es.json
  src/Resources/Locales/fr.json
  src/Resources/Locales/hu.json
  src/Resources/Locales/it.json
  src/Resources/Locales/ja.json
  src/Resources/Locales/ko.json
  src/Resources/Locales/nl.json
  src/Resources/Locales/pl.json
  src/Resources/Locales/pt-pt.json
  src/Resources/Locales/pt.json
  src/Resources/Locales/ru.json
  src/Resources/Locales/sv.json
  src/Resources/Locales/tr.json
  src/Resources/Locales/zh-Hans.json
Labels: small change :droplet:

#862 OAT: Add version picker to details modal
  .eslintrc.json
  src/Components/OATPropertyEditor/Internal/FormRootModelDetails/Internal/FormRootModelDetailsContent/PropertyDetailsEditorModalContent.tsx
  src/Models/Classes/DTDL.ts
  src/Models/Context/OatPageContext/OatPageContext.mock.ts
  src/Models/Services/DtdlUtils.ts
  src/Models/Services/__tests__/DtdlUtils.test.ts
Labels: small change :droplet:

#860 Added CORS enabled for ADT adapter
  .storybook/middleware.js
  src/Adapters/ADT3DSceneAdapter.ts
  src/Adapters/ADTAdapter.ts
  src/Adapters/ADTDataHistoryAdapter.ts
  src/Models/Constants/Constants.ts
  src/Models/Services/Utils.ts
Labels: enhancement :bulb:, small change :droplet:

#863 OAT: Disable adding arrays for V2 models
  src/Components/OATPropertyEditor/Editor.tsx
  src/Components/OATPropertyEditor/Internal/EditorPropertiesTab/EditorPropertiesTab.tsx
  src/Components/OATPropertyEditor/Internal/FormRootModelDetails/Internal/FormRootModelDetailsContent/PropertyDetailsEditorModalContent.tsx
  src/Components/OATPropertyEditor/Internal/PropertyList/Internal/PropertyListItem/Internal/PropertyListItemChildHost/Internal/PropertyListItemArrayChild/PropertyListItemArrayChild.tsx
  src/Components/OATPropertyEditor/Internal/PropertyList/Internal/PropertyListItem/Internal/PropertyListItemChildHost/Internal/PropertyListItemArrayChild/PropertyListItemArrayChild.types.ts
  src/Components/OATPropertyEditor/Internal/PropertyList/Internal/PropertyListItem/Internal/PropertyListItemChildHost/Internal/PropertyListItemMapChild/PropertyListItemMapChild.tsx
  src/Components/OATPropertyEditor/Internal/PropertyList/Internal/PropertyListItem/Internal/PropertyListItemChildHost/Internal/PropertyListItemMapChild/PropertyListItemMapChild.types.ts
  src/Components/OATPropertyEditor/Internal/PropertyList/Internal/PropertyListItem/Internal/PropertyListItemChildHost/Internal/PropertyListItemObjectChild/PropertyListItemObjectChild.tsx
  src/Components/OATPropertyEditor/Internal/PropertyList/Internal/PropertyListItem/Internal/PropertyListItemChildHost/Internal/PropertyListItemObjectChild/PropertyListItemObjectChild.types.ts
  src/Components/OATPropertyEditor/Internal/PropertyList/Internal/PropertyListItem/Internal/PropertyListItemChildHost/PropertyListItemChildHost.tsx
  src/Components/OATPropertyEditor/Internal/PropertyList/Internal/PropertyListItem/Internal/PropertyListItemChildHost/PropertyListItemChildHost.types.ts
  src/Components/OATPropertyEditor/Internal/PropertyList/Internal/PropertyListItem/PropertyListItem.stories.tsx
  src/Components/OATPropertyEditor/Internal/PropertyList/Internal/PropertyListItem/PropertyListItem.tsx
  src/Components/OATPropertyEditor/Internal/PropertyList/Internal/PropertyListItem/PropertyListItem.types.ts
  src/Components/OATPropertyEditor/Internal/PropertyList/PropertyList.tsx
  src/Components/OATPropertyEditor/Internal/PropertyTypePicker/PropertyTypePicker.tsx
  src/Components/OATPropertyEditor/Internal/PropertyTypePicker/PropertyTypePicker.types.ts
  src/Models/Constants/OatConstants.tsx
  src/Models/Constants/dtdlInterfaces.ts
  src/Models/Services/DtdlUtils.ts
  src/Models/Services/__tests__/DtdlUtils.test.ts
  src/Pages/OATEditorPage/OATEditorPage.stories.local.tsx
  src/Resources/Locales/cs.json
  src/Resources/Locales/de.json
  src/Resources/Locales/en.json
  src/Resources/Locales/es.json
  src/Resources/Locales/fr.json
  src/Resources/Locales/hu.json
  src/Resources/Locales/it.json
  src/Resources/Locales/ja.json
  src/Resources/Locales/ko.json
  src/Resources/Locales/nl.json
  src/Resources/Locales/pl.json
  src/Resources/Locales/pt-pt.json
  src/Resources/Locales/pt.json
  src/Resources/Locales/ru.json
  src/Resources/Locales/sv.json
  src/Resources/Locales/tr.json
  src/Resources/Locales/zh-Hans.json
Labels: enhancement :bulb:, small change :droplet:

#864 OAT: Add upgrade button for DTDL v3
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/Behaviors.tsx
  src/Components/ADT3DSceneBuilder/Internal/ConfirmDeleteDialog/ConfirmDeleteDialog.tsx
  src/Components/ADT3DSceneBuilder/Internal/Elements/Elements.tsx
  src/Components/ADT3DSceneBuilder/Internal/SceneLayers/SceneLayers.tsx
  src/Components/OATConfirmDialog/OATConfirmDialog.tsx
  src/Components/OATPropertyEditor/Editor.styles.ts
  src/Components/OATPropertyEditor/Editor.tsx
  src/Components/OATPropertyEditor/Editor.types.ts
  src/Components/OATPropertyEditor/Internal/Version3PreviewLabel/Version3PreviewLabel.stories.tsx
  src/Components/OATPropertyEditor/Internal/Version3PreviewLabel/Version3PreviewLabel.styles.ts
  src/Components/OATPropertyEditor/Internal/Version3PreviewLabel/Version3PreviewLabel.tsx
  src/Components/OATPropertyEditor/Internal/Version3PreviewLabel/Version3PreviewLabel.types.ts
  src/Components/OATPropertyEditor/Internal/Version3UpgradeButton/Version3UpgradeButton.stories.tsx
  src/Components/OATPropertyEditor/Internal/Version3UpgradeButton/Version3UpgradeButton.styles.ts
  src/Components/OATPropertyEditor/Internal/Version3UpgradeButton/Version3UpgradeButton.tsx
  src/Components/OATPropertyEditor/Internal/Version3UpgradeButton/Version3UpgradeButton.types.ts
  src/Models/Constants/Types.ts
  src/Pages/OATEditorPage/Internal/OATConfirmDeleteModal.tsx
  src/Pages/OATEditorPage/OATEditorPage.tsx
  src/Pages/OATEditorPage/OATEditorPage.types.ts
  src/Resources/Locales/cs.json
  src/Resources/Locales/de.json
  src/Resources/Locales/en.json
  src/Resources/Locales/es.json
  src/Resources/Locales/fr.json
  src/Resources/Locales/hu.json
  src/Resources/Locales/it.json
  src/Resources/Locales/ja.json
  src/Resources/Locales/ko.json
  src/Resources/Locales/nl.json
  src/Resources/Locales/pl.json
  src/Resources/Locales/pt-pt.json
  src/Resources/Locales/pt.json
  src/Resources/Locales/ru.json
  src/Resources/Locales/sv.json
  src/Resources/Locales/tr.json
  src/Resources/Locales/zh-Hans.json
Labels: enhancement :bulb:, small change :droplet:

#865 OAT: Update relationship multiplicity logic by version
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/Behaviors.tsx
  src/Components/OATConfirmDialog/OATConfirmDialog.stories.tsx
  src/Components/OATConfirmDialog/OATConfirmDialog.tsx
  src/Components/OATPropertyEditor/Editor.tsx
  src/Components/OATPropertyEditor/Internal/FormRootModelDetails/Internal/FormRootModelDetailsContent/PropertyDetailsEditorModalContent.styles.ts
  src/Components/OATPropertyEditor/Internal/FormRootModelDetails/Internal/FormRootModelDetailsContent/PropertyDetailsEditorModalContent.tsx
  src/Components/OATPropertyEditor/Internal/FormRootModelDetails/Internal/FormRootModelDetailsContent/PropertyDetailsEditorModalContent.types.ts
  src/Components/OATPropertyEditor/Internal/PropertiesModelSummary.tsx
  src/Components/OATPropertyEditor/Internal/Version3UpgradeButton/Version3UpgradeButton.stories.tsx
  src/Components/OATPropertyEditor/Internal/Version3UpgradeButton/Version3UpgradeButton.tsx
  src/Components/OATPropertyEditor/Internal/Version3UpgradeButton/Version3UpgradeButton.types.ts
  src/Models/Constants/dtdlInterfaces.ts
  src/Models/Context/OatPageContext/OatPageContext.mock.ts
  src/Models/Context/OatPageContext/OatPageContext.tsx
  src/Models/Context/OatPageContext/OatPageContext.types.ts
  src/Models/Services/DtdlUtils.ts
  src/Models/Services/OatUtils.ts
  src/Models/Services/__tests__/DtdlUtils.test.ts
  src/Pages/OATEditorPage/OATEditorPage.types.ts
  src/Resources/Locales/cs.json
  src/Resources/Locales/de.json
  src/Resources/Locales/en.json
  src/Resources/Locales/es.json
  src/Resources/Locales/fr.json
  src/Resources/Locales/hu.json
  src/Resources/Locales/it.json
  src/Resources/Locales/ja.json
  src/Resources/Locales/ko.json
  src/Resources/Locales/nl.json
  src/Resources/Locales/pl.json
  src/Resources/Locales/pt-pt.json
  src/Resources/Locales/pt.json
  src/Resources/Locales/ru.json
  src/Resources/Locales/sv.json
  src/Resources/Locales/tr.json
  src/Resources/Locales/zh-Hans.json
Labels: enhancement :bulb:, small change :droplet:

#850 [Data History Explorer]: Property Inspector Integration
  src/Adapters/ADT3DSceneAdapter.ts
  src/Adapters/ADTDataHistoryAdapter.ts
  src/Adapters/index.ts
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/Widgets/WidgetLibraryDialog/WidgetLibraryDialog.tsx
  src/Components/ADT3DViewer/ADT3DViewer.tsx
  src/Components/AdvancedSearch/AdvancedSearch.types.ts
  src/Components/BehaviorsModal/BehaviorsModal.tsx
  src/Components/CardboardList/CardboardListItem.styles.ts
  src/Components/DataHistoryExplorer/DataHistoryExplorer.tsx
  src/Components/DataHistoryExplorer/DataHistoryExplorer.types.ts
  src/Components/DataHistoryExplorer/Internal/TimeSeriesBuilder/TimeSeriesBuilder.tsx
  src/Components/DataHistoryExplorer/Internal/TimeSeriesTwinCallout/TimeSeriesTwinCallout.types.ts
  src/Components/DataHistoryExplorer/Internal/TimeSeriesViewer/TimeSeriesViewer.tsx
  src/Components/DataHistoryExplorerModal/DataHistoryExplorerModal.types.ts
  src/Components/DataHistoryExplorerModal/DataHistoryExplorerModalControl/DataHistoryExplorerModalControl.stories.tsx
  src/Components/DataHistoryExplorerModal/DataHistoryExplorerModalControl/DataHistoryExplorerModalControl.styles.ts
  src/Components/DataHistoryExplorerModal/DataHistoryExplorerModalControl/DataHistoryExplorerModalControl.tsx
  src/Components/DataHistoryExplorerModal/DataHistoryExplorerModalControl/DataHistoryExplorerModalControl.types.ts
  src/Components/PropertyInspector/PropertyInspector.stories.local.tsx
  src/Components/PropertyInspector/PropertyInspector.stories.tsx
  src/Components/PropertyInspector/PropertyInspector.tsx
  src/Components/PropertyInspector/PropertyInspectorCallout/PropertyInspectorCallout.stories.tsx
  src/Components/PropertyInspector/PropertyInspectorCallout/PropertyInspectorCallout.tsx
  src/Components/PropertyInspector/PropertyInspectorCallout/PropertyInspectorCallout.types.ts
  src/Components/PropertyInspector/PropertyTree/PropertyTree.scss
  src/Components/PropertyInspector/PropertyTree/PropertyTree.tsx
  src/Components/PropertyInspector/PropertyTree/PropertyTree.types.ts
  src/Components/PropertyInspector/StandalonePropertyInspector.tsx
  src/Components/PropertyInspector/StandalonePropertyInspector.types.ts
  src/Components/PropertyInspector/__mockdata__/mockData.ts
  src/Components/PropertyInspector/__tests__/PropertyInspectorModel.test.ts
  src/Components/TwinPropertySearchDropdown/TwinPropertySearchDropdown.types.ts
  src/Components/TwinSearch/TwinSearch.types.ts
  src/Components/index.ts
  src/Models/Constants/Constants.ts
  src/Models/Constants/Interfaces.ts
  src/Resources/Locales/cs.json
  src/Resources/Locales/de.json
  src/Resources/Locales/en.json
  src/Resources/Locales/es.json
  src/Resources/Locales/fr.json
  src/Resources/Locales/hu.json
  src/Resources/Locales/it.json
  src/Resources/Locales/ja.json
  src/Resources/Locales/ko.json
  src/Resources/Locales/nl.json
  src/Resources/Locales/pl.json
  src/Resources/Locales/pt-pt.json
  src/Resources/Locales/pt.json
  src/Resources/Locales/ru.json
  src/Resources/Locales/sv.json
  src/Resources/Locales/tr.json
  src/Resources/Locales/zh-Hans.json
Labels: enhancement :bulb:

#867 OAT: Add toggle for default version number
  src/Components/OATGraphViewer/Internal/Utils.tsx
  src/Components/OATGraphViewer/OATGraphViewer.tsx
  src/Components/OATHeader/OATHeader.stories.tsx
  src/Components/OATHeader/internal/ManageOntologyModal/ManageOntologyModal.stories.tsx
  src/Components/OATHeader/internal/ManageOntologyModal/ManageOntologyModal.styles.ts
  src/Components/OATHeader/internal/ManageOntologyModal/ManageOntologyModal.tsx
  src/Components/OATPropertyEditor/Internal/JSONEditor.tsx
  src/Models/Constants/Constants.ts
  src/Models/Constants/OatConstants.tsx
  src/Models/Context/OatPageContext/OatPageContext.mock.ts
  src/Models/Context/OatPageContext/OatPageContext.stories.tsx
  src/Models/Context/OatPageContext/OatPageContext.tsx
  src/Models/Context/OatPageContext/OatPageContext.types.ts
  src/Models/Context/OatPageContext/OatPageContextUtils.ts
  src/Pages/OATEditorPage/Internal/Classes/ProjectData.ts
  src/Resources/Locales/cs.json
  src/Resources/Locales/de.json
  src/Resources/Locales/en.json
  src/Resources/Locales/es.json
  src/Resources/Locales/fr.json
  src/Resources/Locales/hu.json
  src/Resources/Locales/it.json
  src/Resources/Locales/ja.json
  src/Resources/Locales/ko.json
  src/Resources/Locales/nl.json
  src/Resources/Locales/pl.json
  src/Resources/Locales/pt-pt.json
  src/Resources/Locales/pt.json
  src/Resources/Locales/ru.json
  src/Resources/Locales/sv.json
  src/Resources/Locales/tr.json
  src/Resources/Locales/zh-Hans.json
Labels: enhancement :bulb:, small change :droplet:

#870 OAT: Enable editing of Maps (previously missed)
  src/Components/OATPropertyEditor/Internal/PropertyList/Internal/PropertyListItem/Internal/PropertyListItemChildHost/Internal/PropertyListItemEnumChild/PropertyListItemEnumChild.tsx
  src/Components/OATPropertyEditor/Internal/PropertyList/Internal/PropertyListItem/Internal/PropertyListItemChildHost/Internal/PropertyListItemMapChild/PropertyListItemMapChild.tsx
  src/Components/OATPropertyEditor/Internal/PropertyList/Internal/PropertyListItem/Internal/PropertyListItemChildHost/Internal/PropertyListItemMapChild/PropertyListItemMapChild.types.ts
  src/Components/OATPropertyEditor/Internal/PropertyList/Internal/PropertyListItem/Internal/PropertyListItemChildHost/PropertyListItemChildHost.tsx
  src/Models/Classes/DTDL.ts
  src/Models/Constants/dtdlInterfaces.ts
Labels: enhancement :bulb:, small change :droplet:

#875 feat: OAT: Rework the JSON editing experience
  src/Components/OATPropertyEditor/Editor.styles.ts
  src/Components/OATPropertyEditor/Internal/EditorJsonTab/EditorJsonTab.stories.tsx
  src/Components/OATPropertyEditor/Internal/EditorJsonTab/EditorJsonTab.tsx
  src/Components/OATPropertyEditor/Internal/EditorJsonTab/Internal/JSONEditor/JSONEditor.stories.tsx
  src/Components/OATPropertyEditor/Internal/EditorJsonTab/Internal/JSONEditor/JSONEditor.styles.ts
  src/Components/OATPropertyEditor/Internal/EditorJsonTab/Internal/JSONEditor/JSONEditor.tsx
  src/Components/OATPropertyEditor/Internal/EditorJsonTab/Internal/JSONEditor/JSONEditor.types.ts
  src/Components/OATPropertyEditor/Internal/JSONEditor/JSONEditor.stories.tsx
  src/Components/OATPropertyEditor/Internal/JSONEditor/JSONEditor.styles.ts
  src/Components/OATPropertyEditor/Internal/JSONEditor/JSONEditor.tsx
  src/Components/OATPropertyEditor/OATPropertyEditor.stories.tsx
  src/Models/Context/OatPageContext/OatPageContextUtils.ts
  src/Resources/Locales/cs.json
  src/Resources/Locales/de.json
  src/Resources/Locales/en.json
  src/Resources/Locales/es.json
  src/Resources/Locales/fr.json
  src/Resources/Locales/hu.json
  src/Resources/Locales/it.json
  src/Resources/Locales/ja.json
  src/Resources/Locales/ko.json
  src/Resources/Locales/nl.json
  src/Resources/Locales/pl.json
  src/Resources/Locales/pt-pt.json
  src/Resources/Locales/pt.json
  src/Resources/Locales/ru.json
  src/Resources/Locales/sv.json
  src/Resources/Locales/tr.json
  src/Resources/Locales/zh-Hans.json
Labels: enhancement :bulb:, small change :droplet:

#876 [Data History Explorer]: Final pass
  .storybook/preview.js
  src/Adapters/MockAdapter.ts
  src/Components/BehaviorsModal/Internal/Widgets/DataHistoryWidget/DataHistoryWidget.tsx
  src/Components/DataHistoryExplorer/DataHistoryExplorer.stories.tsx
  src/Components/DataHistoryExplorer/DataHistoryExplorer.tsx
  src/Components/DataHistoryExplorer/DataHistoryExplorer.types.ts
  src/Components/DataHistoryExplorer/Internal/TimeSeriesTwinCallout/TimeSeriesTwinCallout.tsx
  src/Components/DataHistoryExplorer/Internal/TimeSeriesTwinCallout/TimeSeriesTwinCallout.types.ts
  src/Components/DataHistoryExplorer/Internal/TimeSeriesViewer/Internal/TimeSeriesCommandBar/TimeSeriesCommandBar.tsx
  src/Components/DataHistoryExplorer/Internal/TimeSeriesViewer/Internal/TimeSeriesCommandBar/TimeSeriesCommandBar.types.ts
  src/Components/DataHistoryExplorer/Internal/TimeSeriesViewer/TimeSeriesViewer.tsx
  src/Components/DataHistoryExplorer/Internal/TimeSeriesViewer/TimeSeriesViewer.types.ts
  src/Components/DataHistoryExplorerModal/DataHistoryExplorerModal.tsx
  src/Components/DataHistoryExplorerModal/DataHistoryExplorerModal.types.ts
  src/Components/DataHistoryExplorerModal/DataHistoryExplorerModalControl/DataHistoryExplorerModalControl.tsx
  src/Components/HighChartsWrapper/HighChartsWrapper.mock.ts
  src/Components/PropertyInspector/PropertyInspectorCallout/PropertyInspectorCallout.tsx
  src/Models/Constants/Constants.ts
  src/Models/Constants/TelemetryConstants.ts
  src/Models/Context/StableMaxDateInMillisProvider.tsx
  src/Models/Hooks/useMaxDateInMillis.ts
  src/Models/Hooks/useTimeSeriesData.ts
  src/Models/SharedUtils/DataHistoryUtils.ts
  src/Resources/Locales/cs.json
  src/Resources/Locales/de.json
  src/Resources/Locales/en.json
  src/Resources/Locales/es.json
  src/Resources/Locales/fr.json
  src/Resources/Locales/hu.json
  src/Resources/Locales/it.json
  src/Resources/Locales/ja.json
  src/Resources/Locales/ko.json
  src/Resources/Locales/nl.json
  src/Resources/Locales/pl.json
  src/Resources/Locales/pt-pt.json
  src/Resources/Locales/pt.json
  src/Resources/Locales/ru.json
  src/Resources/Locales/sv.json
  src/Resources/Locales/tr.json
  src/Resources/Locales/zh-Hans.json
Labels: bugfix :bug: :white_check_mark:, refactor :hammer:

#882 fix: OAT: add custom validation for renaming properties to avoid duplicate property names
  src/Components/OATPropertyEditor/Internal/EditorJsonTab/Internal/JSONEditor/JSONEditor.tsx
  src/Components/OATPropertyEditor/Internal/PropertyList/Internal/PropertyListItem/PropertyListItem.styles.ts
  src/Components/OATPropertyEditor/Internal/PropertyList/Internal/PropertyListItem/PropertyListItem.tsx
  src/Components/OATPropertyEditor/Internal/PropertyList/Internal/PropertyListItem/PropertyListItem.types.ts
  src/Components/OATPropertyEditor/Internal/PropertyList/PropertyList.tsx
  src/Models/Services/DtdlUtils.ts
  src/Models/Services/OatPublicUtils.ts
  src/Resources/Locales/cs.json
  src/Resources/Locales/de.json
  src/Resources/Locales/en.json
  src/Resources/Locales/es.json
  src/Resources/Locales/fr.json
  src/Resources/Locales/hu.json
  src/Resources/Locales/it.json
  src/Resources/Locales/ja.json
  src/Resources/Locales/ko.json
  src/Resources/Locales/nl.json
  src/Resources/Locales/pl.json
  src/Resources/Locales/pt-pt.json
  src/Resources/Locales/pt.json
  src/Resources/Locales/ru.json
  src/Resources/Locales/sv.json
  src/Resources/Locales/tr.json
  src/Resources/Locales/zh-Hans.json
Labels: bugfix :bug: :white_check_mark:, small change :droplet:

#884 fix: OAT: Handle targets that are arrays
  src/Components/OATGraphViewer/Internal/Utils.tsx
  src/Components/OATGraphViewer/OATGraphViewer.tsx
  src/Models/Constants/dtdlInterfaces.ts
  src/Models/Context/OatPageContext/OatPageContextUtils.ts
Labels: bugfix :bug: :white_check_mark:, small change :droplet:

#891 [Data History Explorer]: fix mock data
  src/Adapters/MockAdapter.ts
  src/Components/HighChartsWrapper/HighChartsWrapper.tsx
  src/Models/SharedUtils/DataHistoryUtils.ts
Labels: bugfix :bug: :white_check_mark:, small change :droplet:, review priority (high) :fire: :fire: :fire:

#885 fix: OAT: block adding self-referencing relationships for Extend or Components
  src/Models/Context/OatPageContext/OatPageContextUtils.ts
Labels: bugfix :bug: :white_check_mark:, small change :droplet:

#892 mockData arg fix for Mock Adapter
  src/Adapters/MockAdapter.ts
  src/Components/ADT3DSceneBuilder/ADT3DSceneBuilder.BehaviorForm.stories.tsx
  src/Components/ADT3DSceneBuilder/ADT3DSceneBuilder.BehaviorList.stories.tsx
  src/Components/ADT3DSceneBuilder/ADT3DSceneBuilder.BehaviorTwinAliasList.stories.tsx
  src/Components/ADT3DSceneBuilder/ADT3DSceneBuilder.ElementTwinAliasList.stories.tsx
  src/Components/ADT3DSceneBuilder/ADT3DSceneBuilder.Elements.stories.tsx
  src/Components/ADT3DSceneBuilder/ADT3DSceneBuilder.VisualRuleList.stories.tsx
  src/Components/ADT3DSceneBuilder/ADT3DSceneBuilder.WidgetsForm.stories.tsx
  src/Components/ADT3DSceneBuilder/ADT3DSceneBuilder.WidgetsList.stories.tsx
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/Twins/BehaviorTwinAliasForm.stories.tsx
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/Widgets/WidgetBuilders/DataHistoryWidgetBuilder/DataHistoryWidgetBuilder.stories.tsx
  src/Components/ADT3DSceneBuilder/Internal/Elements/Internal/ElementTwinAliasForm.stories.tsx
  src/Components/DataHistoryExplorer/DataHistoryExplorer.stories.tsx
  src/Components/PropertyInspector/PropertyInspectorCallout/PropertyInspectorCallout.stories.tsx
  src/Models/Constants/Interfaces.ts
  src/Models/SharedUtils/DataHistoryUtils.ts
  src/Pages/ADT3DScenePage/ADT3DScenePage.stories.tsx
Labels: small change :droplet:, refactor :hammer:

#877 Montgomp/bi widget
  .storybook/secrets.placeholder.js
  jest.setup.ts
  package-lock.json
  package.json
  schemas/3DScenesConfiguration/v1.0.0/3DScenesConfiguration.schema.json
  src/Adapters/ADT3DSceneAdapter.ts
  src/Adapters/MockAdapter.ts
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/Internal/WidgetsTab.tsx
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/Widgets/WidgetForm/WidgetForm.tsx
  src/Components/BehaviorsModal/Internal/Widgets/WidgetsContainer.tsx
  src/Components/PowerBIWidget/Internal/PowerBIWidgetBuilder/PowerBIWidgetBuilder.stories.local.tsx
  src/Components/PowerBIWidget/Internal/PowerBIWidgetBuilder/PowerBIWidgetBuilder.stories.tsx
  src/Components/PowerBIWidget/Internal/PowerBIWidgetBuilder/PowerBIWidgetBuilder.styles.ts
  src/Components/PowerBIWidget/Internal/PowerBIWidgetBuilder/PowerBIWidgetBuilder.tsx
  src/Components/PowerBIWidget/Internal/PowerBIWidgetBuilder/PowerBIWidgetBuilder.types.ts
  src/Components/PowerBIWidget/Internal/PowerBIWidgetBuilder/PowerBIWidgetBuilderAdapter.ts
  src/Components/PowerBIWidget/PowerBIWidget.stories.local.tsx
  src/Components/PowerBIWidget/PowerBIWidget.stories.tsx
  src/Components/PowerBIWidget/PowerBIWidget.styles.ts
  src/Components/PowerBIWidget/PowerBIWidget.tsx
  src/Components/PowerBIWidget/PowerBIWidget.types.ts
  src/Models/Classes/3DVConfig.ts
  src/Models/Classes/AdapterMethodSandbox.ts
  src/Models/Constants/Constants.ts
  src/Models/Constants/Interfaces.ts
  src/Models/Services/MsalAuthService.ts
  src/Models/Types/Generated/3DScenesConfiguration-v1.0.0.d.ts
  src/Resources/Locales/cs.json
  src/Resources/Locales/de.json
  src/Resources/Locales/en.json
  src/Resources/Locales/es.json
  src/Resources/Locales/fr.json
  src/Resources/Locales/hu.json
  src/Resources/Locales/it.json
  src/Resources/Locales/ja.json
  src/Resources/Locales/ko.json
  src/Resources/Locales/nl.json
  src/Resources/Locales/pl.json
  src/Resources/Locales/pt-pt.json
  src/Resources/Locales/pt.json
  src/Resources/Locales/ru.json
  src/Resources/Locales/sv.json
  src/Resources/Locales/tr.json
  src/Resources/Locales/zh-Hans.json
Labels: enhancement :bulb:, large change :ocean:
