Repository microsoft/iot-cardboard-js, pull requests merged in 2023-03, with the labels that each got.

#895 OAT: Give maps custom icon and remove menu
  .eslintrc.json
  src/Components/OATPropertyEditor/Internal/PropertyList/Internal/PropertyListItem/Internal/PropertyIcon/PropertyIcon.tsx
  src/Components/OATPropertyEditor/Internal/PropertyList/Internal/PropertyListItem/Internal/PropertyIcon/PropertyIcon.types.ts
  src/Components/OATPropertyEditor/Internal/PropertyList/Internal/PropertyListItem/Internal/PropertyListItemChildHost/Internal/PropertyListItemArrayChild/PropertyListItemArrayChild.tsx
  src/Components/OATPropertyEditor/Internal/PropertyList/Internal/PropertyListItem/Internal/PropertyListItemChildHost/Internal/PropertyListItemMapChild/PropertyListItemMapChild.tsx
  src/Components/OATPropertyEditor/Internal/PropertyList/Internal/PropertyListItem/PropertyListItem.stories.tsx
  src/Components/OATPropertyEditor/Internal/PropertyList/Internal/PropertyListItem/PropertyListItem.tsx
  src/Components/OATPropertyEditor/Internal/PropertyList/Internal/PropertyListItem/PropertyListItem.types.ts
  src/Components/OATPropertyEditor/Internal/PropertyList/PropertyList.tsx
  src/Models/Constants/Constants.ts
  src/Models/Constants/Types.ts
  src/Resources/Locales/cs.json
  src/Resources/Locales/de.json
  src/Resources/Locales/en.json
  src/Resources/Locales/es.json
  src/Resources/Locales/fr.json
  src/Resources/Locales/hu.json
  src/Resources/Locales/it.json
  src/Resources/Locales/ja.json
  src/Resources/Locales/ko.json
  src/Resources/Locales/nl.json
  src/Resources/Locales/pl.json
  src/Resources/Locales/pt-pt.json
  src/Resources/Locales/pt.json
  src/Resources/Locales/ru.json
  src/Resources/Locales/sv.json
  src/Resources/Locales/tr.json
  src/Resources/Locales/zh-Hans.json
  tools/templates/component/component.js
Labels: small change :droplet:

#896 [Data History Explorer]: Remove feature flags
  src/Adapters/ADTAdapter.ts
  src/Components/PropertyInspector/PropertyTree/PropertyTree.tsx
  src/Models/Constants/Constants.ts
Labels: bugfix :bug: :white_check_mark:, small change :droplet:

#898 Montgomp/power bi content
  src/Components/PowerBIWidget/Internal/PowerBIWidgetBuilder/PowerBIWidgetBuilder.tsx
  src/Components/PowerBIWidget/PowerBIWidget.styles.ts
  src/Components/PowerBIWidget/PowerBIWidget.tsx
  src/Components/PowerBIWidget/PowerBIWidget.types.ts
  src/Resources/Locales/cs.json
  src/Resources/Locales/de.json
  src/Resources/Locales/en.json
  src/Resources/Locales/es.json
  src/Resources/Locales/fr.json
  src/Resources/Locales/hu.json
  src/Resources/Locales/it.json
  src/Resources/Locales/ja.json
  src/Resources/Locales/ko.json
  src/Resources/Locales/nl.json
  src/Resources/Locales/pl.json
  src/Resources/Locales/pt-pt.json
  src/Resources/Locales/pt.json
  src/Resources/Locales/ru.json
  src/Resources/Locales/sv.json
  src/Resources/Locales/tr.json
  src/Resources/Locales/zh-Hans.json
Labels: small change :droplet:

#907 Data pusher fix duplication in URL
  src/Adapters/ADTAdapter.ts
Labels: bugfix :bug: :white_check_mark:

#911 [Legion: Adapters and Data Pusher]: Initial adapter implementations and basic database and table fetching in component
  src/Apps/Legion/Adapters/BaseAdapter.ts
  src/Apps/Legion/Adapters/LegionAdapter.ts
  src/Apps/Legion/Adapters/Mixin/LegionAdapter.ts
  src/Apps/Legion/Adapters/Standalone/DataManagement/ADXAdapter.ts
  src/Apps/Legion/Adapters/Standalone/DataManagement/MockDataManagementAdapter.ts
  src/Apps/Legion/Adapters/Standalone/DataManagement/Models/DataManagementAdapter.data.ts
  src/Apps/Legion/Adapters/Standalone/DataManagement/Models/DataManagementAdapter.types.ts
  src/Apps/Legion/Components/DataPusher/DataPusher.stories.local.tsx
  src/Apps/Legion/Components/DataPusher/DataPusher.stories.tsx
  src/Apps/Legion/Components/DataPusher/DataPusher.styles.ts
  src/Apps/Legion/Components/DataPusher/DataPusher.tsx
  src/Apps/Legion/Components/DataPusher/DataPusher.types.ts
  src/Apps/Legion/Models/Constants.ts
  src/Apps/Legion/Models/Interfaces.ts
  src/Resources/Locales/cs.json
  src/Resources/Locales/de.json
  src/Resources/Locales/en.json
  src/Resources/Locales/es.json
  src/Resources/Locales/fr.json
  src/Resources/Locales/hu.json
  src/Resources/Locales/it.json
  src/Resources/Locales/ja.json
  src/Resources/Locales/ko.json
  src/Resources/Locales/nl.json
  src/Resources/Locales/pl.json
  src/Resources/Locales/pt-pt.json
  src/Resources/Locales/pt.json
  src/Resources/Locales/ru.json
  src/Resources/Locales/sv.json
  src/Resources/Locales/tr.json
  src/Resources/Locales/zh-Hans.json
Labels: enhancement :bulb:, typings :lock:, LegionHackathon :volcano:

#912 WizardShell, navigation and skeleton components
  src/Apps/Legion/Components/StepperWizard/Internal/Step.tsx
  src/Apps/Legion/Components/StepperWizard/Internal/Step.types.ts
  src/Apps/Legion/Components/StepperWizard/Internal/StepSeparator.tsx
  src/Apps/Legion/Components/StepperWizard/Internal/StepSeparator.types.ts
  src/Apps/Legion/Components/StepperWizard/Internal/Stepper.tsx
  src/Apps/Legion/Components/StepperWizard/Internal/Stepper.types.ts
  src/Apps/Legion/Components/StepperWizard/StepperWizard.scss
  src/Apps/Legion/Components/StepperWizard/StepperWizard.stories.tsx
  src/Apps/Legion/Components/StepperWizard/StepperWizard.tsx
  src/Apps/Legion/Components/StepperWizard/StepperWizard.types.ts
  src/Apps/Legion/Components/WizardShell/Internal/DataSourceStep/DataSourceStep.stories.tsx
  src/Apps/Legion/Components/WizardShell/Internal/DataSourceStep/DataSourceStep.styles.ts
  src/Apps/Legion/Components/WizardShell/Internal/DataSourceStep/DataSourceStep.tsx
  src/Apps/Legion/Components/WizardShell/Internal/DataSourceStep/DataSourceStep.types.ts
  src/Apps/Legion/Components/WizardShell/Internal/RelationshipBuilderStep/RelationshipBuilderStep.stories.tsx
  src/Apps/Legion/Components/WizardShell/Internal/RelationshipBuilderStep/RelationshipBuilderStep.styles.ts
  src/Apps/Legion/Components/WizardShell/Internal/RelationshipBuilderStep/RelationshipBuilderStep.tsx
  src/Apps/Legion/Components/WizardShell/Internal/RelationshipBuilderStep/RelationshipBuilderStep.types.ts
  src/Apps/Legion/Components/WizardShell/Internal/SaveStep/SaveStep.stories.tsx
  src/Apps/Legion/Components/WizardShell/Internal/SaveStep/SaveStep.styles.ts
  src/Apps/Legion/Components/WizardShell/Internal/SaveStep/SaveStep.tsx
  src/Apps/Legion/Components/WizardShell/Internal/SaveStep/SaveStep.types.ts
  src/Apps/Legion/Components/WizardShell/Internal/TwinVerificationStep/TwinVerificationStep.stories.tsx
  src/Apps/Legion/Components/WizardShell/Internal/TwinVerificationStep/TwinVerificationStep.styles.ts
  src/Apps/Legion/Components/WizardShell/Internal/TwinVerificationStep/TwinVerificationStep.tsx
  src/Apps/Legion/Components/WizardShell/Internal/TwinVerificationStep/TwinVerificationStep.types.ts
  src/Apps/Legion/Components/WizardShell/WizardShell.stories.tsx
  src/Apps/Legion/Components/WizardShell/WizardShell.tsx
  src/Apps/Legion/Models/Context/WizardNavigationContext/WizardNavigationContext.tsx
  src/Apps/Legion/Models/Context/WizardNavigationContext/WizardNavigationContext.types.ts
Labels: enhancement :bulb:, LegionHackathon :volcano:

#914 [Legion: Data Pusher]: Added CRUD methods to ADXAdapter and basic ingestion
  src/Apps/Legion/Adapters/Mixin/LegionAdapter.ts
  src/Apps/Legion/Adapters/Standalone/DataManagement/ADXAdapter.ts
  src/Apps/Legion/Adapters/Standalone/DataManagement/MockDataManagementAdapter.ts
  src/Apps/Legion/Adapters/Standalone/DataManagement/Models/DataManagementAdapter.types.ts
  src/Apps/Legion/Components/DataPusher/DataPusher.styles.ts
  src/Apps/Legion/Components/DataPusher/DataPusher.tsx
  src/Apps/Legion/Components/DataPusher/DataPusher.types.ts
  src/Apps/Legion/Components/DataPusher/Internal/Cook.tsx
  src/Apps/Legion/Components/DataPusher/Internal/Ingest.tsx
  src/Apps/Legion/Components/DataPusher/Internal/Setup.tsx
  src/Apps/Legion/Models/Interfaces.ts
  src/Resources/Locales/cs.json
  src/Resources/Locales/de.json
  src/Resources/Locales/en.json
  src/Resources/Locales/es.json
  src/Resources/Locales/fr.json
  src/Resources/Locales/hu.json
  src/Resources/Locales/it.json
  src/Resources/Locales/ja.json
  src/Resources/Locales/ko.json
  src/Resources/Locales/nl.json
  src/Resources/Locales/pl.json
  src/Resources/Locales/pt-pt.json
  src/Resources/Locales/pt.json
  src/Resources/Locales/ru.json
  src/Resources/Locales/sv.json
  src/Resources/Locales/tr.json
  src/Resources/Locales/zh-Hans.json
Labels: enhancement :bulb:, refactor :hammer:

#916 [Legion: Data Pusher]: Cook
  src/Apps/Legion/Adapters/Standalone/DataManagement/ADXAdapter.ts
  src/Apps/Legion/Adapters/Standalone/DataManagement/MockDataManagementAdapter.ts
  src/Apps/Legion/Adapters/Standalone/DataManagement/Models/DataManagementAdapter.types.ts
  src/Apps/Legion/Components/DataPusher/DataPusher.styles.ts
  src/Apps/Legion/Components/DataPusher/DataPusher.types.ts
  src/Apps/Legion/Components/DataPusher/Internal/Cook.tsx
  src/Apps/Legion/Components/DataPusher/Internal/Ingest.tsx
  src/Apps/Legion/Components/DataPusher/Internal/Setup.tsx
  src/Apps/Legion/Models/Types.ts
  src/Apps/Legion/Services/DataPusherUtils.ts
Labels: enhancement :bulb:, small change :droplet:, LegionHackathon :volcano:
