Repository microsoft/iot-cardboard-js, pull requests merged in 2023-01, with the labels that each got.

#806 [Resource Picker]: Reverted back to react-select allow input edit on focus and bug fixes
  src/Adapters/AzureManagementAdapter.ts
  src/Components/EnvironmentPicker/EnvironmentPicker.state.ts
  src/Components/ResourcePicker/ResourcePicker.tsx
  src/Models/Context/DeeplinkContext/DeeplinkContext.tsx
  src/Models/Context/DeeplinkContext/DeeplinkContext.types.ts
  src/Models/Services/Utils.ts
  src/Pages/ADT3DScenePage/ADT3DScenePage.tsx
Labels: bugfix :bug: :white_check_mark:

#803 colorPicker theming
  src/Components/Pickers/ColorSelectButton/ColorPicker.stories.tsx
  src/Components/Pickers/Internal/Picker.base.styles.ts
Labels: bugfix :bug: :white_check_mark:, small change :droplet:, styling :art:

#813 [React-select]: Styling fixes
  src/Components/TwinPropertySearchDropdown/TwinPropertySearchDropdown.styles.ts
  src/Components/TwinPropertySearchDropdown/TwinPropertySearchDropdown.tsx
  src/Resources/Styles/ReactSelect.styles.ts
Labels: bugfix :bug: :white_check_mark:

#815 [Environment Picker]: Hiding ARG and permission related error messages
  src/Components/EnvironmentPicker/EnvironmentPicker.tsx
  src/Components/ResourcePicker/ResourcePicker.tsx
  src/Components/ResourcePicker/ResourcePicker.types.ts
  src/Resources/Locales/cs.json
  src/Resources/Locales/de.json
  src/Resources/Locales/en.json
  src/Resources/Locales/es.json
  src/Resources/Locales/fr.json
  src/Resources/Locales/hu.json
  src/Resources/Locales/it.json
  src/Resources/Locales/ja.json
  src/Resources/Locales/ko.json
  src/Resources/Locales/nl.json
  src/Resources/Locales/pl.json
  src/Resources/Locales/pt-pt.json
  src/Resources/Locales/pt.json
  src/Resources/Locales/ru.json
  src/Resources/Locales/sv.json
  src/Resources/Locales/tr.json
  src/Resources/Locales/zh-Hans.json
Labels: small change :droplet:, refactor :hammer:

#817 OAT: Delete relationship
  src/Components/OATGraphViewer/Internal/Classes/ElementEdge.ts
  src/Components/OATGraphViewer/Internal/GraphLegend/GraphLegend.tsx
  src/Components/OATGraphViewer/Internal/OATGraphCustomEdge.tsx
  src/Components/OATGraphViewer/Internal/OATGraphCustomEdge.types.ts
  src/Components/OATGraphViewer/Internal/OATGraphCustomNode.types.ts
  src/Components/OATGraphViewer/Internal/Utils.tsx
  src/Components/OATGraphViewer/OATGraphViewer.styles.tsx
  src/Components/OATGraphViewer/OATGraphViewer.tsx
  src/Components/OATGraphViewer/OATGraphViewer.types.ts
  src/Models/Constants/Constants.ts
  src/Models/Constants/Interfaces.ts
  src/Models/Context/OatPageContext/OatPageContext.tsx
  src/Models/Context/OatPageContext/OatPageContext.types.ts
  src/Models/Context/OatPageContext/OatPageContextUtils.ts
  src/Models/Services/OatUtils.ts
Labels: enhancement :bulb:, small change :droplet:

#808 [Data History Explorer]: Viewer component (with only Chart tab)
  src/Adapters/ADTDataHistoryAdapter.ts
  src/Adapters/MockAdapter.ts
  src/Cards/LinechartCard/LineChartCard.stories.local.tsx
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/Widgets/WidgetBuilders/DataHistoryWidgetBuilder/DataHistoryWidgetBuilder.tsx
  src/Components/ADT3DSceneBuilder/Internal/Behaviors/Widgets/WidgetBuilders/DataHistoryWidgetBuilder/DataHistoryWidgetBuilder.types.ts
  src/Components/BehaviorsModal/Internal/Widgets/DataHistoryWidget/DataHistoryWidget.tsx
  src/Components/BehaviorsModal/Internal/Widgets/DataHistoryWidget/Internal/DataHistoryWidgetErrorHandling.tsx
  src/Components/CardboardModal/CardboardModal.tsx
  src/Components/CardboardModal/CardboardModal.types.ts
  src/Components/DataHistoryExplorer/DataHistoryExplorer.stories.local.tsx
  src/Components/DataHistoryExplorer/DataHistoryExplorer.stories.tsx
  src/Components/DataHistoryExplorer/DataHistoryExplorer.styles.ts
  src/Components/DataHistoryExplorer/DataHistoryExplorer.tsx
  src/Components/DataHistoryExplorer/DataHistoryExplorer.types.ts
  src/Components/DataHistoryExplorer/Internal/TimeSeriesViewer/TimeSeriesViewer.stories.tsx
  src/Components/DataHistoryExplorer/Internal/TimeSeriesViewer/TimeSeriesViewer.styles.ts
  src/Components/DataHistoryExplorer/Internal/TimeSeriesViewer/TimeSeriesViewer.tsx
  src/Components/DataHistoryExplorer/Internal/TimeSeriesViewer/TimeSeriesViewer.types.ts
  src/Components/DataHistoryExplorerModal/DataHistoryExplorerModal.stories.tsx
  src/Components/DataHistoryExplorerModal/DataHistoryExplorerModal.tsx
  src/Components/DataHistoryExplorerModal/DataHistoryExplorerModal.types.ts
  src/Components/HighChartsWrapper/HighChartsWrapper.tsx
  src/Components/IllustrationMessage/IllustrationMessage.tsx
  src/Components/IllustrationMessage/IllustrationMessage.types.tsx
  src/Components/QuickTimesDropdown/QuickTimesDropdown.stories.tsx
  src/Components/QuickTimesDropdown/QuickTimesDropdown.tsx
  src/Components/QuickTimesDropdown/QuickTimesDropdown.types.ts
  src/Models/Constants/Constants.ts
  src/Models/Constants/Enums.ts
  src/Models/Services/__tests__/DataHistoryUtils.test.ts
  src/Models/SharedUtils/DataHistoryUtils.ts
  src/Resources/Locales/cs.json
  src/Resources/Locales/de.json
  src/Resources/Locales/en.json
  src/Resources/Locales/es.json
  src/Resources/Locales/fr.json
  src/Resources/Locales/hu.json
  src/Resources/Locales/it.json
  src/Resources/Locales/ja.json
  src/Resources/Locales/ko.json
  src/Resources/Locales/nl.json
  src/Resources/Locales/pl.json
  src/Resources/Locales/pt-pt.json
  src/Resources/Locales/pt.json
  src/Resources/Locales/ru.json
  src/Resources/Locales/sv.json
  src/Resources/Locales/tr.json
  src/Resources/Locales/zh-Hans.json
Labels: enhancement :bulb:, large change :ocean:

#824 OAT: Polishing graph experience
  src/Components/OATGraphViewer/Internal/OATGraphCustomEdge.tsx
  src/Components/OATModelList/OATModelList.tsx
Labels: bugfix :bug: :white_check_mark:, small change :droplet:

#830 OAT: Fix auto layout
  .eslintrc.json
  src/Components/OATGraphViewer/OATGraphViewer.tsx
  src/Models/Context/OatPageContext/OatPageContext.tsx
Labels: bugfix :bug: :white_check_mark:, small change :droplet:

#831 OAT: Fix bug with switching causing crash
  src/Models/Context/OatPageContext/OatPageContext.tsx
  src/Models/Context/OatPageContext/OatPageContext.types.ts
  src/Models/Context/OatPageContext/OatPageContextUtils.ts
  src/Models/Services/OatUtils.ts
  src/Pages/OATEditorPage/Internal/Classes/OatTypes.ts
  src/Pages/OATEditorPage/Internal/Classes/ProjectData.ts
Labels: bugfix :bug: :white_check_mark:, small change :droplet:

#832 Iteratively remove models when they fail the parser
  src/Adapters/__mockData__/MockAdapterData/MockModelData.json
  src/Models/Services/Utils.ts
Labels: bug :bug:, high priority :heavy_exclamation_mark:, small change :droplet:

#837 OAT: Revamp property editor styling and expand in JSON mode
  src/Components/OATGraphViewer/Internal/OATGraphCustomEdge.tsx
  src/Components/OATGraphViewer/Internal/OATGraphCustomNode.tsx
  src/Components/OATGraphViewer/OATGraphViewer.styles.tsx
  src/Components/OATGraphViewer/OATGraphViewer.tsx
  src/Components/OATModelList/OATModelList.tsx
  src/Components/OATPropertyEditor/Editor.styles.ts
  src/Components/OATPropertyEditor/Editor.tsx
  src/Components/OATPropertyEditor/Editor.types.ts
  src/Components/OATPropertyEditor/Internal/EditorJsonTab/EditorJsonTab.stories.tsx
  src/Components/OATPropertyEditor/Internal/EditorJsonTab/EditorJsonTab.styles.ts
  src/Components/OATPropertyEditor/Internal/EditorJsonTab/EditorJsonTab.tsx
  src/Components/OATPropertyEditor/Internal/EditorJsonTab/EditorJsonTab.types.ts
  src/Components/OATPropertyEditor/Internal/EditorPropertiesTab/EditorPropertiesTab.stories.tsx
  src/Components/OATPropertyEditor/Internal/EditorPropertiesTab/EditorPropertiesTab.styles.ts
  src/Components/OATPropertyEditor/Internal/EditorPropertiesTab/EditorPropertiesTab.tsx
  src/Components/OATPropertyEditor/Internal/EditorPropertiesTab/EditorPropertiesTab.types.ts
  src/Components/OATPropertyEditor/Internal/FormAddEnumItem.tsx
  src/Components/OATPropertyEditor/Internal/FormAddEnumItem.types.ts
  src/Components/OATPropertyEditor/Internal/JSONEditor.tsx
  src/Components/OATPropertyEditor/Internal/PropertiesModelSummary.tsx
  src/Components/OATPropertyEditor/Internal/PropertyList/PropertyList.stories.tsx
  src/Components/OATPropertyEditor/Internal/PropertyTypePicker/PropertyTypePicker.stories.tsx
  src/Components/OATPropertyEditor/OATPropertyEditor.stories.tsx
  src/Components/OATPropertyEditor/OATPropertyEditor.styles.ts
  src/Models/Constants/OatStyleConstants.ts
  src/Models/Context/OatPageContext/OatPageContext.tsx
  src/Models/Context/OatPageContext/OatPageContext.types.ts
  src/Models/Context/OatPageContext/OatPageContextUtils.ts
  src/Models/Services/DtdlUtils.ts
  src/Pages/OATEditorPage/Internal/Classes/OatTypes.ts
  src/Pages/OATEditorPage/OATEditorPage.styles.tsx
  src/Pages/OATEditorPage/OATEditorPage.tsx
  src/Resources/Locales/cs.json
  src/Resources/Locales/de.json
  src/Resources/Locales/en.json
  src/Resources/Locales/es.json
  src/Resources/Locales/fr.json
  src/Resources/Locales/hu.json
  src/Resources/Locales/it.json
  src/Resources/Locales/ja.json
  src/Resources/Locales/ko.json
  src/Resources/Locales/nl.json
  src/Resources/Locales/pl.json
  src/Resources/Locales/pt-pt.json
  src/Resources/Locales/pt.json
  src/Resources/Locales/ru.json
  src/Resources/Locales/sv.json
  src/Resources/Locales/tr.json
  src/Resources/Locales/zh-Hans.json
Labels: bugfix :bug: :white_check_mark:, large change :ocean:, refactor :hammer:

#838 OAT: Add ellipsing to long ids and names
  src/Components/OATGraphViewer/Internal/OATGraphCustomNode.tsx
  src/Components/OATGraphViewer/OATGraphViewer.styles.tsx
  src/Components/OATGraphViewer/OATGraphViewer.tsx
  src/Components/OATPropertyEditor/Internal/ModelPropertyHeader/ModelPropertyHeader.styles.ts
  src/Models/Constants/OatStyleConstants.ts
Labels: small change :droplet:, styling :art:

#835 [Data History Explorer]: Revised the TimeSeriesViewer and added internal components
  src/Components/BehaviorsModal/Internal/Widgets/DataHistoryWidget/DataHistoryWidget.tsx
  src/Components/DataHistoryExplorer/DataHistoryExplorer.stories.tsx
  src/Components/DataHistoryExplorer/DataHistoryExplorer.tsx
  src/Components/DataHistoryExplorer/Internal/TimeSeriesBuilder/TimeSeriesBuilder.stories.tsx
  src/Components/DataHistoryExplorer/Internal/TimeSeriesBuilder/TimeSeriesBuilder.styles.ts
  src/Components/DataHistoryExplorer/Internal/TimeSeriesBuilder/TimeSeriesBuilder.tsx
  src/Components/DataHistoryExplorer/Internal/TimeSeriesBuilder/TimeSeriesBuilder.types.ts
  src/Components/DataHistoryExplorer/Internal/TimeSeriesTwinCallout/TimeSeriesTwinCallout.stories.tsx
  src/Components/DataHistoryExplorer/Internal/TimeSeriesTwinCallout/TimeSeriesTwinCallout.tsx
  src/Components/DataHistoryExplorer/Internal/TimeSeriesViewer/Internal/TimeSeriesChart/Internal/ChartCommandBar/ChartCommandBar.stories.tsx
  src/Components/DataHistoryExplorer/Internal/TimeSeriesViewer/Internal/TimeSeriesChart/Internal/ChartCommandBar/ChartCommandBar.styles.ts
  src/Components/DataHistoryExplorer/Internal/TimeSeriesViewer/Internal/TimeSeriesChart/Internal/ChartCommandBar/ChartCommandBar.tsx
  src/Components/DataHistoryExplorer/Internal/TimeSeriesViewer/Internal/TimeSeriesChart/Internal/ChartCommandBar/ChartCommandBar.types.ts
  src/Components/DataHistoryExplorer/Internal/TimeSeriesViewer/Internal/TimeSeriesChart/TimeSeriesChart.stories.tsx
  src/Components/DataHistoryExplorer/Internal/TimeSeriesViewer/Internal/TimeSeriesChart/TimeSeriesChart.styles.ts
  src/Components/DataHistoryExplorer/Internal/TimeSeriesViewer/Internal/TimeSeriesChart/TimeSeriesChart.tsx
  src/Components/DataHistoryExplorer/Internal/TimeSeriesViewer/Internal/TimeSeriesChart/TimeSeriesChart.types.ts
  src/Components/DataHistoryExplorer/Internal/TimeSeriesViewer/TimeSeriesViewer.stories.tsx
  src/Components/DataHistoryExplorer/Internal/TimeSeriesViewer/TimeSeriesViewer.styles.ts
  src/Components/DataHistoryExplorer/Internal/TimeSeriesViewer/TimeSeriesViewer.tsx
  src/Components/DataHistoryExplorerModal/DataHistoryExplorerModal.stories.tsx
  src/Components/HighChartsWrapper/HighChartsWrapper.styles.ts
  src/Components/HighChartsWrapper/HighChartsWrapper.tsx
  src/Components/HighChartsWrapper/HighChartsWrapper.types.ts
  src/Components/QuickTimesDropdown/QuickTimesDropdown.tsx
  src/Models/Constants/Constants.ts
  src/Models/Constants/Interfaces.ts
  src/Models/Services/Utils.ts
  src/Models/Services/__tests__/DataHistoryUtils.test.ts
  src/Models/SharedUtils/DataHistoryUtils.ts
Labels: refactor :hammer:

#840 [Data History Explorer]: Telemetry and Logging
  src/Adapters/ADTDataHistoryAdapter.ts
  src/Adapters/ADXAdapter.ts
  src/Components/DataHistoryExplorer/DataHistoryExplorer.tsx
  src/Components/DataHistoryExplorer/Internal/TimeSeriesBuilder/TimeSeriesBuilder.tsx
  src/Components/DataHistoryExplorer/Internal/TimeSeriesTwinCallout/TimeSeriesTwinCallout.tsx
  src/Components/DataHistoryExplorer/Internal/TimeSeriesViewer/Internal/TimeSeriesChart/Internal/ChartCommandBar/ChartCommandBar.tsx
  src/Components/DataHistoryExplorer/Internal/TimeSeriesViewer/Internal/TimeSeriesChart/TimeSeriesChart.tsx
  src/Components/DataHistoryExplorer/Internal/TimeSeriesViewer/Internal/TimeSeriesTable/Internal/TableCommandBar/TableCommandBar.tsx
  src/Components/DataHistoryExplorer/Internal/TimeSeriesViewer/Internal/TimeSeriesTable/TimeSeriesTable.tsx
  src/Components/DataHistoryExplorer/Internal/TimeSeriesViewer/TimeSeriesViewer.tsx
  src/Components/DataHistoryExplorer/Internal/TimeSeriesViewer/TimeSeriesViewer.types.ts
  src/Models/Constants/TelemetryConstants.ts
  src/Models/SharedUtils/DataHistoryUtils.ts
Labels: enhancement :bulb:
