Repository microsoft/iot-cardboard-js, pull requests merged in 2023-04, with the labels that each got.

#915 [Legion] Model and Twin verification step
  src/Apps/Legion/Components/WizardShell/Internal/TwinVerificationStep/Internal/ModelLists.tsx
  src/Apps/Legion/Components/WizardShell/Internal/TwinVerificationStep/Internal/PropertySelector.tsx
  src/Apps/Legion/Components/WizardShell/Internal/TwinVerificationStep/Internal/TwinLists.tsx
  src/Apps/Legion/Components/WizardShell/Internal/TwinVerificationStep/TwinVerificationMockData.ts
  src/Apps/Legion/Components/WizardShell/Internal/TwinVerificationStep/TwinVerificationStep.stories.tsx
  src/Apps/Legion/Components/WizardShell/Internal/TwinVerificationStep/TwinVerificationStep.styles.ts
  src/Apps/Legion/Components/WizardShell/Internal/TwinVerificationStep/TwinVerificationStep.tsx
  src/Apps/Legion/Components/WizardShell/Internal/TwinVerificationStep/TwinVerificationStep.types.ts
  src/Apps/Legion/Components/WizardShell/WizardShell.stories.tsx
  src/Apps/Legion/Components/WizardShell/WizardShell.styles.ts
  src/Apps/Legion/Components/WizardShell/WizardShell.tsx
  src/Apps/Legion/Components/WizardShell/WizardShell.types.ts
  src/Apps/Legion/Models/Context/WizardNavigationContext/WizardNavigationContext.tsx
  src/Apps/Legion/Models/Context/WizardNavigationContext/WizardNavigationContext.types.ts
Labels: enhancement :bulb:, wip 🚧, LegionHackathon :volcano:

#922 Adding store list data to local storage
  src/Apps/Legion/Components/StoreFormModal/StoreFormModal.stories.tsx
  src/Apps/Legion/Components/StoreFormModal/StoreFormModal.styles.ts
  src/Apps/Legion/Components/StoreFormModal/StoreFormModal.tsx
  src/Apps/Legion/Components/StoreFormModal/StoreFormModal.types.ts
  src/Apps/Legion/Components/StoreList/StoreList.stories.tsx
  src/Apps/Legion/Components/StoreList/StoreList.tsx
  src/Apps/Legion/Components/WizardShell/WizardShell.tsx
  src/Apps/Legion/Contexts/AppDataContext/AppDataContext.types.ts
  src/Apps/Legion/Models/Constants.ts
  src/Apps/Legion/Pages/StoreListPage/StoreListPage.stories.tsx
  src/Apps/Legion/Pages/StoreListPage/StoreListPage.tsx
  src/Apps/Legion/Services/LocalStorageManager.ts
  src/Resources/Locales/cs.json
  src/Resources/Locales/de.json
  src/Resources/Locales/en.json
  src/Resources/Locales/es.json
  src/Resources/Locales/fr.json
  src/Resources/Locales/hu.json
  src/Resources/Locales/it.json
  src/Resources/Locales/ja.json
  src/Resources/Locales/ko.json
  src/Resources/Locales/nl.json
  src/Resources/Locales/pl.json
  src/Resources/Locales/pt-pt.json
  src/Resources/Locales/pt.json
  src/Resources/Locales/ru.json
  src/Resources/Locales/sv.json
  src/Resources/Locales/tr.json
  src/Resources/Locales/zh-Hans.json
Labels: enhancement :bulb:, small change :droplet:, LegionHackathon :volcano:

#923 Wizard shell grid
  src/Apps/Legion/Components/WizardShell/Internal/DataSourceStep/DataSourceStep.tsx
  src/Apps/Legion/Components/WizardShell/Internal/TwinVerificationStep/Internal/ModelLists.tsx
  src/Apps/Legion/Components/WizardShell/WizardShell.styles.ts
  src/Apps/Legion/Components/WizardShell/WizardShell.tsx
  src/Apps/Legion/Components/WizardShell/WizardShell.types.ts
  src/Apps/Legion/Contexts/WizardNavigationContext/WizardNavigationContext.tsx
  src/Apps/Legion/Contexts/WizardNavigationContext/WizardNavigationContext.types.ts
Labels: refactor :hammer:, LegionHackathon :volcano:

#924 [Legion: Data pusher changes]: Merged create & ingest and revised
  src/Apps/Legion/Adapters/Standalone/DataManagement/ADXAdapter.ts
  src/Apps/Legion/Adapters/Standalone/DataManagement/MockDataManagementAdapter.ts
  src/Apps/Legion/Adapters/Standalone/DataManagement/Models/DataManagementAdapter.types.ts
  src/Apps/Legion/Components/DataPusher/DataPusher.stories.local.tsx
  src/Apps/Legion/Components/DataPusher/DataPusher.stories.tsx
  src/Apps/Legion/Components/DataPusher/DataPusher.styles.ts
  src/Apps/Legion/Components/DataPusher/DataPusher.tsx
  src/Apps/Legion/Components/DataPusher/DataPusher.types.ts
  src/Apps/Legion/Components/DataPusher/Internal/ConnectionStringPicker.tsx
  src/Apps/Legion/Components/DataPusher/Internal/Cook.tsx
  src/Apps/Legion/Components/DataPusher/Internal/Ingest.tsx
  src/Apps/Legion/Components/DataPusher/Internal/Setup.tsx
  src/Apps/Legion/Components/WizardShell/Internal/DataSourceStep/DataSourceStep.tsx
  src/Apps/Legion/Services/DataPusherUtils.ts
  src/Models/Constants/Enums.ts
  src/Resources/Locales/cs.json
  src/Resources/Locales/de.json
  src/Resources/Locales/en.json
  src/Resources/Locales/es.json
  src/Resources/Locales/fr.json
  src/Resources/Locales/hu.json
  src/Resources/Locales/it.json
  src/Resources/Locales/ja.json
  src/Resources/Locales/ko.json
  src/Resources/Locales/nl.json
  src/Resources/Locales/pl.json
  src/Resources/Locales/pt-pt.json
  src/Resources/Locales/pt.json
  src/Resources/Locales/ru.json
  src/Resources/Locales/sv.json
  src/Resources/Locales/tr.json
  src/Resources/Locales/zh-Hans.json
Labels: refactor :hammer:, LegionHackathon :volcano:

#902 [forceCORS and use proxy]: Fixes for storage account url and handling missing CORS
  src/Adapters/ADT3DSceneAdapter.ts
  src/Adapters/BlobAdapter.ts
  src/Adapters/MockAdapter.ts
  src/Components/EnvironmentPicker/EnvironmentPicker.tsx
  src/Components/IllustrationMessage/IllustrationMessage.stories.tsx
  src/Components/IllustrationMessage/IllustrationMessage.tsx
  src/Components/IllustrationMessage/IllustrationMessage.types.tsx
  src/Components/OATModelList/OATModelList.tsx
  src/Components/SceneList/SceneList.scss
  src/Components/SceneList/SceneList.tsx
  src/Components/ScenePageErrorHandlingWrapper/ScenePageErrorHandlingWrapper.tsx
  src/Components/ScenePageErrorHandlingWrapper/ScenePageErrorHandlingWrapper.types.ts
  src/Models/Classes/AdapterMethodSandbox.ts
  src/Models/Constants/Constants.ts
  src/Models/Constants/Enums.ts
  src/Pages/ADT3DScenePage/ADT3DScenePage.tsx
  src/Pages/ADT3DScenePage/ADT3DScenePage.types.ts
  src/Resources/Locales/cs.json
  src/Resources/Locales/de.json
  src/Resources/Locales/en.json
  src/Resources/Locales/es.json
  src/Resources/Locales/fr.json
  src/Resources/Locales/hu.json
  src/Resources/Locales/it.json
  src/Resources/Locales/ja.json
  src/Resources/Locales/ko.json
  src/Resources/Locales/nl.json
  src/Resources/Locales/pl.json
  src/Resources/Locales/pt-pt.json
  src/Resources/Locales/pt.json
  src/Resources/Locales/ru.json
  src/Resources/Locales/sv.json
  src/Resources/Locales/tr.json
  src/Resources/Locales/zh-Hans.json
Labels: bugfix :bug: :white_check_mark:, refactor :hammer:

#938 [Private Links]: Bugfix for null check if ARG fails
  src/Adapters/ADT3DSceneAdapter.ts
Labels: bugfix :bug: :white_check_mark:

#939 Legion/montgomp/extension client
  src/Apps/Legion/Contexts/AppDataContext/AppDataContext.types.ts
  src/Apps/Legion/EntryPoints/LegionApp/LegionApp.tsx
  src/Apps/Legion/EntryPoints/LegionApp/LegionApp.types.ts
  src/Apps/Legion/EntryPoints/LegionApp/ShellTypes.d.ts
Labels: LegionHackathon :volcano:

#941 OAT telemetry fix
  src/Components/OATHeader/OATHeader.tsx
  src/Components/OATPropertyEditor/Internal/EditorPropertiesTab/EditorPropertiesTab.tsx
  src/Models/Context/OatPageContext/OatPageContextUtils.ts
  src/Pages/OATEditorPage/OATEditorPage.tsx
Labels: bugfix :bug: :white_check_mark:

#940 Legion: Types tab
  src/Apps/Legion/Components/WizardShell/Internal/ModifyStep/Internal/EntitiesTab/EntitiesTab.stories.tsx
  src/Apps/Legion/Components/WizardShell/Internal/ModifyStep/Internal/TypesTab/Internal/TypesCard/TypesCard.styles.ts
  src/Apps/Legion/Components/WizardShell/Internal/ModifyStep/Internal/TypesTab/Internal/TypesCard/TypesCard.tsx
  src/Apps/Legion/Components/WizardShell/Internal/ModifyStep/Internal/TypesTab/Internal/TypesCard/TypesCard.types.ts
  src/Apps/Legion/Components/WizardShell/Internal/ModifyStep/Internal/TypesTab/TypesTab.styles.ts
  src/Apps/Legion/Components/WizardShell/Internal/ModifyStep/Internal/TypesTab/TypesTab.tsx
  src/Apps/Legion/Components/WizardShell/Internal/ModifyStep/Internal/TypesTab/TypesTab.types.ts
  src/Apps/Legion/Components/WizardShell/Internal/ModifyStep/ModifyStep.tsx
  src/Apps/Legion/Hooks/useEntities.tsx
  src/Apps/Legion/Hooks/useTypes.tsx
  src/Apps/Legion/Models/Wizard.types.ts
  src/Resources/Locales/cs.json
  src/Resources/Locales/de.json
  src/Resources/Locales/en.json
  src/Resources/Locales/es.json
  src/Resources/Locales/fr.json
  src/Resources/Locales/hu.json
  src/Resources/Locales/it.json
  src/Resources/Locales/ja.json
  src/Resources/Locales/ko.json
  src/Resources/Locales/nl.json
  src/Resources/Locales/pl.json
  src/Resources/Locales/pt-pt.json
  src/Resources/Locales/pt.json
  src/Resources/Locales/ru.json
  src/Resources/Locales/sv.json
  src/Resources/Locales/tr.json
  src/Resources/Locales/zh-Hans.json
Labels: LegionHackathon :volcano:
